project:
  type: website

website:
  title: "MASTEMR"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - quarto_help.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

