---
# title: English DfE
---

There are four main data sources that you can use to gain information about education in England:

- [School performance tables](https://www.gov.uk/school-performance-tables) - yearly snapshots of school results and descriptors, used for performance tables and summary websites
- [School workforce census](https://www.gov.uk/government/collections/statistics-school-workforce) - the DfE takes a census of timetabling and staffing each year during one week in November. About 70-80% of state schools respond to this census. It provides information on taught hours of subject, staffing levels and democgraphics and school vacancies.
- [get-information-schools](https://www.get-information-schools.service.gov.uk) school provider information
- ONS SRS restricted datasets, see below.

### Students

```{r}

```



### Schools

Education provider details, also known as _edubase_ can be found [here](https://www.get-information-schools.service.gov.uk/Downloads). This dataset includes a live snapshot about all ~40,000 providers, current and historic, including name, school type, headteacher details, geographic location etc. Current Ofsted results.

To get a yearly snapshot of providers including their Oftsed grade, Progress 8 score, EAL \%, Pupil Premium \% etc. you can use the [School performance tables](https://www.gov.uk/school-performance-tables), in particular the [download data](https://www.find-school-performance-data.service.gov.uk/download-data) area. You can select a year and then choose the data to suit your needs. The options you are presented with might appear a little overlapping, it's worth downloading a few files to see which best suit your needs, for example:

- _School information_ high level data on the name, location and type of school.
- _Key stage 4 results (final)_ school level results and demographic details, e.g. pupil premium %, EBACC and Progress 8.
- _Key stage 4 qualification and subject data (final)_ subject level data for schools, including number of entries and results for each subject in each school.

When downloading the data, you will be faced by a wall of acronyms some might make sense: `AGELOW`, `AGEHIGH`, others might be a little more confusing: `TPUP`, `TPRIORHI`. You can download an _Explanation of terminology used in the data files_ alongside the data you choose. The table below might also help when interpreting the _Key stage 4 results (final)_ (taken from the explanation file):

<details>
<summary>schools description</summary>
|Column|Metafile heading               |Metafile description                                                                                                                                    |
|------|-------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------|
|1     |RECTYPE                        |Record type (1=mainstream school; 2=special school; 4=local authority; 5=National (all schools); 7=National (maintained schools))                       |
|2     |LEA                            |Local authority code (see separate list of local authorities and their codes)                                                                           |
|3     |ESTAB                          |Establishment number                                                                                                                                    |
|4     |URN                            |School Unique Reference Number                                                                                                                          |
|5     |SCHNAME                        |School name                                                                                                                                             |
|6     |SCHNAME_AC                     |School now known as (used if the school has converted to an academy on or after 12 Sept 2018)                                                           |
|7     |ADDRESS1                       |School address (1)                                                                                                                                      |
|8     |ADDRESS2                       |School address (2)                                                                                                                                      |
|9     |ADDRESS3                       |School address (3)                                                                                                                                      |
|10    |TOWN                           |School town                                                                                                                                             |
|11    |PCODE                          |School postcode                                                                                                                                         |
|12    |TELNUM                         |School telephone number                                                                                                                                 |
|13    |PCON_CODE                      |Parliamentary constituency code                                                                                                                         |
|14    |PCON_NAME                      |Parliamentary constituency name                                                                                                                         |
|15    |CONTFLAG                       |Contingency flag - school results 'significantly affected'. This field is zero for all schools.                                                         |
|16    |ICLOSE                         |Closed school flag (0=open; 1=closed)                                                                                                                   |
|17    |NFTYPE                         |School type (see separate list of abbreviations used in the tables)                                                                                     |
|18    |RELDENOM                       |School religious character                                                                                                                              |
|19    |ADMPOL                         |School admissions policy (self-declared by schools on Edubase)                                                                                          |
|20    |ADMPOL_PT                      |School admissions policy - new definition from 2019                                                                                                     |
|21    |EGENDER                        |School gender of entry                                                                                                                                  |
|22    |FEEDER                         |Indicates whether school is a feeder school for sixth form centre/consortia (0=No; 1=Yes)                                                               |
|23    |TABKS2                         |Indicates whether school is published in the primary school (key stage 2) performance tables (0=No; 1=Yes)                                              |
|24    |TAB1618                        |Indicates whether school is published in the school and college (16-18) performance tables (0=No; 1=Yes)                                                |
|25    |AGERANGE                       |Age range                                                                                                                                               |
|26    |TOTPUPS                        |Number of pupils on roll (all ages)                                                                                                                     |
|27    |NUMBOYS                        |Total boys on roll (including part-time pupils)                                                                                                         |
|28    |NUMGIRLS                       |Total girls on roll (including part-time pupils)                                                                                                        |
|29    |TPUP                           |Number of pupils at the end of key stage 4                                                                                                              |
|30    |BPUP                           |Number of boys at the end of key stage 4                                                                                                                |
|31    |PBPUP                          |% of pupils at the end of key stage 4 who are boys                                                                                                      |
|32    |GPUP                           |Number of girls at the end of key stage 4                                                                                                               |
|33    |PGPUP                          |% of pupils at the end key stage 4 who are girls                                                                                                        |
|34    |KS2ASS                         |KS4 cohort average KS2 Scaled Score (average of English reading and maths)                                                                              |
|35    |TPRIORLO                       |Number of pupils at the end of key stage 4 with low prior attainment at the end of key stage 2                                                          |
|36    |PTPRIORLO                      |% of pupils at the end of key stage 4 with low prior attainment at the end of key stage 2                                                               |
|37    |TPRIORAV                       |Number of pupils at the end of key stage 4 with middle prior attainment at the end of key stage 2                                                       |
|38    |PTPRIORAV                      |% of pupils at the end of key stage 4 with middle prior attainment at the end of key stage 2                                                            |
|39    |TPRIORHI                       |Number of pupils at the end of key stage 4 with high prior attainment at the end of key stage 2                                                         |
|40    |PTPRIORHI                      |% of pupils at the end of key stage 4 with high prior attainment at the end of key stage 2                                                              |
|41    |TFSM6CLA1A                     |Number of disadvantaged pupils at the end of key stage 4                                                                                                |
|42    |PTFSM6CLA1A                    |% of pupils at the end of key stage 4 who are disadvantaged                                                                                             |
|43    |TNOTFSM6CLA1A                  |Number of non-disadvantaged pupils at the end of key stage 4                                                                                            |
|44    |PTNOTFSM6CLA1A                 |% of pupils at the end of key stage 4 who are not disadvantaged                                                                                         |
|45    |TEALGRP2                       |Number of pupils at the end of key stage 4 with English as additional language (EAL)                                                                    |
|46    |PTEALGRP2                      |% of pupils at the end of key stage 4 with English as additional language (EAL)                                                                         |
|47    |TEALGRP1                       |Number of pupils at the end of key stage 4 with English as their first language                                                                         |
|48    |PTEALGRP1                      |% of pupils at the end of key stage 4 with English as their first language                                                                              |
|49    |TEALGRP3                       |Number of pupils at the end of key stage 4 whose first language is unclassified                                                                         |
|50    |PTEALGRP3                      |% of pupils at the end of key stage 4 whose first language is unclassified                                                                              |
|51    |TNMOB                          |Number of pupils at the end of key stage 4 who are non-mobile                                                                                           |
|52    |PTNMOB                         |% of pupils at the end of key stage 4 who are non-mobile                                                                                                |
|53    |SENE4                          |Number of pupils at the end of key stage 4 with special educational needs (SEN) with an Education, health and care (EHC) plan                           |
|54    |PSENE4                         |% of pupils at the end of key stage 4 with special educational needs (SEN) with an Education, health and care (EHC) plan                                |
|55    |SEN_ALL4                       |Number of pupils at the end of key stage 4 with special educational needs (SEN) including those with or without an Education, health and care (EHC) plan|
|56    |PSEN_ALL4                      |% of pupils at the end of key stage 4 with special educational needs (SEN) including those with or without an Education, health and care (EHC) plan     |
|57    |SENK4                          |Number of pupils at the end of key stage 4 with special educational needs (SEN) without an Education, health and care (EHC) plan                        |
|58    |PSENK4                         |% of pupils at the end of key stage 4 with special educational needs (SEN) without an Education, health and care (EHC) plan                             |
|59    |TOTATT8                        |Total sum of Attainment 8 scores                                                                                                                        |
|60    |ATT8SCR                        |Average Attainment 8 score per pupil                                                                                                                    |
|61    |TOTATT8ENG                     |Total sum of Attainment 8 scores for English element                                                                                                    |
|62    |ATT8SCRENG                     |Average Attainment 8 score per pupil for English element                                                                                                |
|63    |TOTATT8MAT                     |Total sum of Attainment 8 scores for mathematics element                                                                                                |
|64    |ATT8SCRMAT                     |Average Attainment 8 score per pupil for mathematics element                                                                                            |
|65    |TOTATT8EBAC                    |Total sum of Attainment 8 scores for EBacc element                                                                                                      |
|66    |ATT8SCREBAC                    |Average Attainment 8 score per pupil for EBacc element                                                                                                  |
|67    |TOTATT8OPEN                    |Total sum of Attainment 8 scores for open element                                                                                                       |
|68    |ATT8SCROPEN                    |Average Attainment 8 score per pupil for open element                                                                                                   |
|69    |TOTATT8OPENG                   |Total sum of Attainment 8 scores for open element - GCSE only                                                                                           |
|70    |ATT8SCROPENG                   |Average Attainment 8 score per pupil for open element - GCSE only                                                                                       |
|71    |TOTATT8OPENNG                  |Total sum of Attainment 8 scores for open element - non-GCSE only                                                                                       |
|72    |ATT8SCROPENNG                  |Average Attainment 8 score per pupil for open element - non-GCSE only                                                                                   |
|73    |AVGEBACFILL                    |Average number of EBacc slots filled in Attainment 8 per pupil                                                                                          |
|74    |AVGOPENFILL                    |Average number of Open slots filled in Attainment 8 per pupil                                                                                           |
|75    |P8PUP                          |Number of pupils included in Progress 8 measure                                                                                                         |
|76    |TP8ADJ                         |Number of pupils who have had P8 score adjusted in average                                                                                              |
|77    |P8MEACOV                       |% of pupils at the end of key stage 4 included in Progress 8 measure                                                                                    |
|78    |P8MEA                          |Progress 8 measure after adjustment for extreme scores                                                                                                  |
|79    |P8CILOW                        |Progress 8 lower 95% confidence interval for adjusted average                                                                                           |
|80    |P8CIUPP                        |Progress 8 upper 95% confidence interval for adjusted average                                                                                           |
|81    |P8MEA_ORIG                     |Progress 8 measure based on unadjusted pupil scores                                                                                                     |
|82    |P8CILOW_ORIG                   |Progress 8 lower 95% confidence interval for unadjusted average                                                                                         |
|83    |P8CIUPP_ORIG                   |Progress 8 upper 95% confidence interval for unadjusted average                                                                                         |
|84    |P8MEAENG                       |Progress 8 measure for English element                                                                                                                  |
|85    |P8MEAENG_CILOW                 |Lower 95% confidence interval for Progress 8 English element                                                                                            |
|86    |P8MEAENG_CIUPP                 |Upper 95% confidence interval for Progress 8 English element                                                                                            |
|87    |P8MEAMAT                       |Progress 8 measure for mathematics element                                                                                                              |
|88    |P8MEAMAT_CILOW                 |Lower 95% confidence interval for Progress 8 maths element                                                                                              |
|89    |P8MEAMAT_CIUPP                 |Upper 95% confidence interval for Progress 8 maths element                                                                                              |
|90    |P8MEAEBAC                      |Progress 8 measure for EBacc element                                                                                                                    |
|91    |P8MEAEBAC_CILOW                |Lower 95% confidence interval for Progress 8 EBacc element                                                                                              |
|92    |P8MEAEBAC_CIUPP                |Upper 95% confidence interval for Progress 8 EBacc element                                                                                              |
|93    |P8MEAOPEN                      |Progress 8 measure for open element                                                                                                                     |
|94    |P8MEAOPEN_CILOW                |Lower 95% confidence interval for Progress 8 open element                                                                                               |
|95    |P8MEAOPEN_CIUPP                |Upper 95% confidence interval for Progress 8 open element                                                                                               |
|96    |PTL2BASICS_94                  |% of pupils achieving standard 9-4 passes in both English and mathematics GCSEs                                                                         |
|97    |PTL2BASICS_95                  |% of pupils achieving strong 9-5 passes in both English and mathematics GCSEs                                                                           |
|98    |TOTEBACCAPS                    |Total EBacc APS score per pupil                                                                                                                         |
|99    |EBACCAPS                       |Average EBacc APS score per pupil                                                                                                                       |
|100   |EBACCAPS_FSM6CLA1A             |Average EBacc APS score per disadvantaged pupil                                                                                                         |
|101   |EBACCAPS_NFSM6CLA1A            |Average EBacc APS score per non-disadvantaged pupil                                                                                                     |
|102   |EBACCAPS_LO                    |Average EBacc APS score per pupil with low prior attainment                                                                                             |
|103   |EBACCAPS_MID                   |Average EBacc APS score per pupil with middle prior attainment                                                                                          |
|104   |EBACCAPS_HI                    |Average EBacc APS score per pupil with high prior attainment                                                                                            |
|105   |EBACCAPS_EAL                   |Average EBacc APS score per pupil for whom English is an additional language                                                                            |
|106   |EBACCAPS_GIRLS                 |Average EBacc APS score per girl                                                                                                                        |
|107   |EBACCAPS_BOYS                  |Average EBacc APS score per boy                                                                                                                         |
|108   |EBACCAPS_NMOB                  |Average EBacc APS score per non-mobile pupil                                                                                                            |
|109   |EBACCAPS_20                    |Average EBacc APS score per pupil in 2020                                                                                                               |
|110   |EBACCAPS_FSM6CLA1A_20          |Average EBacc APS score per disadvantaged pupil in 2020                                                                                                 |
|111   |EBACCAPS_NFSM6CLA1A_20         |Average EBacc APS score per non-disadvantaged pupil in 2020                                                                                             |
|112   |EBACCAPS_21                    |Average EBacc APS score per pupil in 2021                                                                                                               |
|113   |EBACCAPS_FSM6CLA1A_21          |Average EBacc APS score per disadvantaged pupil in 2021                                                                                                 |
|114   |EBACCAPS_NFSM6CLA1A_21         |Average EBacc APS score per non-disadvantaged pupil in 2021                                                                                             |
|115   |TEBACC_E_PTQ_EE                |Number of key stage 4 pupils with entries in all English Baccalaureate subject areas                                                                    |
|116   |PTEBACC_E_PTQ_EE               |% of key stage 4 pupils with entries in all English Baccalaureate subject areas                                                                         |
|117   |PTEBACC_94                     |% of pupils achieving the English Baccalaureate with 9-4 passes                                                                                         |
|118   |PTEBACC_95                     |% of pupils achieving the English Baccalaureate with 9-5 passes                                                                                         |
|119   |TEBACENG_E_PTQ_EE              |Number of pupils entering the English Baccalaureate English subject area                                                                                |
|120   |PTEBACENG_E_PTQ_EE             |% of pupils entering the English Baccalaureate English subject area                                                                                     |
|121   |TEBACMAT_E_PTQ_EE              |Number of pupils entering the English Baccalaureate Maths subject area                                                                                  |
|122   |PTEBACMAT_E_PTQ_EE             |% of pupils entering the English Baccalaureate Maths subject area                                                                                       |
|123   |TEBAC2SCI_E_PTQ_EE             |Number of pupils entering the English Baccalaureate Science subject area                                                                                |
|124   |PTEBAC2SCI_E_PTQ_EE            |%  of pupils entering the English Baccalaureate Science subject area                                                                                    |
|125   |TEBACHUM_E_PTQ_EE              |Number of pupils entering the English Baccalaureate Humanities subject area                                                                             |
|126   |PTEBACHUM_E_PTQ_EE             |%  of pupils entering the English Baccalaureate Humanities subject area                                                                                 |
|127   |TEBACLAN_E_PTQ_EE              |Number of pupils entering the English Baccalaureate Language subject area                                                                               |
|128   |PTEBACLAN_E_PTQ_EE             |%  of pupils entering the English Baccalaureate Language subject area                                                                                   |
|129   |PTEBACENG_94                   |% of pupils achieving the EBacc English subject area with a standard 9-4 pass                                                                           |
|130   |PTEBACENG_95                   |% of pupils achieving the EBacc English subject area with a strong 9-5 pass                                                                             |
|131   |PTEBACMAT_94                   | % of pupils achieving the EBacc Maths subject area with a standard 9-4 pass                                                                            |
|132   |PTEBACMAT_95                   | % of pupils achieving the EBacc Maths subject area with a strong 9-5 pass                                                                              |
|133   |PTEBAC2SCI_94                  | % of entered pupils achieving the EBacc Science subject area with a 9-4 pass                                                                           |
|134   |PTEBAC2SCI_95                  | % of entered pupils achieving the EBacc Science subject area with a 9-5 pass                                                                           |
|135   |PTEBACHUM_94                   | % of entered pupils achieving the EBacc Humanities subject area with a 9-4 pass                                                                        |
|136   |PTEBACHUM_95                   | % of entered pupils achieving the EBacc Humanities subject area with a 9-5 pass                                                                        |
|137   |PTEBACLAN_94                   | % of entered pupils achieving the EBacc Language subject area with a 9-4 pass                                                                          |
|138   |PTEBACLAN_95                   | % of entered pupils achieving the EBacc Language subject area with a 9-5 pass                                                                          |
|139   |SCIVAPUP_PTQ_EE                |Number of pupils included in English Baccalaureate Science Value Added measure                                                                          |
|140   |SCIVACOV_PTQ_EE                |Coverage of the English Baccalaureate Science Value Added indicators of those who entered for science                                                   |
|141   |HUMVAPUP_PTQ_EE                |Number of pupils included in English Baccalaureate Humanities Value Added measure                                                                       |
|142   |HUMVACOV_PTQ_EE                |Coverage of the English Baccalaureate Humanities Value Added indicators of those who entered for humanities                                             |
|143   |LANVAPUP_PTQ_EE                |Number of pupils included in English Baccalaureate Language Value Added measure                                                                         |
|144   |LANVACOV_PTQ_EE                |Coverage of the English Baccalaureate Language Value Added indicators of those who entered for languages                                                |
|145   |SCIVAMEA_PTQ_EE                |English Baccalaureate Science Value Added measure                                                                                                       |
|146   |SCIVALOW_PTQ_EE                |English Baccalaureate Science Value Added lower 95% confidence limit                                                                                    |
|147   |SCIVAUPP_PTQ_EE                |English Baccalaureate Science Value Added upper 95% confidence limit                                                                                    |
|148   |HUMVAMEA_PTQ_EE                |EBacc Humanities VA measure                                                                                                                             |
|149   |HUMVALOW_PTQ_EE                |English Baccalaureate Humanities Value Added lower 95% confidence limit                                                                                 |
|150   |HUMVAUPP_PTQ_EE                |English Baccalaureate Humanities Value Added upper 95% confidence limit                                                                                 |
|151   |LANVAMEA_PTQ_EE                |English Baccalaureate Languages Value Added measure                                                                                                     |
|152   |LANVALOW_PTQ_EE                |English Baccalaureate Languages Value Added lower 95% confidence limit                                                                                  |
|153   |LANVAUPP_PTQ_EE                |English Baccalaureate Languages Value Added upper 95% confidence limit                                                                                  |
|154   |TEBACENG_94                    |Number of pupils achieving EBacc English subject area with a standard 9-4 pass                                                                          |
|155   |TEBACENG_95                    |Number of pupils achieving EBacc English subject area with a strong 9-5 pass                                                                            |
|156   |TEBACMAT_94                    |Number of pupils achieving EBacc Maths subject area with a standard 9-4 pass                                                                            |
|157   |TEBACMAT_95                    |Number of pupils achieving EBacc Maths subject area with a strong 9-5 pass                                                                              |
|158   |TEBAC2SCI_94                   |Number of pupils achieving EBacc Science subject area with a 9-4 pass                                                                                   |
|159   |TEBAC2SCI_95                   |Number of pupils achieving EBacc Science subject area with a 9-5 pass                                                                                   |
|160   |TEBACHUM_94                    |Number of pupils achieving EBacc Humanities subject area with a 9-4 pass                                                                                |
|161   |TEBACHUM_95                    |Number of pupils achieving EBacc Humanities subject area with a 9-5 pass                                                                                |
|162   |TEBACLAN_94                    |Number of pupils achieving EBacc Language subject area with a 9-4 pass                                                                                  |
|163   |TEBACLAN_95                    |Number of pupils achieving EBacc Language subject area with a 9-5 pass                                                                                  |
|164   |TEBACC91                       |Number of pupils achieving the English Baccalaureate at grades 9-1                                                                                      |
|165   |PTEBACC91                      | % of pupils achieving the English Baccalaureate at grades 9-1                                                                                          |
|166   |TEBACENG91                     |Number of pupils achieving EBacc English subject area at grade 9-1                                                                                      |
|167   |PTEBACENG91                    |% of pupils achieving the EBacc English subject area at grade 9-1                                                                                       |
|168   |TEBACMAT91                     |Number of pupils achieving EBacc Maths subject area at grade 9-1                                                                                        |
|169   |PTEBACMAT91                    | % of pupils achieving the EBacc Maths subject area at grade 9-1                                                                                        |
|170   |TEBAC2SCI91                    |Number of pupils achieving EBacc Science subject area with grades 9-1                                                                                   |
|171   |PTEBAC2SCI91                   | % entered pupils achieving the EBacc Science subject area with grades 9-1                                                                              |
|172   |TEBACHUM91                     |Number of pupils achieving EBacc Humanities subject area with grades 9-1                                                                                |
|173   |PTEBACHUM91                    | % entered pupils achieving the EBacc Humanities subject area with grades 9-1                                                                           |
|174   |TEBACLAN91                     |Number of pupils achieving EBacc Language subject area with grades 9-1                                                                                  |
|175   |PTEBACLAN91                    | % of entered pupils achieving the EBacc Language subject area with grades 9-1                                                                          |
|176   |ATT8SCR_FSM6CLA1A              |Average Attainment 8 score per disadvantaged pupil                                                                                                      |
|177   |P8PUP_FSM6CLA1A                |Number of disadvantaged pupils in Progress 8 measure                                                                                                    |
|178   |TP8ADJ_FSM6CLA1A               |Number of disadvantaged pupils in progress measure with adjusted scores                                                                                 |
|179   |P8MEA_FSM6CLA1A                |Adjusted Progress 8 measure - disadvantaged pupils                                                                                                      |
|180   |P8CILOW_FSM6CLA1A              |Adjusted Progress 8 lower 95% confidence interval - disadvantaged pupils                                                                                |
|181   |P8CIUPP_FSM6CLA1A              |Adjusted Progress 8 upper 95% confidence interval - disadvantaged pupils                                                                                |
|182   |P8MEA_FSM6CLA1A_ORIG           |Unadjusted Progress 8 measure - disadvantaged pupils                                                                                                    |
|183   |P8CILOW_FSM6CLA1A_ORIG         |Unadjusted Progress 8 lower 95% confidence interval - disadvantaged pupils                                                                              |
|184   |P8CIUPP_FSM6CLA1A_ORIG         |Unadjusted Progress 8 upper 95% confidence interval - disadvantaged pupils                                                                              |
|185   |ATT8SCR_NFSM6CLA1A             |Average Attainment 8 score per non-disadvantaged pupil                                                                                                  |
|186   |P8PUP_NFSM6CLA1A               |Number of non-disadvantaged pupils in Progress 8 measure                                                                                                |
|187   |TP8ADJ_NFSM6CLA1A              |Number of non-disadvantaged pupils in progress measure with adjusted scores                                                                             |
|188   |P8MEA_NFSM6CLA1A               |Adjusted Progress 8 measure - non-disadvantaged pupils                                                                                                  |
|189   |P8CILOW_NFSM6CLA1A             |Progress 8 lower 95% confidence interval - non-disadvantaged pupils                                                                                     |
|190   |P8CIUPP_NFSM6CLA1A             |Progress 8 upper 95% confidence interval - non-disadvantaged pupils                                                                                     |
|191   |P8MEA_NFSM6CLA1A_ORIG          |Unadjusted Progress 8 measure - non-disadvantaged pupils                                                                                                |
|192   |P8CILOW_NFSM6CLA1A_ORIG        |Unadjusted Progress 8 lower 95% confidence interval - non-disadvantaged pupils                                                                          |
|193   |P8CIUPP_NFSM6CLA1A_ORIG        |Unadjusted Progress 8 upper 95% confidence interval - non-disadvantaged pupils                                                                          |
|194   |ATT8SCRENG_FSM6CLA1A           |Average Attainment 8 score per disadvantaged pupil for English element                                                                                  |
|195   |P8MEAENG_FSM6CLA1A             |Progress 8 measure for English element - disadvantaged pupils                                                                                           |
|196   |P8MEAENG_CILOW_FSM6CLA1A       |Lower 95% confidence interval for Progress 8 English element for disadvantaged pupils                                                                   |
|197   |P8MEAENG_CIUPP_FSM6CLA1A       |Upper 95% confidence interval for Progress 8 English element for disadvantaged pupils                                                                   |
|198   |ATT8SCRMAT_FSM6CLA1A           |Average Attainment 8 score per disadvantaged pupil for mathematics element                                                                              |
|199   |P8MEAMAT_FSM6CLA1A             |Progress 8 measure for maths element - disadvantaged pupils                                                                                             |
|200   |P8MEAMAT_CILOW_FSM6CLA1A       |Lower 95% confidence interval for Progress 8 maths element for disadvantaged pupils                                                                     |
|201   |P8MEAMAT_CIUPP_FSM6CLA1A       |Upper 95% confidence interval for Progress 8 maths element for disadvantaged pupils                                                                     |
|202   |ATT8SCREBAC_FSM6CLA1A          |Average Attainment 8 score per disadvantaged pupil for EBacc element                                                                                    |
|203   |P8MEAEBAC_FSM6CLA1A            |Progress 8 measure for EBacc element - disadvantaged pupils                                                                                             |
|204   |P8MEAEBAC_CILOW_FSM6CLA1A      |Lower 95% confidence interval for Progress 8 EBacc element for disadvantaged pupils                                                                     |
|205   |P8MEAEBAC_CIUPP_FSM6CLA1A      |Upper 95% confidence interval for Progress 8 EBacc element for disadvantaged pupils                                                                     |
|206   |ATT8SCROPEN_FSM6CLA1A          |Average Attainment 8 score per disadvantaged pupil for open element                                                                                     |
|207   |P8MEAOPEN_FSM6CLA1A            |Progress 8 measure for open element - disadvantaged pupils                                                                                              |
|208   |P8MEAOPEN_CILOW_FSM6CLA1A      |Lower 95% confidence interval for Progress 8 open element for disadvantaged pupils                                                                      |
|209   |P8MEAOPEN_CIUPP_FSM6CLA1A      |Upper 95% confidence interval for Progress 8 open element for disadvantaged pupils                                                                      |
|210   |ATT8SCRENG_NFSM6CLA1A          |Average Attainment 8 score per non-disadvantaged pupil for English element                                                                              |
|211   |P8MEAENG_NFSM6CLA1A            |Progress 8 measure for English element - non-disadvantaged pupils                                                                                       |
|212   |P8MEAENG_CILOW_NFSM6CLA1A      |Lower 95% confidence interval for Progress 8 English element for non-disadvantaged pupils                                                               |
|213   |P8MEAENG_CIUPP_NFSM6CLA1A      |Upper 95% confidence interval for Progress 8 English element for non-disadvantaged pupils                                                               |
|214   |ATT8SCRMAT_NFSM6CLA1A          |Average Attainment 8 score per non-disadvantaged pupil for mathematics element                                                                          |
|215   |P8MEAMAT_NFSM6CLA1A            |Progress 8 measure for maths element - non-disadvantaged pupils                                                                                         |
|216   |P8MEAMAT_CILOW_NFSM6CLA1A      |Lower 95% confidence interval for Progress 8 maths element for non-disadvantaged pupils                                                                 |
|217   |P8MEAMAT_CIUPP_NFSM6CLA1A      |Upper 95% confidence interval for Progress 8 maths element for non-disadvantaged pupils                                                                 |
|218   |ATT8SCREBAC_NFSM6CLA1A         |Average Attainment 8 score per non-disadvantaged pupil for EBacc element                                                                                |
|219   |P8MEAEBAC_NFSM6CLA1A           |Progress 8 measure for EBacc element - non-disadvantaged pupils                                                                                         |
|220   |P8MEAEBAC_CILOW_NFSM6CLA1A     |Lower 95% confidence interval for Progress 8 EBacc element for non-disadvantaged pupils                                                                 |
|221   |P8MEAEBAC_CIUPP_NFSM6CLA1A     |Upper 95% confidence interval for Progress 8 EBacc element for non-disadvantaged pupils                                                                 |
|222   |ATT8SCROPEN_NFSM6CLA1A         |Average Attainment 8 score per non-disadvantaged pupil for open element                                                                                 |
|223   |P8MEAOPEN_NFSM6CLA1A           |Progress 8 measure for open element - non-disadvantaged pupils                                                                                          |
|224   |P8MEAOPEN_CILOW_NFSM6CLA1A     |Lower 95% confidence interval for Progress 8 open element for non-disadvantaged pupils                                                                  |
|225   |P8MEAOPEN_CIUPP_NFSM6CLA1A     |Upper 95% confidence interval for Progress 8 open element for non-disadvantaged pupils                                                                  |
|226   |ATT8SCROPENG_FSM6CLA1A         |Average Attainment 8 score per disadvantaged pupil for open element - GCSE only                                                                         |
|227   |ATT8SCROPENNG_FSM6CLA1A        |Average Attainment 8 score per disadvantaged pupil for open element - non-GCSE only                                                                     |
|228   |ATT8SCROPENG_NFSM6CLA1A        |Average Attainment 8 score per non-disadvantaged pupil for open element - GCSE only                                                                     |
|229   |ATT8SCROPENNG_NFSM6CLA1A       |Average Attainment 8 score per non-disadvantaged pupil for open element - non-GCSE only                                                                 |
|230   |DIFFN_ATT8                     |Difference between Attainment 8 for disadvantaged pupils in school/LA and non-disadvantaged pupils nationally                                           |
|231   |DIFFN_P8MEA                    |Difference between Progress 8 measure for disadvantaged pupils in school/LA and non-disadvantaged pupils nationally                                     |
|232   |ATT8SCR_LO                     |Average Attainment 8 score per pupil with low prior attainment                                                                                          |
|233   |P8PUP_LO                       |Number of pupils with low prior attainment included in Progress 8 measure                                                                               |
|234   |TP8ADJ_LO                      |Number of pupils with low prior attainments in progress measure with adjusted scores                                                                    |
|235   |P8MEA_LO                       |Adjusted Progress 8 measure - pupils with low prior attainments                                                                                         |
|236   |P8CILOW_LO                     |Adjusted Progress 8 lower 95% confidence interval - pupils with low prior attainments                                                                   |
|237   |P8CIUPP_LO                     |Adjusted Progress 8 upper 95% confidence interval - pupils with low prior attainments                                                                   |
|238   |P8MEA_LO_ORIG                  |Unadjusted Progress 8 measure - pupils with low prior attainments                                                                                       |
|239   |P8CILOW_LO_ORIG                |Unadjusted Progress 8 lower 95% confidence interval - pupils with low prior attainments                                                                 |
|240   |P8CIUPP_LO_ORIG                |Unadjusted Progress 8 upper 95% confidence interval - pupils with low prior attainments                                                                 |
|241   |ATT8SCR_MID                    |Average Attainment 8 score per pupil with middle prior attainment                                                                                       |
|242   |P8PUP_MID                      |Number of pupils with middle prior attainment included in Progress 8 measure                                                                            |
|243   |TP8ADJ_MID                     |Number of pupils with middle prior attainments in progress measure with adjusted scores                                                                 |
|244   |P8MEA_MID                      |Adjusted Progress 8 measure - pupils with middle prior attainment                                                                                       |
|245   |P8CILOW_MID                    |Progress 8 lower 95% confidence interval - pupils with middle prior attainment                                                                          |
|246   |P8CIUPP_MID                    |Progress 8 upper 95% confidence interval - pupils with middle prior attainment                                                                          |
|247   |P8MEA_MID_ORIG                 |Unadjusted Progress 8 measure - pupils with middle prior attainments                                                                                    |
|248   |P8CILOW_MID_ORIG               |Unadjusted Progress 8 lower 95% confidence interval - pupils with middle prior attainments                                                              |
|249   |P8CIUPP_MID_ORIG               |Unadjusted Progress 8 upper 95% confidence interval - pupils with middle prior attainments                                                              |
|250   |ATT8SCR_HI                     |Average Attainment 8 score per pupil with high prior attainment                                                                                         |
|251   |P8PUP_HI                       |Number of pupils with high prior attainment included in Progress 8 measure                                                                              |
|252   |TP8ADJ_HI                      |Number of pupils with high prior attainments in progress measure with adjusted scores                                                                   |
|253   |P8MEA_HI                       |Adjusted Progress 8 measure - pupils with high prior attainment                                                                                         |
|254   |P8CILOW_HI                     |Progress 8 lower 95% confidence interval - pupils with high prior attainment                                                                            |
|255   |P8CIUPP_HI                     |Progress 8 upper 95% confidence interval - pupils with high prior attainment                                                                            |
|256   |P8MEA_HI_ORIG                  |Unadjusted Progress 8 measure - pupils with high prior attainments                                                                                      |
|257   |P8CILOW_HI_ORIG                |Unadjusted Progress 8 lower 95% confidence interval - pupils with high prior attainments                                                                |
|258   |P8CIUPP_HI_ORIG                |Unadjusted Progress 8 upper 95% confidence interval - pupils with high prior attainments                                                                |
|259   |ATT8SCR_EAL                    |Average Attainment 8 score per pupil for whom English is an additional language                                                                         |
|260   |ATT8SCRENG_EAL                 |Average Attainment 8 score per pupil for whom English is an additional language for English element                                                     |
|261   |ATT8SCRMAT_EAL                 |Average Attainment 8 score per pupil for whom English is an additional language for mathematics element                                                 |
|262   |ATT8SCREBAC_EAL                |Average Attainment 8 score per pupil for whom English is an additional language for EBacc element                                                       |
|263   |ATT8SCROPEN_EAL                |Average Attainment 8 score per pupil for whom English is an additional language for open element                                                        |
|264   |ATT8SCROPENG_EAL               |Average Attainment 8 score per pupil for whom English is an additional language - GCSE only                                                             |
|265   |ATT8SCROPENNG_EAL              |Average Attainment 8 score per pupil for whom English is an additional language - non-GCSE only                                                         |
|266   |P8PUP_EAL                      |Number of pupils for whom English is an additional language included in Progress 8 measure                                                              |
|267   |TP8ADJ_EAL                     |Number of pupils for whom English is an additional language in progress measure with adjusted scores                                                    |
|268   |P8MEA_EAL                      |Adjusted Progress 8 measure - pupils for whom English is an additional language                                                                         |
|269   |P8CILOW_EAL                    |Adjusted Progress 8 lower 95% confidence interval - pupils for whom English is an additional language                                                   |
|270   |P8CIUPP_EAL                    |Adjusted Progress 8 upper 95% confidence interval - pupils for whom English is an additional language                                                   |
|271   |P8MEA_EAL_ORIG                 |Unadjusted Progress 8 measure - pupils for whom English is an additional language                                                                       |
|272   |P8CILOW_EAL_ORIG               |Unadjusted Progress 8 lower 95% confidence interval - pupils for whom English is an additional language                                                 |
|273   |P8CIUPP_EAL_ORIG               |Unadjusted Progress 8 upper 95% confidence interval - pupils for whom English is an additional language                                                 |
|274   |ATT8SCR_GIRLS                  |Average Attainment 8 score per girl                                                                                                                     |
|275   |ATT8SCRENG_GIRLS               |Average Attainment 8 score per girl for English element                                                                                                 |
|276   |ATT8SCRMAT_GIRLS               |Average Attainment 8 score per girl for mathematics element                                                                                             |
|277   |ATT8SCREBAC_GIRLS              |Average Attainment 8 score per girl for EBacc element                                                                                                   |
|278   |ATT8SCROPEN_GIRLS              |Average Attainment 8 score per girl for open element                                                                                                    |
|279   |ATT8SCROPENG_GIRLS             |Average Attainment 8 score per girl - GCSE only                                                                                                         |
|280   |ATT8SCROPENNG_GIRLS            |Average Attainment 8 score per girl - non-GCSE only                                                                                                     |
|281   |P8PUP_GIRLS                    |Number of girls included in Progress 8 measure                                                                                                          |
|282   |TP8ADJ_GIRLS                   |Number of girls in progress measure with adjusted scores                                                                                                |
|283   |P8MEA_GIRLS                    |Adjusted Progress 8 measure - girls                                                                                                                     |
|284   |P8CILOW_GIRLS                  |Adjusted Progress 8 lower 95% confidence interval - girls                                                                                               |
|285   |P8CIUPP_GIRLS                  |Adjusted Progress 8 upper 95% confidence interval - girls                                                                                               |
|286   |P8MEA_GIRLS_ORIG               |Unadjusted Progress 8 measure - girls                                                                                                                   |
|287   |P8CILOW_GIRLS_ORIG             |Unadjusted Progress 8 lower 95% confidence interval - girls                                                                                             |
|288   |P8CIUPP_GIRLS_ORIG             |Unadjusted Progress 8 upper 95% confidence interval - girls                                                                                             |
|289   |ATT8SCR_BOYS                   |Average Attainment 8 score per boy                                                                                                                      |
|290   |ATT8SCRENG_BOYS                |Average Attainment 8 score per boy for English element                                                                                                  |
|291   |ATT8SCRMAT_BOYS                |Average Attainment 8 score per boy for mathematics element                                                                                              |
|292   |ATT8SCREBAC_BOYS               |Average Attainment 8 score per boy for EBacc element                                                                                                    |
|293   |ATT8SCROPEN_BOYS               |Average Attainment 8 score per boy for open element                                                                                                     |
|294   |ATT8SCROPENG_BOYS              |Average Attainment 8 score per boy - GCSE only                                                                                                          |
|295   |ATT8SCROPENNG_BOYS             |Average Attainment 8 score per boy - non-GCSE only                                                                                                      |
|296   |P8PUP_BOYS                     |Number of boys included in Progress 8 measure                                                                                                           |
|297   |TP8ADJ_BOYS                    |Number of boys in progress measure with adjusted scores                                                                                                 |
|298   |P8MEA_BOYS                     |Adjusted Progress 8 measure - boys                                                                                                                      |
|299   |P8CILOW_BOYS                   |Adjusted Progress 8 lower 95% confidence interval - boys                                                                                                |
|300   |P8CIUPP_BOYS                   |Adjusted Progress 8 upper 95% confidence interval - boys                                                                                                |
|301   |P8MEA_BOYS_ORIG                |Unadjusted Progress 8 measure - boys                                                                                                                    |
|302   |P8CILOW_BOYS_ORIG              |Unadjusted Progress 8 lower 95% confidence interval - boys                                                                                              |
|303   |P8CIUPP_BOYS_ORIG              |Unadjusted Progress 8 upper 95% confidence interval - boys                                                                                              |
|304   |ATT8SCR_NMOB                   |Average Attainment 8 score per non-mobile pupil                                                                                                         |
|305   |ATT8SCRENG_NMOB                |Average Attainment 8 score per non-mobile pupil for English element                                                                                     |
|306   |ATT8SCRMAT_NMOB                |Average Attainment 8 score per non-mobile pupil for mathematics element                                                                                 |
|307   |ATT8SCREBAC_NMOB               |Average Attainment 8 score per non-mobile pupil for EBacc element                                                                                       |
|308   |ATT8SCROPEN_NMOB               |Average Attainment 8 score per non-mobile pupil for open element                                                                                        |
|309   |ATT8SCROPENG_NMOB              |Average Attainment 8 score per non-mobile pupil - GCSE only                                                                                             |
|310   |ATT8SCROPENNG_NMOB             |Average Attainment 8 score per non-mobile pupil - non-GCSE only                                                                                         |
|311   |P8PUP_NMOB                     |Number of non-mobile pupils included in Progress 8 measure                                                                                              |
|312   |TP8ADJ_NMOB                    |Number of non-mobile pupils in progress measure with adjusted scores                                                                                    |
|313   |P8MEA_NMOB                     |Adjusted Progress 8 measure - non-mobile pupils                                                                                                         |
|314   |P8CILOW_NMOB                   |Adjusted Progress 8 lower 95% confidence interval - non-mobile pupils                                                                                   |
|315   |P8CIUPP_NMOB                   |Adjusted Progress 8 upper 95% confidence interval - non-mobile pupils                                                                                   |
|316   |P8MEA_NMOB_ORIG                |Unadjusted Progress 8 measure - non-mobile pupils                                                                                                       |
|317   |P8CILOW_NMOB_ORIG              |Unadjusted Progress 8 lower 95% confidence interval - non-mobile pupils                                                                                 |
|318   |P8CIUPP_NMOB_ORIG              |Unadjusted Progress 8 upper 95% confidence interval - non-mobile pupils                                                                                 |
|319   |ATT8SCR_20                     |Average Attainment 8 score per pupil  - 2020                                                                                                            |
|320   |P8PUP_20                       |Number of pupils in progress measure  - 2020                                                                                                            |
|321   |P8MEA_20                       |Progress 8 measure  - 2020                                                                                                                              |
|322   |P8CILOW_20                     |Progress 8 lower 95% confidence interval  - 2020                                                                                                        |
|323   |P8CIUPP_20                     |Progress 8 upper 95% confidence interval - 2020                                                                                                         |
|324   |ATT8SCR_FSM6CLA1A_20           |Average Attainment 8 score per disadvantaged pupil - 2020                                                                                               |
|325   |P8PUP_FSM6CLA1A_20             |Number of disadvantaged pupils in progress measure - 2020                                                                                               |
|326   |P8MEA_FSM6CLA1A_20             |Progress 8 measure - disadvantaged pupils - 2020                                                                                                        |
|327   |P8CILOW_FSM6CLA1A_20           |Progress 8 lower 95% confidence interval - disadvantaged pupils - 2020                                                                                  |
|328   |P8CIUPP_FSM6CLA1A_20           |Progress 8 upper 95% confidence interval - disadvantaged pupils - 2020                                                                                  |
|329   |ATT8SCR_NFSM6CLA1A_20          |Average Attainment 8 score per non-disadvantaged pupil - 2020                                                                                           |
|330   |P8PUP_NFSM6CLA1A_20            |Number of non-disadvantaged pupils in progress measure - 2020                                                                                           |
|331   |P8MEA_NFSM6CLA1A_20            |Progress 8 measure - non-disadvantaged pupils - 2020                                                                                                    |
|332   |P8CILOW_NFSM6CLA1A_20          |Progress 8 lower 95% confidence interval - non-disadvantaged pupils - 2020                                                                              |
|333   |P8CIUPP_NFSM6CLA1A_20          |Progress 8 upper 95% confidence interval - non-disadvantaged pupils - 2020                                                                              |
|334   |ATT8SCR_21                     |Average Attainment 8 score per pupil - 2021                                                                                                             |
|335   |P8PUP_21                       |Number of pupils in progress measure - 2021                                                                                                             |
|336   |P8MEA_21                       |Progress 8 measure - 2021                                                                                                                               |
|337   |P8CILOW_21                     |Progress 8 lower 95% confidence interval - 2021                                                                                                         |
|338   |P8CIUPP_21                     |Progress 8 upper 95% confidence interva - 2021                                                                                                          |
|339   |ATT8SCR_FSM6CLA1A_21           |Average Attainment 8 score per disadvantaged pupil - 2021                                                                                               |
|340   |P8PUP_FSM6CLA1A_21             |Number of disadvantaged pupils in progress measure - 2021                                                                                               |
|341   |P8MEA_FSM6CLA1A_21             |Progress 8 measure - disadvantaged pupils - 2021                                                                                                        |
|342   |P8CILOW_FSM6CLA1A_21           |Progress 8 lower 95% confidence interval - disadvantaged pupils - 2021                                                                                  |
|343   |P8CIUPP_FSM6CLA1A_21           |Progress 8 upper 95% confidence interval - disadvantaged pupils - 2021                                                                                  |
|344   |ATT8SCR_NFSM6CLA1A_21          |Average Attainment 8 score per non-disadvantaged pupil  - 2021                                                                                          |
|345   |P8PUP_NFSM6CLA1A_21            |Number of non-disadvantaged pupils in progress measure - 2021                                                                                           |
|346   |P8MEA_NFSM6CLA1A_21            |Progress 8 measure - non-disadvantaged pupils - 2021                                                                                                    |
|347   |P8CILOW_NFSM6CLA1A_21          |Progress 8 lower 95% confidence interval - non-disadvantaged pupils - 2021                                                                              |
|348   |P8CIUPP_NFSM6CLA1A_21          |Progress 8 upper 95% confidence interval - non-disadvantaged pupils - 2021                                                                              |
|349   |TEBACC_ELO_PTQ_EE              |Number of pupils in low prior attainment band with entries in all EBacc subject areas                                                                   |
|350   |PTEBACC_ELO_PTQ_EE             |EBacc entered % by low prior attainment                                                                                                                 |
|351   |PTEBACCLO_94                   |EBacc achieved % by low prior attainment - with standard 9-4 passes in English and maths                                                                |
|352   |PTEBACCLO_95                   |EBacc achieved % by low prior attainment - with 9-5 passes                                                                                              |
|353   |TEBACC_EAV_PTQ_EE              |Number of pupils in middle prior attainment band with entries in all EBacc subject areas                                                                |
|354   |PTEBACC_EAV_PTQ_EE             |EBacc entered % by middle prior attainment                                                                                                              |
|355   |PTEBACCAV_94                   |EBacc achieved % by middle prior attainment - with 9-4 passes                                                                                           |
|356   |PTEBACCAV_95                   |EBacc achieved % by middle prior attainment - with 9-5 passes                                                                                           |
|357   |TEBACC_EHI_PTQ_EE              |Number of pupils in high prior attainment band with entries in all EBacc subject areas                                                                  |
|358   |PTEBACC_EHI_PTQ_EE             |EBacc entered % by high prior attainment                                                                                                                |
|359   |PTEBACCHI_94                   |EBacc achieved % by high prior attainment - with 9-4 passes                                                                                             |
|360   |PTEBACCHI_95                   |EBacc achieved % by high prior attainment - with 9-5 passes                                                                                             |
|361   |PTEBACC_EFSM6CLA1A_PTQ_EE      |% of disadvantaged pupils entering all English Baccalaureate subject areas                                                                              |
|362   |PTEBACC_ENFSM6CLA1A_PTQ_EE     | % of non-disadvantaged pupils entering all English Baccalaureate subject areas                                                                         |
|363   |PTEBACC_94_FSM6CLA1A           | % of disadvantaged pupils achieving the English Baccalaureate - with 9-4 passes                                                                        |
|364   |PTEBACC_95_FSM6CLA1A           | % of disadvantaged pupils achieving the English Baccalaureate - with 9-5 passes                                                                        |
|365   |PTEBACC_94_NFSM6CLA1A          | % of non-disadvantaged pupils achieving the English Baccalaureate - with 9-4 passes                                                                    |
|366   |PTEBACC_95_NFSM6CLA1A          | % of non-disadvantaged pupils achieving the English Baccalaureate - with 9-5 passes                                                                    |
|367   |SCIVAMEA_LO_PTQ_EE             |English Baccalaureate Science Value Added measure for pupils with low prior attainment                                                                  |
|368   |SCIVAMEA_MID_PTQ_EE            |English Baccalaureate Science Value Added measure for pupils with middle prior attainment                                                               |
|369   |SCIVAMEA_HI_PTQ_EE             |English Baccalaureate Science Value Added measure for pupils with high prior attainment                                                                 |
|370   |SCIVAMEA_FSM6CLA1A_PTQ_EE      |English Baccalaureate Science Value Added measure for disadvantaged pupils                                                                              |
|371   |SCIVAMEA_NFSM6CLA1A_PTQ_EE     |English Baccalaureate Science Value Added measure for non-disadvantaged pupils                                                                          |
|372   |HUMVAMEA_LO_PTQ_EE             |English Baccalaureate Humanities Value Added measure for pupils with low prior attainment                                                               |
|373   |HUMVAMEA_MID_PTQ_EE            |English Baccalaureate Humanities Value Added measure for pupils with middle prior attainment                                                            |
|374   |HUMVAMEA_HI_PTQ_EE             |English Baccalaureate Humanities Value Added measure for pupils with high prior attainment                                                              |
|375   |HUMVAMEA_FSM6CLA1A_PTQ_EE      |English Baccalaureate Humanities Value Added measure for disadvantaged pupils                                                                           |
|376   |HUMVAMEA_NFSM6CLA1A_PTQ_EE     |English Baccalaureate Humanities Value Added measure for non-disadvantaged pupils                                                                       |
|377   |LANVAMEA_LO_PTQ_EE             |English Baccalaureate Languages Value Added measure for pupils with low prior attainment                                                                |
|378   |LANVAMEA_MID_PTQ_EE            |English Baccalaureate Languages Value Added measure for pupils with middle prior attainment                                                             |
|379   |LANVAMEA_HI_PTQ_EE             |English Baccalaureate Languages Value Added measure for pupils with high prior attainment                                                               |
|380   |LANVAMEA_FSM6CLA1A_PTQ_EE      |English Baccalaureate Languages Value Added measure for disadvantaged pupils                                                                            |
|381   |LANVAMEA_NFSM6CLA1A_PTQ_EE     |English Baccalaureate Languages Value Added measure for non-disadvantaged pupils                                                                        |
|382   |SCIVAUPP_FSM6CLA1A_PTQ_EE      |Upper 95% confidence limit for English Baccalaureate Science Value Added measure for disadvantaged pupils                                               |
|383   |SCIVALOW_FSM6CLA1A_PTQ_EE      |Lower 95% confidence limit for English Baccalaureate Science Value Added measure for disadvantaged pupils                                               |
|384   |SCIVAUPP_NFSM6CLA1A_PTQ_EE     |Upper 95% confidence limit for English Baccalaureate Science Value Added measure for non-disadvantaged pupils                                           |
|385   |SCIVALOW_NFSM6CLA1A_PTQ_EE     |Lower 95% confidence limit for English Baccalaureate Science Value Added measure for non-disadvantaged pupils                                           |
|386   |SCIVAUPP_LO_PTQ_EE             |Upper 95% confidence limit for English Baccalaureate Science Value Added measure for pupils with low prior attainment                                   |
|387   |SCIVALOW_LO_PTQ_EE             |Lower 95% confidence limit for English Baccalaureate Science Value Added measure for pupils with low prior attainment                                   |
|388   |SCIVAUPP_MID_PTQ_EE            |Upper 95% confidence limit for English Baccalaureate Science Value Added measure for pupils with middle prior attainment                                |
|389   |SCIVALOW_MID_PTQ_EE            |Lower 95% confidence limit for English Baccalaureate Science Value Added measure for pupils with middle prior attainment                                |
|390   |SCIVAUPP_HI_PTQ_EE             |Upper 95% confidence limit for English Baccalaureate Science Value Added measure for pupils with high prior attainment                                  |
|391   |SCIVALOW_HI_PTQ_EE             |Lower 95% confidence limit for English Baccalaureate Science Value Added measure for pupils with high prior attainment                                  |
|392   |HUMVAUPP_FSM6CLA1A_PTQ_EE      |Upper 95% confidence limit for English Baccalaureate Humanities Value Added measure for disadvantaged pupils                                            |
|393   |HUMVALOW_FSM6CLA1A_PTQ_EE      |Lower 95% confidence limit for English Baccalaureate Humanities Value Added measure for disadvantaged pupils                                            |
|394   |HUMVAUPP_NFSM6CLA1A_PTQ_EE     |Upper 95% confidence limit for English Baccalaureate Humanities Value Added measure for non-disadvantaged pupils                                        |
|395   |HUMVALOW_NFSM6CLA1A_PTQ_EE     |Lower 95% confidence limit for English Baccalaureate Humanities Value Added measure for non-disadvantaged pupils                                        |
|396   |HUMVAUPP_LO_PTQ_EE             |Upper 95% confidence limit for English Baccalaureate Humanities Value Added measure for pupils with low prior attainment                                |
|397   |HUMVALOW_LO_PTQ_EE             |Lower 95% confidence limit for English Baccalaureate Humanities Value Added measure for pupils with low prior attainment                                |
|398   |HUMVAUPP_MID_PTQ_EE            |Upper 95% confidence limit for English Baccalaureate Humanities Value Added measure for pupils with middle prior attainment                             |
|399   |HUMVALOW_MID_PTQ_EE            |Lower 95% confidence limit for English Baccalaureate Humanities Value Added measure for pupils with middle prior attainment                             |
|400   |HUMVAUPP_HI_PTQ_EE             |Upper 95% confidence limit for English Baccalaureate Humanities Value Added measure for pupils with high prior attainment                               |
|401   |HUMVALOW_HI_PTQ_EE             |Lower 95% confidence limit for English Baccalaureate Humanities Value Added measure for pupils with high prior attainment                               |
|402   |LANVAUPP_FSM6CLA1A_PTQ_EE      |Upper 95% confidence limit for English Baccalaureate Languages Value Added measure for disadvantaged pupils                                             |
|403   |LANVALOW_FSM6CLA1A_PTQ_EE      |Lower 95% confidence limit for English Baccalaureate Languages Value Added measure for disadvantaged pupils                                             |
|404   |LANVAUPP_NFSM6CLA1A_PTQ_EE     |Upper 95% confidence limit for English Baccalaureate Languages Value Added measure for non-disadvantaged pupils                                         |
|405   |LANVALOW_NFSM6CLA1A_PTQ_EE     |Lower 95% confidence limit for English Baccalaureate Languages Value Added measure for non-disadvantaged pupils                                         |
|406   |LANVAUPP_LO_PTQ_EE             |Upper 95% confidence limit for English Baccalaureate Languages Value Added measure for pupils with low prior attainment                                 |
|407   |LANVALOW_LO_PTQ_EE             |Lower 95% confidence limit for English Baccalaureate Languages Value Added measure for pupils with low prior attainment                                 |
|408   |LANVAUPP_MID_PTQ_EE            |Upper 95% confidence limit for English Baccalaureate Languages Value Added measure for pupils with middle prior attainment                              |
|409   |LANVALOW_MID_PTQ_EE            |Lower 95% confidence limit for English Baccalaureate Languages Value Added measure for pupils with middle prior attainment                              |
|410   |LANVAUPP_HI_PTQ_EE             |Upper 95% confidence limit for English Baccalaureate Languages Value Added measure for pupils with high prior attainment                                |
|411   |LANVALOW_HI_PTQ_EE             |Lower 95% confidence limit for English Baccalaureate Languages Value Added measure for pupils with high prior attainment                                |
|412   |PTEBACC_E_20_PTQ_EE            |% of pupils entering all English Baccalaureate subject areas in 2020                                                                                    |
|413   |PTEBACC_94_20                  |% of KS4 pupils achieving the Ebacc - with standard 9-4 passes in English and maths in 2020                                                             |
|414   |PTEBACC_95_20                  |% of KS4 pupils achieving the Ebacc - with strong 9-5 passes in English and maths in 2020                                                               |
|415   |PTEBACC_E_21_PTQ_EE            |% of  pupils entering all English Baccalaureate subject areas in 2021                                                                                   |
|416   |PTEBACC_94_21                  |% of KS4 pupils achieving the Ebacc - with standard 9-4 passes in English and maths in 2021                                                             |
|417   |PTEBACC_95_21                  |% of KS4 pupils achieving the Ebacc - with strong 9-5 passes in English and maths in 2021                                                               |
|418   |PBEBACC_E_PTQ_EE               |% of boys with entries in all English Baccalaureate subject areas                                                                                       |
|419   |PBEBACC_94                     |% of KS4 boys achieving the Ebacc - with 9-4 passes                                                                                                     |
|420   |PBEBACC_95                     |% of KS4 boys achieving the Ebacc - with 9-5 passes                                                                                                     |
|421   |PGEBACC_E_PTQ_EE               |% of girls with entries in all English Baccalaureate subject areas                                                                                      |
|422   |PGEBACC_94                     |% of KS4 girls achieving the Ebacc - with 9-4 passes                                                                                                    |
|423   |PGEBACC_95                     |% of KS4 girls achieving the Ebacc - with 9-5 passes                                                                                                    |
|424   |PTEBACC_ENMOB_PTQ_EE           |% of non-mobile pupils with entries in all English Baccalaureate subject areas                                                                          |
|425   |PTEBACCNMOB_94                 |% of non-mobile pupils achieving the English Baccalaureate with 9-4 passes                                                                              |
|426   |PTEBACCNMOB_95                 |% of non-mobile pupils achieving the English Baccalaureate with 9-5 passes                                                                              |
|427   |PTEBACC_EEAL_PTQ_EE            |% of pupils for whom English is an additional language with entries in all English Baccalaureate subject areas                                          |
|428   |PTEBACCEAL_94                  |% of pupils for whom English as an additional language achieving the English Baccalaureate with 9-4 passes                                              |
|429   |PTEBACCEAL_95                  |% of pupils for whom English as an additional language achieving the English Baccalaureate with 9-5 passes                                              |
|430   |PTEBACC_EFSM6CLA1A_20          |% of disadvantaged pupils entering all English Baccalaureate subject areas in 2020                                                                      |
|431   |PTEBACC_94_FSM6CLA1A_20        |% of disadvantaged pupils achieving the English Baccalaureate at grades 9-4 in 2020                                                                     |
|432   |PTEBACC_95_FSM6CLA1A_20        |% of disadvantaged pupils achieving the English Baccalaureate at grades 9-5 in 2020                                                                     |
|433   |PTEBACC_ENFSM6CLA1A_20         |% of non-disadvantaged pupils entering all English Baccalaureate subject areas in 2020                                                                  |
|434   |PTEBACC_94_NFSM6CLA1A_20       |% of non-disadvantaged pupils achieving the English Baccalaureate at grade 9-4 in 2020                                                                  |
|435   |PTEBACC_95_NFSM6CLA1A_20       |% of non-disadvantaged pupils achieving the English Baccalaureate at grade 9-5 in 2020                                                                  |
|436   |PTEBACC_EFSM6CLA1A_21          |% of disadvantaged pupils entering all English Baccalaureate subject areas in 2021                                                                      |
|437   |PTEBACC_94_FSM6CLA1A_21        |% of disadvantaged pupils achieving the English Baccalaureate including 9-4 passes in English and maths in 2021                                         |
|438   |PTEBACC_95_FSM6CLA1A_21        |% of disadvantaged pupils achieving the English Baccalaureate including 9-5 passes in English and maths in 2021                                         |
|439   |PTEBACC_ENFSM6CLA1A_21         |% of non-disadvantaged pupils entering all English Baccalaureate subject areas in 2021                                                                  |
|440   |PTEBACC_94_NFSM6CLA1A_21       |% of non-disadvantaged pupils achieving the English Baccalaureate including 9-4 passes in English and maths in 2021                                     |
|441   |PTEBACC_95_NFSM6CLA1A_21       |% of non-disadvantaged pupils achieving the English Baccalaureate including 9-5 passes in English and maths in 2021                                     |
|442   |PT5EM_94                       |% of pupils achieving Level 2 threshold including standard passes 9-4 in both English and Maths GCSEs                                                   |
|443   |PT5EM_94_20                    |% of pupils achieving Level 2 threshold including standard passes 9-4 in both English and Maths GCSEs in 2020                                           |
|444   |PT5EM_94_21                    |% of pupils achieving Level 2 threshold including standard passes 9-4 in both English and Maths GCSEs in 2021                                           |
|445   |PTANYQ_PTQ_EE                  |% of pupils achieving any qualifications                                                                                                                |
|446   |PTL2BASICS_94_20               |% of pupils achieving 9-4 passes in GCSE English and maths in 2020                                                                                      |
|447   |PTL2BASICS_95_20               |% of pupils achieving 9-5 passes in GCSE English and maths in 2020                                                                                      |
|448   |PTL2BASICS_94_21               |% of pupils achieving 9-4 passes in GCSE English and maths in 2021                                                                                      |
|449   |PTL2BASICS_95_21               |% of pupils achieving 9-5 passes in GCSE English and maths in 2021                                                                                      |
|450   |PTFSM6CLA1ABASICS_94           |% of disadvantaged pupils achieving standard 9-4 passes in GCSE English and maths                                                                       |
|451   |PTNOTFSM6CLA1ABASICS_94        |% of non-disadvantaged pupils achieving standard 9-4 passes in GCSE English and maths                                                                   |
|452   |TBASICSLO_94                   |Number of pupils in low prior attainment band who achieved standard 9-4 passes in English and maths                                                     |
|453   |PTBASICSLO_94                  |% of pupils in low prior attainment band who achieved standard 9-4 passes in English and maths                                                          |
|454   |TBASICSAV_94                   |Number of pupils in middle prior attainment band who achieved standard 9-4 passes in English and maths                                                  |
|455   |PTBASICSAV_94                  |% pupils in middle prior attainment band who achieved standard 9-4 passes in English and maths                                                          |
|456   |TBASICSHI_94                   |Number of pupils in high prior attainment band who achieved standard 9-4 passes in English and maths                                                    |
|457   |PTBASICSHI_94                  |% pupils in high prior attainment band who achieved standard 9-4 passes in English and maths                                                            |
|458   |PBL2BASICS_94                  |% of boys achieving standard 9-4 passes in both English and mathematics GCSEs                                                                           |
|459   |PGL2BASICS_94                  |% of girls achieving standard 9-4 passes in both English and mathematics GCSEs                                                                          |
|460   |PTL2BASICSEAL_94               |% of pupils achieving standard 9-4 passes in both English and mathematics GCSEs and for whom English is an additional language                          |
|461   |PTL2BASICSNMOB_94              |% of non-mobile pupils achieving standard 9-4 passes in both English and mathematics GCSEs                                                              |
|462   |PTFSM6CLA1ABASICS_95           |% of disadvantaged pupils achieving strong 9-5 passes in GCSE English and maths                                                                         |
|463   |PTNOTFSM6CLA1ABASICS_95        |% of non-disadvantaged pupils achieving strong 9-5 passes in GCSE English and maths                                                                     |
|464   |TBASICSLO_95                   |Number of pupils in low prior attainment band who achieved strong 9-5 passes in English and maths                                                       |
|465   |PTBASICSLO_95                  |% of pupils in low prior attainment band who achieved strong 9-5 passes in English and maths                                                            |
|466   |TBASICSAV_95                   |Number of pupils in middle prior attainment band who achieved strong 9-5 passes in English and maths                                                    |
|467   |PTBASICSAV_95                  |% pupils in middle prior attainment band who achieved strong 9-5 passes in English and maths                                                            |
|468   |TBASICSHI_95                   |Number of pupils in high prior attainment band who achieved strong 9-5 passes in English and maths                                                      |
|469   |PTBASICSHI_95                  |% pupils in high prior attainment band who achieved strong 9-5 passes in English and maths                                                              |
|470   |PBL2BASICS_95                  |% of boys achieving strong 9-5 passes in both English and mathematics GCSEs                                                                             |
|471   |PGL2BASICS_95                  |% of girls achieving strong 9-5 passes in both English and mathematics GCSEs                                                                            |
|472   |PTL2BASICSEAL_95               |% of pupils achieving strong 9-5 passes in both English and mathematics GCSEs and for whom English is an additional language                            |
|473   |PTL2BASICSNMOB_95              |% of non-mobile pupils achieving strong 9-5 passes in both English and mathematics GCSEs                                                                |
|474   |PTFSM6CLA1ABASICS_94_20        |% of disadvantaged pupils achieving 9-4 in GCSE English and maths in 2020                                                                               |
|475   |PTFSM6CLA1ABASICS_95_20        |% of disadvantaged pupils achieving 9-4 passes in GCSE English and maths in 2020                                                                        |
|476   |PTNOTFSMBASICS_94_20           |% of non-disadvantaged pupils achieving 9-4 passes in GCSE English and maths in 2020                                                                    |
|477   |PTNOTFSM6CLA1ABASICS_95_20     |% of non-disadvantaged pupils achieving 9-5 passes in GCSE English and maths in 2020                                                                    |
|478   |PTFSM6CLA1ABASICS_94_21        |% of disadvantaged pupils achieving 9-4 passes in GCSE English and maths in 2021                                                                        |
|479   |PTFSM6CLA1ABASICS_95_21        |% of disadvantaged pupils achieving 9-5 passes in GCSE English and maths in 2021                                                                        |
|480   |PTNOTFSM6CLA1ABASICS_94_21     |% of non-disadvantaged pupils achieving 9-4 passes in GCSE English and maths in 2021                                                                    |
|481   |PTNOTFSM6CLA1ABASICS_95_21     |% of non-disadvantaged pupils achieving 9-5 passes in GCSE English and maths in 2021                                                                    |
|482   |PTmultiLan_E                   |% of pupils entering more than one language                                                                                                             |
|483   |PTtripleSci_E                  |% of pupils entering biology, chemistry and physics                                                                                                     |
|484   |TFSM6CLA1A_20                  |Number of disadvantaged pupils at the end of key stage 4 in 2020                                                                                        |
|485   |PTFSM6CLA1A_20                 |% of pupils at the end of key stage 4 who were disadvantaged in 2020                                                                                    |
|486   |TNOTFSM6CLA1A_20               |Number of non-disadvantaged pupils at the end of key stage 4 in 2020                                                                                    |
|487   |PTNOTFSM6CLA1A_20              |% of pupils at the end of key stage 4 who were not disadvantaged in 2020                                                                                |
|488   |TFSM6CLA1A_21                  |Number of disadvantaged pupils in 2021                                                                                                                  |
|489   |PTFSM6CLA1A_21                 |% of pupils who were disadvantaged in 2021                                                                                                              |
|490   |TNOTFSM6CLA1A_21               |Number of non-disadvantaged pupils in 2021                                                                                                              |
|491   |PTNOTFSM6CLA1A_21              |% of pupils who were not disadvantaged in 2021                                                                                                          |
|492   |TAVENT_E_3NG_PTQ_EE            |Average number of KS4 entries per pupil                                                                                                                 |
|493   |TAVENT_E_3NG_LO_PTQ_EE         |Average number of KS4 entries per pupil with low prior attainment                                                                                       |
|494   |TAVENT_E_3NG_MID_PTQ_EE        |Average number of KS4 entries per pupil with middle prior attainment                                                                                    |
|495   |TAVENT_E_3NG_HI_PTQ_EE         |Average number of KS4 entries per pupil with high prior attainment                                                                                      |
|496   |TAVENT_E_3NG_FSM6CLA1A_PTQ_EE  |Average number of KS4 entries per disadvantaged pupil                                                                                                   |
|497   |TAVENT_E_3NG_NFSM6CLA1A_PTQ_EE |Average number of KS4 entries per non-disadvantaged pupil                                                                                               |
|498   |TAVENT_EFSM6CLA1A_20_PTQ_EE    |Average number of KS4 entries per disadvantaged pupil in 2020                                                                                           |
|499   |TAVENT_ENFSM6CLA1A_20_PTQ_EE   |Average number of KS4 entries per non-disadvantaged pupil in 2020                                                                                       |
|500   |TAVENT_EFSM6CLA1A_21_PTQ_EE    |Average number of KS4 entries per disadvantaged pupil in 2021                                                                                           |
|501   |TAVENT_ENFSM6CLA1A_21_PTQ_EE   |Average number of KS4 entries per non-disadvantaged pupil in 2021                                                                                       |
|502   |TAVENT_G_PTQ_EE                |Average number of GCSE entries per pupil                                                                                                                |
|503   |TAVENT_GLO_PTQ_EE              |Average number of GCSE entries per pupil with low prior attainment                                                                                      |
|504   |TAVENT_GAV_PTQ_EE              |Average number of GCSE entries per pupil with middle prior attainment                                                                                   |
|505   |TAVENT_GHI_PTQ_EE              |Average number of GCSE entries per pupil with high prior attainment                                                                                     |
|506   |TAVENT_GFSM6CLA1A_PTQ_EE       |Average number of GCSE entries per disadvantaged pupil                                                                                                  |
|507   |TAVENT_GNFSM6CLA1A_PTQ_EE      |Average number of GCSE entries per non-disadvantaged pupil                                                                                              |
|508   |TAVENT_GFSM6CLA1A_20_PTQ_EE    |Average number of GCSE entries per disadvantaged pupil in 2020                                                                                          |
|509   |TAVENT_GNFSM6CLA1A_20_PTQ_EE   |Average number of GCSE entries per non-disadvantaged pupil in 2020                                                                                      |
|510   |TAVENT_GFSM6CLA1A_21_PTQ_EE    |Average number of GCSE entries per disadvantaged pupil in 2021                                                                                          |
|511   |TAVENT_GNFSM6CLA1A_21_PTQ_EE   |Average number of GCSE entries per non-disadvantaged pupil in 2021                                                                                      |
|512   |TTOTENT_E_TOTAL_PTQ_EE         |Total volume of entries without discounting                                                                                                             |
|513   |TTOTENT_E_COVID_IMPACTED_PTQ_EE|Total volume of covid-impacted entries without discounting                                                                                              |
|514   |PTOTENT_E_COVID_IMPACTED_PTQ_EE|% of covid-impacted entries out of total number of entries                                                                                              |
</details>

<details>
<summary>census description</summary>
|Variable   |Label                                                                    |
|-----------|-------------------------------------------------------------------------|
|URN        |Unique Reference Number                                                  |
|LAESTAB    |DfE Number                                                               |
|TOTPUPSENDN|Total number of pupils on roll (all ages)                                |
|NORG       |Number of girls on roll                                                  |
|NORB       |Number of boys on roll                                                   |
|PNORG      |Percentage of girls on roll                                              |
|PNORB      |Percentage of boys on roll                                               |
|TSENSAP    |Number of pupils SEN statement or on School Action Plus                  |
|TSENA      |Number of pupils on roll with SEN on School Action                       |
|TOTSENST   |Total pupils with SEN statement                                          |
|TOTSENAP   |Total pupils at School  Action Plus                                      |
|PSENSAP    |Percentage of pupils with SEN statement or on School Action Plus         |
|PSENA      |Percentage of pupils on roll with SEN on School Action                   |
|PTOTSENST  |Percentage pupils with SEN statement                                     |
|PTOTSENAP  |Percentage pupils at School Action Plus                                  |
|NUMEAL     |Number of pupils with English not as first language                      |
|NUMENGFL   |Number of pupils with English first language                             |
|NUMUNCFL   |Number of pupils where first language is unclassified                    |
|PNUMEAL    |Percentage of pupils with English not as first language                  |
|PNUMENGFL  |Percentage pupils with English first language                            |
|PNUMUNCFL  |Percentage of pupils where first language is unclassified                |
|TOTPUPFSMDN|Number of pupils used in FSM calculation                                 |
|NUMFSM     |Total pupils eligible for free school meals                              |
|NUMNOFSM   |Total pupils not eligible for free school meals                          |
|PNUMFSM    |Percentage of  pupils eligible for free school meals                     |
|PNUMNOFSM  |Percentage pupils not eligible for free school meals                     |
|NUMFSMEVER |Number of pupils eligible for FSM at any time during the past 6 years    |
|PNUMFSMEVER|Percentage of pupils eligible for FSM at any time during the past 6 years|


### School workforce

The DfE published a yearly snapshot on the workforce in schools. This data is taken from 
[school workforce](https://www.gov.uk/government/collections/statistics-school-workforce)


#### Teachers

#### Vacancies

#### Timetabling




### Restricted datasets

The DfE maintains several restricted datasets that concerns sensitive data about students and teachers. The two main datasets are the [National Pupil Database](https://find-npd-data.education.gov.ukOffice of National Statistics through their Secure Research System) and the [School Workforce Census](https://www.gov.uk/guidance/apply-for-department-for-education-dfe-personal-data)
datasets. These datasets contain data including demographic indicators, results, degree qualifications and pay. To gain access to these datasets you need to complete a rather onerous process to justify your need for the data and your ability to work safely with it. Data is hosted by the Office of National Statistics through their [Secure Research Service (SRS)](https://www.ons.gov.uk/aboutus/whatwedo/statistics/requestingstatistics/secureresearchservice), an online platform where you can safely analyse data using R, Stata, Python, SPSS etc. To gain access to this system researchers will need to get [ONS accreditation](https://www.ons.gov.uk/aboutus/whatwedo/statistics/requestingstatistics/secureresearchservice/becomeanaccreditedresearcher), this process is free, but can take some time to arrange. The SRS offers several routes to access the data:

- _safe rooms_, dedicated research sites hosted by the ONS or other provider, e.g. a university (you won't be allowed to bring mobile phones or laptop into this sites, nor will you be able to remove any notes you take while undertaking research)
- _secure rooms_, rooms within your institution that have been cleared to access the SRS. You'll need to justify that this room is safe, e.g. single use room, no one overlooking you whilst working, locked door to the room, dedicated IP address linked to a networked physical socket not a WiFi connection.

More recently, due to the pandemic, VPN access has been allowed to the SRS. Requests for VPN access need to be made to the DfE and the ONS.

Additionally, the DfE have been working on the [LEO dataset](https://www.gov.uk/guidance/apply-to-access-the-longitudinal-education-outcomes-leo-dataset), a longitudinal dataset matching student outcomes to national insurance data on earnings. LEO is also accessed through the SRS. 
