{
  "hash": "fde29f413cc7b339fe7a61ce880f6323",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Questions and Answers\"\n---\n\n\n::: {.cell}\n\n:::\n\n\n# Questions about R {#sec-QANDA}\n\n## Why doesn't my `select`/`filter` statement work?\n\nWhen you are loading packages, sometimes different packages have the same function names in them, and the functions themselves will do very different things. For example, there is a `select` function in the `tidyverse`, but also *another* `select` function in the package `MASS` that does something very different. If we load the tidyverse before loading MASS, then the MASS version of select is the one that will be used?!\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(MASS)\n\ndiamonds %>% select(carat, cut, color)\n```\n:::\n\n\nTo get around this make sure that you load the `tidyverse` *after* `MASS`, to be safe you should always load the `tidyverse` last.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS) \nlibrary(tidyverse)\n\ndiamonds %>% select(carat, cut, color)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 53,940 × 3\n   carat cut       color\n   <dbl> <ord>     <ord>\n 1  0.23 Ideal     E    \n 2  0.21 Premium   E    \n 3  0.23 Good      E    \n 4  0.29 Premium   I    \n 5  0.31 Good      J    \n 6  0.24 Very Good J    \n 7  0.24 Very Good I    \n 8  0.26 Very Good H    \n 9  0.22 Fair      E    \n10  0.23 Very Good H    \n# ℹ 53,930 more rows\n```\n\n\n:::\n:::\n\n\nyou can also specify the package that select comes from (in this case from a package within the `tidyverse` called `dplyr`):\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndiamonds %>% dplyr::select(carat, cut, color)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 53,940 × 3\n   carat cut       color\n   <dbl> <ord>     <ord>\n 1  0.23 Ideal     E    \n 2  0.21 Premium   E    \n 3  0.23 Good      E    \n 4  0.29 Premium   I    \n 5  0.31 Good      J    \n 6  0.24 Very Good J    \n 7  0.24 Very Good I    \n 8  0.26 Very Good H    \n 9  0.22 Fair      E    \n10  0.23 Very Good H    \n# ℹ 53,930 more rows\n```\n\n\n:::\n:::\n\n\nFinally, there is a package that helps your deal with conflicts called `conflicted`. At the top of your script you can define which version of a function you prefer, this will be the version that will always be used. If you want to specify another version of a function, you can still use other versions of the function using the `::` notation:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(conflicted)\nconflicts_prefer(dplyr::select)\nconflicts_prefer(dplyr::mutate)\nconflicts_prefer(dplyr::summarise)\nconflicts_prefer(dplyr::filter)\n\ndf %>% select(name, age) # uses select from dplyr\ndf %>% MASS::select(name) # uses select from MASS\n```\n:::\n\n\nTo find out if you have any conflicts, you can run `conflict_scout()`.\n\n## How can I unload packages\n\nIf you are finding yourself with a conflict as mentioned above and want to `unload` packages, then you need to run the following code:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# adapted from: @mmfrgmpds https://stackoverflow.com/questions/7505547/detach-all-packages-while-working-in-r\nwhile(!is.null(sessionInfo()$loadedOnly)){\n  lapply(names(sessionInfo()$loadedOnly), require, character.only = TRUE)\n  invisible(lapply(paste0('package:', names(sessionInfo()$otherPkgs)), detach, character.only=TRUE, unload=TRUE, force=TRUE))    \n}\n```\n:::\n\n\n## Why am I getting the error 'could not find function \"%>%\"'\n\nThe pipe operator `%>%` is loaded when you load the tidyverse package - make sure you have installed tidyverse and loaded it\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninstall.packages(\"tidyverse\")  # install\nlibrary(tidyverse)             # load\n```\n:::\n\n\n## I am getting the error: '\"Error: Mapping should be created with `aes()` or `aes_()`.\"' when using ggplot\n\nThis may be caused by having a bracket after the geom rather than before it\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata<-data.frame(x=5:1,\n                 y=10:6)\nggplot(data, aes(x, y) +           # Reproduce error message\n         geom_point())\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata<-data.frame(x=5:1,\n                 y=10:6)\nggplot(data, aes(x, y)) +           # Fixed error by moving bracket\n         geom_point()\n```\n:::\n\n\n## My axis labels are too long\n\nIf you want to use long axis titles you may find they overrun the space available\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make a sample data frame\ndata<-data.frame(x=5:1,\n                 y=10:6)\n\n# plot the data\nggplot(data, aes(x=x, y=y)) +           \n         geom_col()+\n  ylab(\"A very long description for the y-axis label that will overflow and not look very nice\")\n```\n\n::: {.cell-output-display}\n![](A6-QandA_files/figure-html/unnamed-chunk-10-1.png){width=95%}\n:::\n:::\n\n\nTo insert a line break in the axis label, add `\\n` to the text where you want line breaks.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Make a sample data frame\ndata<-data.frame(x=5:1,\n                 y=10:6)\n\n# plot the data\nggplot(data, aes(x=x, y=y)) +           \n         geom_col()+\n  ylab(\"A very long description \\n for the y-axis label that will \\n overflow and not look very nice\")\n```\n\n::: {.cell-output-display}\n![](A6-QandA_files/figure-html/unnamed-chunk-11-1.png){width=95%}\n:::\n:::\n\n\n## How can I find out the full item labels in the PISA data frame?\n\nThe code below will give you a list of all the item labels\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# You may want to set the maximun print output to see all the labels\noptions(max.print = 1300)\n\nlapply(PISA_2022, attr, \"label\")\n```\n:::\n\n\n## How do I turn a data frame into a form I can put into an assignment or paper?\n\nYou can use the `gt` package to convert data frames to aesthetically pleasing outputs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load the gt package - you will need to run install.packages(\"gt\") the first time\n# install.packages(\"gt\")\nlibrary(gt)\n\n# Make the data frame you want you want to output\nscience_mean_scores <- PISA_2022 %>%\n  group_by(CNT) %>%\n  summarise(mean_science_score = mean(PV1SCIE, na.rm = TRUE),\n            sd_science = sd(PV1SCIE, na.rm =TRUE))\n\n# Use gt to produce an output - you can copy and paste the table from the\n# viewer window to your report\n\ngt(science_mean_scores)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"imeqsdkxyz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#imeqsdkxyz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#imeqsdkxyz thead, #imeqsdkxyz tbody, #imeqsdkxyz tfoot, #imeqsdkxyz tr, #imeqsdkxyz td, #imeqsdkxyz th {\n  border-style: none;\n}\n\n#imeqsdkxyz p {\n  margin: 0;\n  padding: 0;\n}\n\n#imeqsdkxyz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#imeqsdkxyz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#imeqsdkxyz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#imeqsdkxyz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#imeqsdkxyz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#imeqsdkxyz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#imeqsdkxyz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#imeqsdkxyz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#imeqsdkxyz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#imeqsdkxyz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#imeqsdkxyz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#imeqsdkxyz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#imeqsdkxyz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#imeqsdkxyz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#imeqsdkxyz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#imeqsdkxyz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#imeqsdkxyz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#imeqsdkxyz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#imeqsdkxyz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#imeqsdkxyz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#imeqsdkxyz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#imeqsdkxyz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#imeqsdkxyz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#imeqsdkxyz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#imeqsdkxyz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#imeqsdkxyz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#imeqsdkxyz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#imeqsdkxyz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#imeqsdkxyz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#imeqsdkxyz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#imeqsdkxyz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#imeqsdkxyz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#imeqsdkxyz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#imeqsdkxyz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#imeqsdkxyz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#imeqsdkxyz .gt_left {\n  text-align: left;\n}\n\n#imeqsdkxyz .gt_center {\n  text-align: center;\n}\n\n#imeqsdkxyz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#imeqsdkxyz .gt_font_normal {\n  font-weight: normal;\n}\n\n#imeqsdkxyz .gt_font_bold {\n  font-weight: bold;\n}\n\n#imeqsdkxyz .gt_font_italic {\n  font-style: italic;\n}\n\n#imeqsdkxyz .gt_super {\n  font-size: 65%;\n}\n\n#imeqsdkxyz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#imeqsdkxyz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#imeqsdkxyz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#imeqsdkxyz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#imeqsdkxyz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#imeqsdkxyz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#imeqsdkxyz .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#imeqsdkxyz .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#imeqsdkxyz div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CNT\">Country code 3-character</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean_science_score\">mean_science_score</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd_science\">sd_science</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Albania</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">375.8650</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">81.17499</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">United Arab Emirates</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">435.9609</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">108.04562</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Argentina</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">415.0584</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">86.30466</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Australia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">507.7795</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">106.78340</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Austria</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">494.0894</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">99.10689</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Belgium</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">495.0015</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">99.89222</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Bulgaria</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">421.9872</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">94.68480</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Brazil</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">406.3370</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">93.33488</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Brunei Darussalam</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">444.8849</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">93.49958</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Canada</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">499.4697</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">98.78625</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Switzerland</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">501.4123</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">97.88277</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Chile</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">463.1057</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">94.91051</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Colombia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">420.9458</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">88.24887</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Costa Rica</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">411.2082</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">80.40614</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Czech Republic</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">510.7872</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">102.76484</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Germany</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">495.2547</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">105.42084</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Denmark</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">480.3369</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">96.87209</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Dominican Republic</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">361.6200</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">68.71457</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Spain</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">492.9236</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">90.06178</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Estonia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">527.3109</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">87.67284</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Finland</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">497.9649</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">111.47589</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">France</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">481.3834</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">105.72320</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">United Kingdom</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">492.2651</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">102.15378</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Georgia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">385.6145</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">81.63218</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Greece</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">445.4408</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">88.95744</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Guatemala</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">374.5886</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">65.37109</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Hong Kong (China)</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">524.5497</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">91.06857</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Croatia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">483.1283</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">91.97320</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Hungary</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">492.1069</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">94.69703</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Indonesia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">394.9906</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">69.89182</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Ireland</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">504.3750</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">91.95203</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Iceland</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">448.0546</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">94.76950</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Israel</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">464.0777</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">108.57084</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Italy</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">481.3281</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">91.97045</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Jamaica</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">395.7114</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">91.97299</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Jordan</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">374.6990</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">73.68470</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Japan</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">545.5399</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">92.72193</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Kazakhstan</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">440.9755</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">84.44319</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Cambodia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">340.4659</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">50.34331</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Korea</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">530.6552</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">103.99342</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Kosovo</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">353.5723</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">64.84509</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Lithuania</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">480.0535</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">92.51359</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Latvia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">492.5822</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">84.61410</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Macao (China)</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">543.1331</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">86.61414</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Morocco</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">363.4098</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">66.20574</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Republic of Moldova</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">416.8691</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">82.50639</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Mexico</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">410.7969</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">74.97042</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">North Macedonia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">382.3574</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">82.77203</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Malta</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">469.8360</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">101.83745</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Montenegro</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">404.9706</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">83.35015</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Mongolia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">411.4142</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">77.72520</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Malaysia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">417.1980</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">77.85995</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Netherlands</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">486.8380</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">111.77833</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Norway</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">478.9396</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">106.09425</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">New Zealand</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">504.8458</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">107.85424</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Panama</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">385.0859</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">84.92427</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Peru</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">410.8352</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">85.35240</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Philippines</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">353.7724</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">76.99187</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Poland</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">505.1500</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">94.16577</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Portugal</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">488.2668</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">89.70144</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Paraguay</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">371.6893</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">74.52611</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Palestinian Authority</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">367.0259</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">70.91610</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Qatar</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">428.8246</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">96.25937</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Baku (Azerbaijan)</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">381.5571</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">78.67151</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Ukrainian regions (18 of 27)</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">454.4918</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">88.72635</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Romania</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">436.4904</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">96.24036</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Saudi Arabia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">390.1679</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">72.21294</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Singapore</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">560.8252</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">99.60358</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">El Salvador</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">374.9843</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">73.44363</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Serbia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">446.7715</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">88.26844</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Slovak Republic</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">467.2694</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">102.95534</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Slovenia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">487.1098</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">93.85904</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Sweden</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">494.1717</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">107.51162</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Chinese Taipei</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">526.8225</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">102.25648</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Thailand</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">429.1863</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">93.12958</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Türkiye</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">476.0276</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">89.06750</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Uruguay</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">433.2891</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">92.41654</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">United States</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">498.2506</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">108.85390</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Uzbekistan</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">355.3407</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">63.34434</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Viet Nam</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">473.3375</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">78.42436</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\n# You can see more options on formating the table here: https://gt.rstudio.com\n# For example to add a heading\n\ngt(science_mean_scores) %>% tab_header(\n    title = \"Mean science scores\",\n    subtitle = \"PISA 2022 data\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ikbzlrdvlo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ikbzlrdvlo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ikbzlrdvlo thead, #ikbzlrdvlo tbody, #ikbzlrdvlo tfoot, #ikbzlrdvlo tr, #ikbzlrdvlo td, #ikbzlrdvlo th {\n  border-style: none;\n}\n\n#ikbzlrdvlo p {\n  margin: 0;\n  padding: 0;\n}\n\n#ikbzlrdvlo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ikbzlrdvlo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ikbzlrdvlo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ikbzlrdvlo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ikbzlrdvlo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ikbzlrdvlo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ikbzlrdvlo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ikbzlrdvlo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ikbzlrdvlo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ikbzlrdvlo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ikbzlrdvlo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ikbzlrdvlo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ikbzlrdvlo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ikbzlrdvlo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ikbzlrdvlo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ikbzlrdvlo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ikbzlrdvlo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ikbzlrdvlo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ikbzlrdvlo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ikbzlrdvlo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ikbzlrdvlo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ikbzlrdvlo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ikbzlrdvlo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ikbzlrdvlo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ikbzlrdvlo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ikbzlrdvlo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ikbzlrdvlo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ikbzlrdvlo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ikbzlrdvlo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ikbzlrdvlo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ikbzlrdvlo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ikbzlrdvlo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ikbzlrdvlo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ikbzlrdvlo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ikbzlrdvlo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ikbzlrdvlo .gt_left {\n  text-align: left;\n}\n\n#ikbzlrdvlo .gt_center {\n  text-align: center;\n}\n\n#ikbzlrdvlo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ikbzlrdvlo .gt_font_normal {\n  font-weight: normal;\n}\n\n#ikbzlrdvlo .gt_font_bold {\n  font-weight: bold;\n}\n\n#ikbzlrdvlo .gt_font_italic {\n  font-style: italic;\n}\n\n#ikbzlrdvlo .gt_super {\n  font-size: 65%;\n}\n\n#ikbzlrdvlo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ikbzlrdvlo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ikbzlrdvlo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ikbzlrdvlo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ikbzlrdvlo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ikbzlrdvlo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ikbzlrdvlo .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ikbzlrdvlo .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ikbzlrdvlo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\" style>Mean science scores</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>PISA 2022 data</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CNT\">Country code 3-character</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean_science_score\">mean_science_score</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd_science\">sd_science</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Albania</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">375.8650</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">81.17499</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">United Arab Emirates</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">435.9609</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">108.04562</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Argentina</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">415.0584</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">86.30466</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Australia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">507.7795</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">106.78340</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Austria</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">494.0894</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">99.10689</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Belgium</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">495.0015</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">99.89222</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Bulgaria</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">421.9872</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">94.68480</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Brazil</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">406.3370</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">93.33488</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Brunei Darussalam</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">444.8849</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">93.49958</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Canada</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">499.4697</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">98.78625</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Switzerland</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">501.4123</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">97.88277</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Chile</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">463.1057</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">94.91051</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Colombia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">420.9458</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">88.24887</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Costa Rica</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">411.2082</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">80.40614</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Czech Republic</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">510.7872</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">102.76484</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Germany</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">495.2547</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">105.42084</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Denmark</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">480.3369</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">96.87209</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Dominican Republic</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">361.6200</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">68.71457</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Spain</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">492.9236</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">90.06178</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Estonia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">527.3109</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">87.67284</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Finland</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">497.9649</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">111.47589</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">France</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">481.3834</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">105.72320</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">United Kingdom</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">492.2651</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">102.15378</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Georgia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">385.6145</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">81.63218</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Greece</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">445.4408</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">88.95744</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Guatemala</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">374.5886</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">65.37109</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Hong Kong (China)</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">524.5497</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">91.06857</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Croatia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">483.1283</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">91.97320</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Hungary</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">492.1069</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">94.69703</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Indonesia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">394.9906</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">69.89182</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Ireland</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">504.3750</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">91.95203</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Iceland</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">448.0546</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">94.76950</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Israel</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">464.0777</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">108.57084</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Italy</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">481.3281</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">91.97045</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Jamaica</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">395.7114</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">91.97299</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Jordan</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">374.6990</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">73.68470</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Japan</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">545.5399</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">92.72193</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Kazakhstan</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">440.9755</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">84.44319</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Cambodia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">340.4659</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">50.34331</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Korea</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">530.6552</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">103.99342</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Kosovo</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">353.5723</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">64.84509</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Lithuania</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">480.0535</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">92.51359</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Latvia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">492.5822</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">84.61410</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Macao (China)</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">543.1331</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">86.61414</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Morocco</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">363.4098</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">66.20574</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Republic of Moldova</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">416.8691</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">82.50639</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Mexico</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">410.7969</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">74.97042</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">North Macedonia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">382.3574</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">82.77203</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Malta</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">469.8360</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">101.83745</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Montenegro</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">404.9706</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">83.35015</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Mongolia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">411.4142</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">77.72520</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Malaysia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">417.1980</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">77.85995</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Netherlands</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">486.8380</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">111.77833</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Norway</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">478.9396</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">106.09425</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">New Zealand</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">504.8458</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">107.85424</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Panama</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">385.0859</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">84.92427</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Peru</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">410.8352</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">85.35240</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Philippines</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">353.7724</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">76.99187</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Poland</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">505.1500</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">94.16577</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Portugal</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">488.2668</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">89.70144</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Paraguay</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">371.6893</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">74.52611</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Palestinian Authority</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">367.0259</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">70.91610</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Qatar</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">428.8246</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">96.25937</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Baku (Azerbaijan)</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">381.5571</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">78.67151</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Ukrainian regions (18 of 27)</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">454.4918</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">88.72635</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Romania</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">436.4904</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">96.24036</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Saudi Arabia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">390.1679</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">72.21294</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Singapore</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">560.8252</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">99.60358</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">El Salvador</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">374.9843</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">73.44363</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Serbia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">446.7715</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">88.26844</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Slovak Republic</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">467.2694</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">102.95534</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Slovenia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">487.1098</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">93.85904</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Sweden</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">494.1717</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">107.51162</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Chinese Taipei</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">526.8225</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">102.25648</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Thailand</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">429.1863</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">93.12958</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Türkiye</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">476.0276</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">89.06750</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Uruguay</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">433.2891</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">92.41654</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">United States</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">498.2506</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">108.85390</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Uzbekistan</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">355.3407</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">63.34434</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Viet Nam</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">473.3375</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">78.42436</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\n# Or to change the number of decimal places and a column name\n\ngt(science_mean_scores) %>% tab_header(\n  title = \"Mean science scores\",\n  subtitle = \"PISA 2022 data\") %>%\n  fmt_number(columns = c(mean_science_score , sd_science), decimals = 1) %>%\n  cols_label(\"CNT\" = md(\"**Country**\"))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"pxojqzivxo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#pxojqzivxo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#pxojqzivxo thead, #pxojqzivxo tbody, #pxojqzivxo tfoot, #pxojqzivxo tr, #pxojqzivxo td, #pxojqzivxo th {\n  border-style: none;\n}\n\n#pxojqzivxo p {\n  margin: 0;\n  padding: 0;\n}\n\n#pxojqzivxo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#pxojqzivxo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#pxojqzivxo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#pxojqzivxo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#pxojqzivxo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pxojqzivxo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pxojqzivxo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pxojqzivxo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#pxojqzivxo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#pxojqzivxo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#pxojqzivxo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#pxojqzivxo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#pxojqzivxo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#pxojqzivxo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#pxojqzivxo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#pxojqzivxo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#pxojqzivxo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#pxojqzivxo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#pxojqzivxo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pxojqzivxo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#pxojqzivxo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#pxojqzivxo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#pxojqzivxo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pxojqzivxo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#pxojqzivxo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#pxojqzivxo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pxojqzivxo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pxojqzivxo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#pxojqzivxo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pxojqzivxo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#pxojqzivxo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pxojqzivxo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pxojqzivxo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pxojqzivxo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pxojqzivxo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pxojqzivxo .gt_left {\n  text-align: left;\n}\n\n#pxojqzivxo .gt_center {\n  text-align: center;\n}\n\n#pxojqzivxo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#pxojqzivxo .gt_font_normal {\n  font-weight: normal;\n}\n\n#pxojqzivxo .gt_font_bold {\n  font-weight: bold;\n}\n\n#pxojqzivxo .gt_font_italic {\n  font-style: italic;\n}\n\n#pxojqzivxo .gt_super {\n  font-size: 65%;\n}\n\n#pxojqzivxo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#pxojqzivxo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#pxojqzivxo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#pxojqzivxo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#pxojqzivxo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#pxojqzivxo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#pxojqzivxo .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#pxojqzivxo .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#pxojqzivxo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\" style>Mean science scores</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>PISA 2022 data</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CNT\"><span data-qmd-base64=\"KipDb3VudHJ5Kio=\"><span class='gt_from_md'><strong>Country</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean_science_score\">mean_science_score</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd_science\">sd_science</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Albania</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">375.9</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">81.2</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">United Arab Emirates</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">436.0</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">108.0</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Argentina</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">415.1</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">86.3</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Australia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">507.8</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">106.8</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Austria</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">494.1</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">99.1</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Belgium</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">495.0</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">99.9</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Bulgaria</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">422.0</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">94.7</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Brazil</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">406.3</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">93.3</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Brunei Darussalam</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">444.9</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">93.5</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Canada</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">499.5</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">98.8</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Switzerland</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">501.4</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">97.9</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Chile</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">463.1</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">94.9</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Colombia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">420.9</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">88.2</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Costa Rica</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">411.2</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">80.4</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Czech Republic</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">510.8</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">102.8</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Germany</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">495.3</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">105.4</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Denmark</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">480.3</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">96.9</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Dominican Republic</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">361.6</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">68.7</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Spain</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">492.9</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">90.1</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Estonia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">527.3</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">87.7</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Finland</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">498.0</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">111.5</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">France</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">481.4</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">105.7</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">United Kingdom</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">492.3</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">102.2</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Georgia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">385.6</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">81.6</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Greece</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">445.4</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">89.0</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Guatemala</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">374.6</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">65.4</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Hong Kong (China)</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">524.5</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">91.1</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Croatia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">483.1</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">92.0</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Hungary</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">492.1</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">94.7</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Indonesia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">395.0</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">69.9</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Ireland</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">504.4</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">92.0</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Iceland</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">448.1</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">94.8</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Israel</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">464.1</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">108.6</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Italy</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">481.3</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">92.0</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Jamaica</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">395.7</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">92.0</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Jordan</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">374.7</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">73.7</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Japan</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">545.5</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">92.7</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Kazakhstan</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">441.0</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">84.4</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Cambodia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">340.5</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">50.3</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Korea</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">530.7</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">104.0</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Kosovo</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">353.6</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">64.8</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Lithuania</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">480.1</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">92.5</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Latvia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">492.6</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">84.6</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Macao (China)</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">543.1</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">86.6</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Morocco</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">363.4</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">66.2</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Republic of Moldova</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">416.9</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">82.5</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Mexico</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">410.8</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">75.0</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">North Macedonia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">382.4</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">82.8</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Malta</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">469.8</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">101.8</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Montenegro</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">405.0</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">83.4</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Mongolia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">411.4</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">77.7</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Malaysia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">417.2</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">77.9</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Netherlands</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">486.8</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">111.8</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Norway</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">478.9</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">106.1</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">New Zealand</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">504.8</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">107.9</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Panama</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">385.1</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">84.9</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Peru</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">410.8</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">85.4</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Philippines</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">353.8</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">77.0</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Poland</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">505.1</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">94.2</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Portugal</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">488.3</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">89.7</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Paraguay</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">371.7</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">74.5</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Palestinian Authority</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">367.0</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">70.9</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Qatar</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">428.8</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">96.3</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Baku (Azerbaijan)</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">381.6</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">78.7</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Ukrainian regions (18 of 27)</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">454.5</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">88.7</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Romania</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">436.5</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">96.2</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Saudi Arabia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">390.2</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">72.2</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Singapore</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">560.8</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">99.6</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">El Salvador</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">375.0</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">73.4</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Serbia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">446.8</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">88.3</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Slovak Republic</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">467.3</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">103.0</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Slovenia</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">487.1</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">93.9</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Sweden</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">494.2</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">107.5</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Chinese Taipei</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">526.8</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">102.3</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Thailand</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">429.2</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">93.1</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Türkiye</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">476.0</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">89.1</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Uruguay</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">433.3</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">92.4</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">United States</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">498.3</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">108.9</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Uzbekistan</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">355.3</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">63.3</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Viet Nam</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">473.3</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">78.4</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\n## If you have an output from a linear model, there is an additional step to do before using gt\n# You need to use the broom package, which has the `tidy` function which gets the output of `lm`\n# Into a suitable format for turing into a table\n# install.packages(\"broom\")\n\nlibrary(broom)\n\n# Create example dataframe\n\nUK_PISA <- PISA_2022 %>%\n  select(PV1SCIE, PV1MATH, CNT) %>%\n  filter(CNT == \"United Kingdom\")\n\n# Run the model\n\nuk_mod <- lm(data = UK_PISA, PV1SCIE ~ PV1MATH)\n\n# tidy the model\n\nuk_mod_tidy <- tidy(uk_mod)\n\n# pass to gt to produce nice output\n\ngt(uk_mod_tidy) %>% \n  fmt_number(columns=c(\"p.value\"), \n              decimals = 3) %>%\n  fmt_number(columns=c(\"estimate\", \"std.error\", \"statistic\"), \n              decimals = 2)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"kahhhkujqp\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#kahhhkujqp table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#kahhhkujqp thead, #kahhhkujqp tbody, #kahhhkujqp tfoot, #kahhhkujqp tr, #kahhhkujqp td, #kahhhkujqp th {\n  border-style: none;\n}\n\n#kahhhkujqp p {\n  margin: 0;\n  padding: 0;\n}\n\n#kahhhkujqp .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#kahhhkujqp .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#kahhhkujqp .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#kahhhkujqp .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#kahhhkujqp .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kahhhkujqp .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kahhhkujqp .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#kahhhkujqp .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#kahhhkujqp .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#kahhhkujqp .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#kahhhkujqp .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#kahhhkujqp .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#kahhhkujqp .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#kahhhkujqp .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#kahhhkujqp .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#kahhhkujqp .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#kahhhkujqp .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#kahhhkujqp .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#kahhhkujqp .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kahhhkujqp .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#kahhhkujqp .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#kahhhkujqp .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#kahhhkujqp .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kahhhkujqp .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#kahhhkujqp .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#kahhhkujqp .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kahhhkujqp .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kahhhkujqp .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#kahhhkujqp .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kahhhkujqp .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#kahhhkujqp .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#kahhhkujqp .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kahhhkujqp .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kahhhkujqp .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#kahhhkujqp .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#kahhhkujqp .gt_left {\n  text-align: left;\n}\n\n#kahhhkujqp .gt_center {\n  text-align: center;\n}\n\n#kahhhkujqp .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#kahhhkujqp .gt_font_normal {\n  font-weight: normal;\n}\n\n#kahhhkujqp .gt_font_bold {\n  font-weight: bold;\n}\n\n#kahhhkujqp .gt_font_italic {\n  font-style: italic;\n}\n\n#kahhhkujqp .gt_super {\n  font-size: 65%;\n}\n\n#kahhhkujqp .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#kahhhkujqp .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#kahhhkujqp .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#kahhhkujqp .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#kahhhkujqp .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#kahhhkujqp .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#kahhhkujqp .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#kahhhkujqp .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#kahhhkujqp div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">42.33</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.30</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">18.37</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">PV1MATH</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.93</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">199.00</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## How do I report the results of tests in APA format?\n\nWhen you have run some tests, the outputs (for example the degrees of freedom, test statistic and p-value) should be formatted in your paper in line with the citation convention of the journal or assessment (for example, KCL assignments follow the American Psychological Association (APA) citation style). You can find a general guide to presenting your results in APA style here: APA [numbers and statistics style guide](https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf).\n\nFor example, to report a chi-square result:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create example dataframe\n\nUK_gender_differences <- PISA_2022 %>%\n  select(CNT, ST004D01T) %>%\n  filter(CNT == \"United Kingdom\") %>% \n  droplevels()\n\ncont_tab <- xtabs(data = UK_gender_differences, ~ ST004D01T)\n\n# Run a chi sqaure goodness of fit test\n\nchisq.test(cont_tab, p = c(0.5, 0.5))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tChi-squared test for given probabilities\n\ndata:  cont_tab\nX-squared = 2.4425, df = 1, p-value = 0.1181\n```\n\n\n:::\n:::\n\nA chi-square test of goodness-of-fit was conducted to compare the observed frequencies in the contingency table to the expected frequencies (equal numbers of boys and girls). The result was not statistically significant, χ²(1, N = 12973) = 2.44, p = .12, indicating no significant difference between the observed and expected frequencies.\n\n\nTo report a t-test of the mathematics scores of girls and boys in the UK:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create example dataframe\n\nUK_PISA <- PISA_2022 %>%\n  select(PV1MATH, CNT, ST004D01T) %>%\n  filter(CNT == \"United Kingdom\")\n\n# Run a t-test\n\nt.test(data = UK_PISA, PV1MATH ~ ST004D01T)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  PV1MATH by ST004D01T\nt = -8.2246, df = 12942, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group Female and group Male is not equal to 0\n95 percent confidence interval:\n -16.9470 -10.4238\nsample estimates:\nmean in group Female   mean in group Male \n            475.6061             489.2915 \n```\n\n\n:::\n:::\n\nThe output of that test would be reported as follows:\n\nThe results of a Welch's t-test indicated a statistically significant difference in mean mathematics scores between UK females (M = 475.61) and UK males (M = 489.29), t(12,942) = -8.22, p < .001, 95% CI [-16.95, -10.42].\n\nAlternatively, consider the output of an anova to look at the difference in wealth scores between Finland, Norway, and Sweden:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create example dataframe\n\nwealth_scores <- PISA_2022 %>%\n  select(HOMEPOS, CNT) %>%\n  filter(CNT == \"Finland\" | CNT == \"Norway\" | CNT == \"Sweden\")\n\n# Run an anova and summarise\n\naov_out <- aov(data = wealth_scores, HOMEPOS ~ CNT)\nsummary(aov_out)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               Df Sum Sq Mean Sq F value Pr(>F)    \nCNT             2    575  287.61   356.7 <2e-16 ***\nResiduals   22335  18008    0.81                   \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n584 observations deleted due to missingness\n```\n\n\n:::\n\n```{.r .cell-code}\nTukeyHSD(aov_out)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Tukey multiple comparisons of means\n    95% family-wise confidence level\n\nFit: aov(formula = HOMEPOS ~ CNT, data = wealth_scores)\n\n$CNT\n                     diff        lwr        upr p adj\nNorway-Finland  0.3846629  0.3508747  0.4184511     0\nSweden-Finland  0.1645141  0.1301168  0.1989114     0\nSweden-Norway  -0.2201488 -0.2581530 -0.1821445     0\n```\n\n\n:::\n:::\n\n\nA one-way ANOVA was conducted to compare levels of home possessions (HOMEPOS) across three countries (CNT: Finland, Norway, and Sweden). The analysis revealed a statistically significant effect of country on home possessions, F(2, 22,335) = 356.7, p < .001, η² = .031.\n\nPost hoc Tukey's HSD tests indicated the following pairwise differences:\n\nNorway had significantly higher HOMEPOS scores than Finland (M difference = 0.38, 95% CI [0.35, 0.42], p < .001).\nSweden had significantly higher HOMEPOS scores than Finland (M difference = 0.16, 95% CI [0.13, 0.20], p < .001).\nSweden had significantly lower HOMEPOS scores than Norway (M difference = -0.22, 95% CI [-0.26, -0.18], p < .001).\nA total of 584 observations were excluded due to missing data.\n\nAlternatively, you can use the `report` function in the `easystats` package to give a summary of an output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(easystats)\n\n# Get a summary of an anova\n\nreport(aov_out)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nThe ANOVA (formula: HOMEPOS ~ CNT) suggests that:\n\n  - The main effect of CNT is statistically significant and small (F(2, 22335) =\n356.72, p < .001; Eta2 = 0.03, 95% CI [0.03, 1.00])\n\nEffect sizes were labelled following Field's (2013) recommendations.\n```\n\n\n:::\n\n```{.r .cell-code}\n# And of a linear model\n\nmod1 <- lm(data = wealth_scores, HOMEPOS ~ CNT)\n\nreport(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWe fitted a linear model (estimated using OLS) to predict HOMEPOS with CNT\n(formula: HOMEPOS ~ CNT). The model explains a statistically significant and\nweak proportion of variance (R2 = 0.03, F(2, 22335) = 356.72, p < .001, adj. R2\n= 0.03). The model's intercept, corresponding to CNT = Albania, is at 0.16 (95%\nCI [0.14, 0.18], t(22335) = 18.13, p < .001). Within this model:\n\n  - The effect of CNT [Norway] is statistically significant and positive (beta =\n0.38, 95% CI [0.36, 0.41], t(22335) = 26.68, p < .001; Std. beta = 0.42, 95% CI\n[0.39, 0.45])\n  - The effect of CNT [Sweden] is statistically significant and positive (beta =\n0.16, 95% CI [0.14, 0.19], t(22335) = 11.21, p < .001; Std. beta = 0.18, 95% CI\n[0.15, 0.21])\n\nStandardized parameters were obtained by fitting the model on a standardized\nversion of the dataset. 95% Confidence Intervals (CIs) and p-values were\ncomputed using a Wald t-distribution approximation.\n```\n\n\n:::\n:::\n\n\nThe `report` function will work on other test outputs, for example, on a t-test:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create example data frame\n\nUK_PISA <- PISA_2022 %>%\n  select(PV1MATH, CNT, ST004D01T) %>%\n  filter(CNT == \"United Kingdom\") %>%\n  droplevels()\n\n# Use report on a t-test\n\nreport(t.test(data = UK_PISA, PV1MATH ~ ST004D01T))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEffect sizes were labelled following Cohen's (1988) recommendations.\n\nThe Welch Two Sample t-test testing the difference of PV1MATH by ST004D01T\n(mean in group Female = 475.61, mean in group Male = 489.29) suggests that the\neffect is negative, statistically significant, and very small (difference =\n-13.69, 95% CI [-16.95, -10.42], t(12942.17) = -8.22, p < .001; Cohen's d =\n-0.14, 95% CI [-0.18, -0.11])\n```\n\n\n:::\n:::\n\n\n\n\nTo produce tables in APA format, you can use the `apa.aov.table` (for anovas) or `apa.reg.table` (for linear model outputs) functions from the `apaTables` package. You will need to install the package first using `install.packages(\"apaTables\")`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(apaTables)\n\n# Get a summary table from an anova\n\napa.aov.table(aov_out)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\nANOVA results using HOMEPOS as the dependent variable\n \n\n   Predictor       SS    df     MS      F    p partial_eta2 CI_90_partial_eta2\n (Intercept)   264.91     1 264.91 328.56 .000                                \n         CNT   575.22     2 287.61 356.72 .000          .03         [.03, .03]\n       Error 18007.84 22335   0.81                                            \n\nNote: Values in square brackets indicate the bounds of the 90% confidence interval for partial eta-squared \n```\n\n\n:::\n\n```{.r .cell-code}\n# And of a linear model\n\napa.reg.table(mod1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\nRegression results using HOMEPOS as the criterion\n \n\n   Predictor      b     b_95%_CI sr2 sr2_95%_CI             Fit\n (Intercept) 0.16** [0.14, 0.18]                               \n   CNTNorway 0.38** [0.36, 0.41] .03 [.03, .04]                \n   CNTSweden 0.16** [0.14, 0.19] .01 [.00, .01]                \n                                                    R2 = .031**\n                                                95% CI[.03,.04]\n                                                               \n\nNote. A significant b-weight indicates the semi-partial correlation is also significant.\nb represents unstandardized regression weights. \nsr2 represents the semi-partial correlation squared.\nSquare brackets are used to enclose the lower and upper limits of a confidence interval.\n* indicates p < .05. ** indicates p < .01.\n \n```\n\n\n:::\n:::\n\nYou can get more aesthetically pleasing versions of both tables using the `gt` function in the `gt` package. Before passing the outputs of `avo` of `lm` to `gt`, you will need to use the `tidy` fucntion from the `broom` package to tidy the output.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gt)\nlibrary(broom)\n\n# Tidy the outputs\n\ntidied_aov <- tidy(aov_out)\ntidied_mod1 <- tidy(mod1)\n\n\n# Produced a nicely formatted table from an anova\n\ngt(tidied_aov)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ypgoenhkvz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ypgoenhkvz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ypgoenhkvz thead, #ypgoenhkvz tbody, #ypgoenhkvz tfoot, #ypgoenhkvz tr, #ypgoenhkvz td, #ypgoenhkvz th {\n  border-style: none;\n}\n\n#ypgoenhkvz p {\n  margin: 0;\n  padding: 0;\n}\n\n#ypgoenhkvz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ypgoenhkvz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ypgoenhkvz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ypgoenhkvz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ypgoenhkvz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ypgoenhkvz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ypgoenhkvz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ypgoenhkvz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ypgoenhkvz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ypgoenhkvz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ypgoenhkvz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ypgoenhkvz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ypgoenhkvz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ypgoenhkvz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ypgoenhkvz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ypgoenhkvz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ypgoenhkvz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ypgoenhkvz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ypgoenhkvz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ypgoenhkvz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ypgoenhkvz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ypgoenhkvz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ypgoenhkvz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ypgoenhkvz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ypgoenhkvz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ypgoenhkvz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ypgoenhkvz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ypgoenhkvz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ypgoenhkvz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ypgoenhkvz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ypgoenhkvz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ypgoenhkvz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ypgoenhkvz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ypgoenhkvz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ypgoenhkvz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ypgoenhkvz .gt_left {\n  text-align: left;\n}\n\n#ypgoenhkvz .gt_center {\n  text-align: center;\n}\n\n#ypgoenhkvz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ypgoenhkvz .gt_font_normal {\n  font-weight: normal;\n}\n\n#ypgoenhkvz .gt_font_bold {\n  font-weight: bold;\n}\n\n#ypgoenhkvz .gt_font_italic {\n  font-style: italic;\n}\n\n#ypgoenhkvz .gt_super {\n  font-size: 65%;\n}\n\n#ypgoenhkvz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ypgoenhkvz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ypgoenhkvz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ypgoenhkvz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ypgoenhkvz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ypgoenhkvz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ypgoenhkvz .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ypgoenhkvz .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ypgoenhkvz div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"df\">df</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sumsq\">sumsq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"meansq\">meansq</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">CNT</td>\n<td headers=\"df\" class=\"gt_row gt_right\">2</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">575.2171</td>\n<td headers=\"meansq\" class=\"gt_row gt_right\">287.6085570</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">356.719</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">3.175047e-153</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">Residuals</td>\n<td headers=\"df\" class=\"gt_row gt_right\">22335</td>\n<td headers=\"sumsq\" class=\"gt_row gt_right\">18007.8370</td>\n<td headers=\"meansq\" class=\"gt_row gt_right\">0.8062609</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">NA</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">NA</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\n# And of a linear model\n\ngt(tidied_mod1)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"mlzhieklzo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mlzhieklzo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mlzhieklzo thead, #mlzhieklzo tbody, #mlzhieklzo tfoot, #mlzhieklzo tr, #mlzhieklzo td, #mlzhieklzo th {\n  border-style: none;\n}\n\n#mlzhieklzo p {\n  margin: 0;\n  padding: 0;\n}\n\n#mlzhieklzo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mlzhieklzo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mlzhieklzo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mlzhieklzo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mlzhieklzo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mlzhieklzo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mlzhieklzo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mlzhieklzo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mlzhieklzo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mlzhieklzo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mlzhieklzo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mlzhieklzo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mlzhieklzo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mlzhieklzo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mlzhieklzo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mlzhieklzo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mlzhieklzo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mlzhieklzo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mlzhieklzo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mlzhieklzo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mlzhieklzo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mlzhieklzo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mlzhieklzo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mlzhieklzo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mlzhieklzo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mlzhieklzo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mlzhieklzo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mlzhieklzo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mlzhieklzo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mlzhieklzo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mlzhieklzo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mlzhieklzo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mlzhieklzo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mlzhieklzo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mlzhieklzo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mlzhieklzo .gt_left {\n  text-align: left;\n}\n\n#mlzhieklzo .gt_center {\n  text-align: center;\n}\n\n#mlzhieklzo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mlzhieklzo .gt_font_normal {\n  font-weight: normal;\n}\n\n#mlzhieklzo .gt_font_bold {\n  font-weight: bold;\n}\n\n#mlzhieklzo .gt_font_italic {\n  font-style: italic;\n}\n\n#mlzhieklzo .gt_super {\n  font-size: 65%;\n}\n\n#mlzhieklzo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mlzhieklzo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mlzhieklzo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mlzhieklzo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mlzhieklzo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mlzhieklzo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mlzhieklzo .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#mlzhieklzo .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#mlzhieklzo div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.1622658</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.008951941</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">18.12632</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">6.584384e-73</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">CNTNorway</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.3846629</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.014415658</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">26.68369</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.915252e-154</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">CNTSweden</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.1645141</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.014675508</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">11.21011</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">4.349919e-29</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## How do I add the results from statistical tests to ggplot?\n\nThere are a number of helpful packages that can add data to charts. First `ggpubr` lets you add data about the regression line to your plot using the `stat_regline_equation()` function. You will need to tweak the coordinates (`label.x` and `label.y`) to appear appropiately on your chart.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the ggpbur library (you will need to run install.packages(\"ggpubr\") the first time you use it)\nlibrary(ggpubr)\n\n# Create example dataframe\n\nUK_wealth_reading <- PISA_2022 %>%\n  select(CNT, PV1READ, HOMEPOS) %>%\n  filter(CNT == \"United Kingdom\") \n\n# Plot a scatter plot with the regression equation\n\nggplot(UK_wealth_reading, aes(x = HOMEPOS, y = PV1READ)) +\n  geom_point(colour = \"lightgreen\", size = 0.1) +\n  geom_smooth(method = \"lm\") +\n  stat_regline_equation(label.x = -5, label.y = 600)  # Add regression equation\n```\n\n::: {.cell-output-display}\n![](A6-QandA_files/figure-html/unnamed-chunk-21-1.png){width=95%}\n:::\n:::\n\n\nYou can also use `stat_regline_equation` to add additional information like the p-value of the model and the R^2^ value:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the ggpbur library (you will need to run install.packages(\"ggpubr\") the first time you use it)\nlibrary(ggpubr)\n\n# Create example dataframe\n\nUK_wealth_reading <- PISA_2022 %>%\n  select(CNT, PV1READ, HOMEPOS) %>%\n  filter(CNT == \"United Kingdom\") \n\n# Plot a scatter plot with the regression equation\n\nggplot(UK_wealth_reading, aes(x = HOMEPOS, y = PV1READ)) +\n  geom_point(colour = \"lightgreen\", size = 0.1) +\n  geom_smooth(method = \"lm\", formula = y ~ x) + # Ensure formula is specified here too\n  stat_regline_equation(\n    aes(label = paste(..eq.label.., ..adj.rr.label.., sep = \"~~~~\")), # Indicate you want the equation and R2 value and the seperator text\n    label.x = -10, label.y = 600,\n    formula = y ~ x)\n```\n\n::: {.cell-output-display}\n![](A6-QandA_files/figure-html/unnamed-chunk-22-1.png){width=95%}\n:::\n:::\n\n\nAnother powerful package for adding data to graphs is `ggstatsplot`. For example, it can anotate a plot with anova data. For example, if you want compare the science scores of the UK, Japan and the US:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the ggstatplot library (you will need to run install.packages(\"ggstatsplot\") the first time you use it)\nlibrary(ggstatsplot)\n\n# Create example dataframe\n\ncountry_sci_data <- PISA_2022 %>%\n  select(CNT, PV1SCIE) %>%\n  filter(CNT == \"United Kingdom\" | CNT == \"Japan\" | CNT == \"United States\")\n\n# Use ggstatplot to create an annotated plot with an anova result\n\nggbetweenstats(\n  data  = country_sci_data,\n  x     = CNT,\n  y     = PV1SCIE,\n  title = \"Science scores in the UK, US and Japan\",\n  type  = \"parametric\" # Forces the test to be ANOVA\n)\n```\n\n::: {.cell-output-display}\n![](A6-QandA_files/figure-html/unnamed-chunk-23-1.png){width=95%}\n:::\n:::\n\n\n## How do I turn a data frame into a form I can put into an assignment or paper?\n\nYou can use the `gt` package to convert data frames to aesthetically pleasing outputs.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load the gt package - you will need to run install.packages(\"gt\") the first time\n# install.packages(\"gt\")\nlibrary(gt)\n\n# Make the data frame you want you want to output\nscience_mean_scores <- PISA_2022 %>%\n  group_by(CNT) %>%\n  summarise(mean_science_score = mean(PV1SCIE, na.rm = TRUE),\n            sd_science = sd(PV1SCIE, na.rm =TRUE)) %>%\n  filter(CNT == \"United Kingdom\" | CNT == \"United States\" | CNT == \"Germany\")\n\n# Use gt to produce an output - you can copy and paste the table from the\n# viewer window to your report\n\ngt(science_mean_scores)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"mdkotqmoop\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mdkotqmoop table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mdkotqmoop thead, #mdkotqmoop tbody, #mdkotqmoop tfoot, #mdkotqmoop tr, #mdkotqmoop td, #mdkotqmoop th {\n  border-style: none;\n}\n\n#mdkotqmoop p {\n  margin: 0;\n  padding: 0;\n}\n\n#mdkotqmoop .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mdkotqmoop .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mdkotqmoop .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mdkotqmoop .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mdkotqmoop .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mdkotqmoop .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mdkotqmoop .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mdkotqmoop .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mdkotqmoop .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mdkotqmoop .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mdkotqmoop .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mdkotqmoop .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mdkotqmoop .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mdkotqmoop .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mdkotqmoop .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mdkotqmoop .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mdkotqmoop .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mdkotqmoop .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mdkotqmoop .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mdkotqmoop .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mdkotqmoop .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mdkotqmoop .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mdkotqmoop .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mdkotqmoop .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mdkotqmoop .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mdkotqmoop .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mdkotqmoop .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mdkotqmoop .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mdkotqmoop .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mdkotqmoop .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mdkotqmoop .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mdkotqmoop .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mdkotqmoop .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mdkotqmoop .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mdkotqmoop .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mdkotqmoop .gt_left {\n  text-align: left;\n}\n\n#mdkotqmoop .gt_center {\n  text-align: center;\n}\n\n#mdkotqmoop .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mdkotqmoop .gt_font_normal {\n  font-weight: normal;\n}\n\n#mdkotqmoop .gt_font_bold {\n  font-weight: bold;\n}\n\n#mdkotqmoop .gt_font_italic {\n  font-style: italic;\n}\n\n#mdkotqmoop .gt_super {\n  font-size: 65%;\n}\n\n#mdkotqmoop .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mdkotqmoop .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mdkotqmoop .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mdkotqmoop .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mdkotqmoop .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mdkotqmoop .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mdkotqmoop .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#mdkotqmoop .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#mdkotqmoop div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CNT\">Country code 3-character</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean_science_score\">mean_science_score</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd_science\">sd_science</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Germany</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">495.2547</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">105.4208</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">United Kingdom</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">492.2651</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">102.1538</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">United States</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">498.2506</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">108.8539</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\n# You can see more options on formatting the table here: https://gt.rstudio.com\n# For example to add a heading\n\ngt(science_mean_scores) %>% tab_header(\n    title = \"Mean science scores\",\n    subtitle = \"PISA 2022 data\")\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"bnvldvsavu\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#bnvldvsavu table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#bnvldvsavu thead, #bnvldvsavu tbody, #bnvldvsavu tfoot, #bnvldvsavu tr, #bnvldvsavu td, #bnvldvsavu th {\n  border-style: none;\n}\n\n#bnvldvsavu p {\n  margin: 0;\n  padding: 0;\n}\n\n#bnvldvsavu .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#bnvldvsavu .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#bnvldvsavu .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#bnvldvsavu .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#bnvldvsavu .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bnvldvsavu .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bnvldvsavu .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#bnvldvsavu .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#bnvldvsavu .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#bnvldvsavu .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#bnvldvsavu .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#bnvldvsavu .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#bnvldvsavu .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#bnvldvsavu .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#bnvldvsavu .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#bnvldvsavu .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#bnvldvsavu .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#bnvldvsavu .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#bnvldvsavu .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bnvldvsavu .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#bnvldvsavu .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#bnvldvsavu .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#bnvldvsavu .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bnvldvsavu .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#bnvldvsavu .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#bnvldvsavu .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bnvldvsavu .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bnvldvsavu .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#bnvldvsavu .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bnvldvsavu .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#bnvldvsavu .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#bnvldvsavu .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bnvldvsavu .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bnvldvsavu .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#bnvldvsavu .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#bnvldvsavu .gt_left {\n  text-align: left;\n}\n\n#bnvldvsavu .gt_center {\n  text-align: center;\n}\n\n#bnvldvsavu .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#bnvldvsavu .gt_font_normal {\n  font-weight: normal;\n}\n\n#bnvldvsavu .gt_font_bold {\n  font-weight: bold;\n}\n\n#bnvldvsavu .gt_font_italic {\n  font-style: italic;\n}\n\n#bnvldvsavu .gt_super {\n  font-size: 65%;\n}\n\n#bnvldvsavu .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#bnvldvsavu .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#bnvldvsavu .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#bnvldvsavu .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#bnvldvsavu .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#bnvldvsavu .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#bnvldvsavu .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#bnvldvsavu .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#bnvldvsavu div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\" style>Mean science scores</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>PISA 2022 data</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CNT\">Country code 3-character</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean_science_score\">mean_science_score</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd_science\">sd_science</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Germany</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">495.2547</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">105.4208</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">United Kingdom</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">492.2651</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">102.1538</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">United States</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">498.2506</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">108.8539</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n\n```{.r .cell-code}\n# Or to change the number of decimal places and a column name\n\ngt(science_mean_scores) %>% tab_header(\n  title = \"Mean science scores\",\n  subtitle = \"PISA 2022 data\") %>%\n  fmt_number(columns = c(mean_science_score , sd_science), decimals = 1) %>%\n  cols_label(\"CNT\" = md(\"**Country**\")) # Here the **Country** makes Country bold\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jcvynnrlwg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jcvynnrlwg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jcvynnrlwg thead, #jcvynnrlwg tbody, #jcvynnrlwg tfoot, #jcvynnrlwg tr, #jcvynnrlwg td, #jcvynnrlwg th {\n  border-style: none;\n}\n\n#jcvynnrlwg p {\n  margin: 0;\n  padding: 0;\n}\n\n#jcvynnrlwg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jcvynnrlwg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jcvynnrlwg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jcvynnrlwg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jcvynnrlwg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jcvynnrlwg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jcvynnrlwg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jcvynnrlwg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jcvynnrlwg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jcvynnrlwg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jcvynnrlwg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jcvynnrlwg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jcvynnrlwg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jcvynnrlwg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jcvynnrlwg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jcvynnrlwg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jcvynnrlwg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jcvynnrlwg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jcvynnrlwg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jcvynnrlwg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jcvynnrlwg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jcvynnrlwg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jcvynnrlwg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jcvynnrlwg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jcvynnrlwg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jcvynnrlwg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jcvynnrlwg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jcvynnrlwg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jcvynnrlwg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jcvynnrlwg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jcvynnrlwg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jcvynnrlwg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jcvynnrlwg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jcvynnrlwg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jcvynnrlwg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jcvynnrlwg .gt_left {\n  text-align: left;\n}\n\n#jcvynnrlwg .gt_center {\n  text-align: center;\n}\n\n#jcvynnrlwg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jcvynnrlwg .gt_font_normal {\n  font-weight: normal;\n}\n\n#jcvynnrlwg .gt_font_bold {\n  font-weight: bold;\n}\n\n#jcvynnrlwg .gt_font_italic {\n  font-style: italic;\n}\n\n#jcvynnrlwg .gt_super {\n  font-size: 65%;\n}\n\n#jcvynnrlwg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jcvynnrlwg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jcvynnrlwg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jcvynnrlwg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jcvynnrlwg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jcvynnrlwg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jcvynnrlwg .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jcvynnrlwg .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jcvynnrlwg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_title gt_font_normal\" style>Mean science scores</td>\n    </tr>\n    <tr class=\"gt_heading\">\n      <td colspan=\"3\" class=\"gt_heading gt_subtitle gt_font_normal gt_bottom_border\" style>PISA 2022 data</td>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CNT\"><span data-qmd-base64=\"KipDb3VudHJ5Kio=\"><span class='gt_from_md'><strong>Country</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean_science_score\">mean_science_score</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd_science\">sd_science</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">Germany</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">495.3</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">105.4</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">United Kingdom</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">492.3</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">102.2</td></tr>\n    <tr><td headers=\"CNT\" class=\"gt_row gt_center\">United States</td>\n<td headers=\"mean_science_score\" class=\"gt_row gt_right\">498.3</td>\n<td headers=\"sd_science\" class=\"gt_row gt_right\">108.9</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## If you have an output from a linear model, there is an additional step to do before using gt\n# You need to use the broom package, which has the `tidy` function which gets the output of `lm`\n# Into a suitable format for turing into a table\n# install.packages(\"broom\")\n\nlibrary(broom)\n\n# Create example dataframe\n\nUK_PISA <- PISA_2022 %>%\n  select(PV1SCIE, PV1MATH, CNT) %>%\n  filter(CNT == \"United Kingdom\")\n\n# Run the model\n\nuk_mod <- lm(data = UK_PISA, PV1SCIE ~ PV1MATH)\n\n# tidy the model\n\nuk_mod_tidy <- tidy(uk_mod)\n\n# pass to gt to produce nice output\n\ngt(uk_mod_tidy)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"lnezrbuqyg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#lnezrbuqyg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lnezrbuqyg thead, #lnezrbuqyg tbody, #lnezrbuqyg tfoot, #lnezrbuqyg tr, #lnezrbuqyg td, #lnezrbuqyg th {\n  border-style: none;\n}\n\n#lnezrbuqyg p {\n  margin: 0;\n  padding: 0;\n}\n\n#lnezrbuqyg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lnezrbuqyg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lnezrbuqyg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lnezrbuqyg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lnezrbuqyg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lnezrbuqyg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lnezrbuqyg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lnezrbuqyg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lnezrbuqyg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lnezrbuqyg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lnezrbuqyg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lnezrbuqyg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lnezrbuqyg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lnezrbuqyg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lnezrbuqyg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lnezrbuqyg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lnezrbuqyg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lnezrbuqyg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lnezrbuqyg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lnezrbuqyg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lnezrbuqyg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lnezrbuqyg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lnezrbuqyg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lnezrbuqyg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lnezrbuqyg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lnezrbuqyg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lnezrbuqyg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lnezrbuqyg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lnezrbuqyg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lnezrbuqyg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lnezrbuqyg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lnezrbuqyg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lnezrbuqyg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lnezrbuqyg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lnezrbuqyg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lnezrbuqyg .gt_left {\n  text-align: left;\n}\n\n#lnezrbuqyg .gt_center {\n  text-align: center;\n}\n\n#lnezrbuqyg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lnezrbuqyg .gt_font_normal {\n  font-weight: normal;\n}\n\n#lnezrbuqyg .gt_font_bold {\n  font-weight: bold;\n}\n\n#lnezrbuqyg .gt_font_italic {\n  font-style: italic;\n}\n\n#lnezrbuqyg .gt_super {\n  font-size: 65%;\n}\n\n#lnezrbuqyg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lnezrbuqyg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lnezrbuqyg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lnezrbuqyg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lnezrbuqyg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lnezrbuqyg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lnezrbuqyg .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#lnezrbuqyg .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#lnezrbuqyg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">42.3335278</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">2.304412214</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">18.37064</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">1.978594e-74</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">PV1MATH</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.9324181</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.004685464</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">199.00232</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.000000e+00</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n## How can I change the colours of a plot if I don't want the default colours?\n\nggplot will use a default palette - you can sometimes identify plots in papers as being produced by ggplot from the distinctive green and pink colour! If you want to move away from these, you can use the `scale_fill_manual` and `scale_colour_manual` functions.\n\nFor example, if you have a bar graph of the number of boys and girls in the UK, you can change the fill colours using  `scale_fill_manual` and defining the colours for the categories (in this case `Male` and `Female`).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUK_PISA <- PISA_2022 %>%\n  select(ST004D01T, CNT) %>%\n  filter(CNT == \"United Kingdom\")\n\nggplot(UK_PISA, aes(x = ST004D01T, fill = ST004D01T)) +\n  geom_bar() +\n  scale_fill_manual(values = c(\"Male\" = \"orange\", \"Female\" = \"lightblue\"))  # manually set the values for male and female\n```\n\n::: {.cell-output-display}\n![](A6-QandA_files/figure-html/unnamed-chunk-26-1.png){width=95%}\n:::\n:::\n\nYou need to match the scale manual command to the aesthetic you want to change. For example, when using `geom_point` you use the `colour` aesthetic to change the colour of points. In that case, you use `scale_colour_manual`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nUK_PISA <- PISA_2022 %>%\n  select(ST004D01T, CNT, PV1SCIE, PV1MATH) %>%\n  filter(CNT == \"United Kingdom\")\n\nggplot(UK_PISA, aes(x = PV1MATH, y = PV1SCIE, colour = ST004D01T)) +\n  geom_point(size = 0.1, alpha = 0.6) +\n  scale_colour_manual(values = c(\"Male\" = \"lightgreen\", \"Female\" = \"red\")) # manually set the colour values for male and female\n```\n\n::: {.cell-output-display}\n![](A6-QandA_files/figure-html/unnamed-chunk-27-1.png){width=95%}\n:::\n:::\n\n\n\n",
    "supporting": [
      "A6-QandA_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}