{
  "hash": "ddb54742eaad4e22895299ae7e357478",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"09 Correlation and regression\"\n---\n\n\n::: {.cell}\n\n:::\n\n\n```{=html}\n<!-- Correlation \nhttps://docs.google.com/presentation/d/1QlXhCOaFMRyg8IJ2JczKkpjx26eS9BRi/edit#slide=id.p1-->\n```\n```{=html}\n<!-- Correlation \nhttps://docs.google.com/presentation/d/1QlXhCOaFMRyg8IJ2JczKkpjx26eS9BRi/edit#slide=id.p1\n@mikk2016relationships\n\nDOCTR slides\nhttps://docs.google.com/presentation/d/1j2IhhnBSrg0sM4HuUE5thO0rMLz2W48scylbdPOmAlo/edit#slide=id.p \n-->\n```\n# Pre-reading and pre-session tasks\n## Pre-reading\n## Pre-session task\n\n# Correlation and linear regression\n\nIn this session we will be exploring the use of **linear regression** to describe data and predict results. We will be looking for patterns within the PISA data sets, as well we trying to recreate some of the controversial findings from @stoet2018gender by linking `PISA_2018` data to global gender equality indices using the `left_join` function.\n\nThere are two types of statistics that we can create:\n\n**Descriptive statistics** describe/summarise a data set. E.g. what's the average height of a woman, how many people called George were born in Somerset each year since 1921?\n\n**Inferential statistics** estimate something from a set of data, make generalisations about larger populations. E.g. If I know the height of a woman, can I predict her shoe size? If I meet someone called George, what is the likelihood that they were born in Somerset?\n\nThe first few sessions of this course taught you how to use R to perform descriptive statistics, with you finding the `mean`, `max`, `min` etc of data. Following sessions have given you a range of inferential tools, for example chi-square, t-tests and ANOVA. This session will introduce you to *linear regression* a means by which you can predict the value of a variable based on the value of another variable. Before we can start using linear regression we will introduce you to *correlation*, another type of inferential statistics.\n\n# Correlation\n\nCorrelation gives the direction and strength of the relationship between two numeric variables. For example we might see a relationship between the reading level of a student and their maths results in the UK: the better a student is at reading, typically, the higher their maths grade. Correlation allows us to describe this relation statistically:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"code\"}\ncorr_data <- PISA_2022 %>% \n  filter(CNT == \"United Kingdom\") %>% \n  select(PV1MATH, PV1READ, ST004D01T)\n\ncorr <- cor.test(corr_data$PV1MATH, corr_data$PV1READ, method = \"pearson\")\ncorr_est <- signif(corr[[\"estimate\"]],4)\n\n\nggplot(data = corr_data, aes(PV1MATH, PV1READ)) +\n  geom_point(alpha=0.1) + \n  geom_smooth(method=\"lm\", se = FALSE) +\n  geom_text(label=paste(\"r = \", corr_est), aes(x=700,y=-4.5))\n```\n\n::: {.cell-output-display}\n![](10-Correlation_and_regression_files/figure-html/unnamed-chunk-1-1.png){width=95%}\n:::\n:::\n\n\nThe graph above shows that there is a correlation between Maths score and Reading score. This relationship is a *positive* one, i.e. as the reading level of an individual increases the maths grade is also likely to increase. The strength, *correlation coefficient* (`Pearson's r`) of the relationship between these two numeric fields is 0.7974. The correlation coefficient runs from -1 to +1.\n\n\n::: {.cell}\n\n:::\n\n\n-   If the correlation coefficient (r) is _negative_, i.e. as one factor increase the other declines, the slope of the line of best-fit will be negative. E.g \"The more time you spend running on a treadmill, your body mass decreases\"\n-   If the correlation coefficient (r) is _positive_, i.e. as one factor increase the other increases, the slope of the line of best-fit will be positive. E.g. \"As the temperature increases, more icecreams are purchased.\"\n-   If the correlation coefficient (r) is 0, i.e one factor increasing doesn't impact the other factor, the slope of the line of best-fit will be flat. E.g. \"the number of trees in a city has no relation to the number of chocolate bars purchased by children\"\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-Correlation_and_regression_files/figure-html/unnamed-chunk-3-1.png){width=95%}\n:::\n:::\n\n\nTo run the correlation test in R we use the `cor.test` function:\n\n`cor.test(<vector1>, <vector2>, method = \"pearson\")`\n\nFor our data we will be using the `PV1MATH` and `PV1READ` columns.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(corr_data$PV1MATH, corr_data$PV1READ, method = \"pearson\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  corr_data$PV1MATH and corr_data$PV1READ\nt = 150.47, df = 12970, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.7909995 0.8035376\nsample estimates:\n      cor \n0.7973546 \n```\n\n\n:::\n:::\n\n\n-   `df` the number of ways that the data can vary, the larger this number the more ways the data could have been different\n-   `p-value` significance of the result, we can dismiss the null-hypothesis that there isn't a relationship between maths score and wealth as the p-value is less than `0.05`\n-   `sample estimates` the strength of the relationship between the factors\n-   `confidence intervals` the upper and lower limit of where the correlation coefficient is likely to lie, with 95% confidence.\n\n::: callout-note\nDegrees of freedom (`df`)\n\nTwo individuals from different countries might have a weight difference of 5 kg. So what?! But if *average* weights between *whole* populations of countries vary by 5 kg then this becomes much more interesting.\n\nRoughly: The number of independent values that can vary without questioning the significance of the model. So the more `df` you have, the safer your model. Degrees of freedom can be calculated by looking at the number of values that can vary, often this is the number of observations that you have minus one -- if you had just one element it wouldn't be able to vary against anything else.\n:::\n\n## Other correlation-coefficients\n\nWhen looking for correlations in data that is *non-parametric*, i.e. not normally distributed you could use *Spearman's rank order correlation-coefficient (rho ρ)* rather than *Pearson's r*. `cor.test(... method = \"...\")` allows you to specify the `method` used for correlation, you can set this to Spearman's rho by writing `method = \"spearman\"`\n\nData will need to contain continuous or ordinal variables. The Spearman correlation coefficient is based on the *ranked* values for each variable rather than the raw data. The Spearman correlation between two variables is equal to the Pearson correlation between the rank values of those two variables.\n\nWe want to look at the correlation between students self-efficacy in digital competencies  (`ICTEFFIC`) and wealth (`HOMEPOS`) for students in the the UK. To make the data set manageable, let us examine girls whose mother or father is a software developer\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# create a data set for the UK, including the HOMEPOS and ICTEFFIC variables\nsub_data <- PISA_2022 %>% \n              select(CNT, HOMEPOS, ICTEFFIC, ST004D01T, OCOD1, OCOD2) %>%\n              filter(CNT == \"United Kingdom\") %>%\n              filter(ST004D01T == \"Female\") %>%\n              filter(OCOD1 == \"Software developers\" | OCOD2 == \"Software developers\")\n```\n:::\n\n\nIt is unclear if `ICTEFFIC`, self-efficacy in digital competencies, is _normalised_. We can graph it with `geom_density` to find out:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sub_data) + \n  geom_density(aes(x=ICTEFFIC))\n```\n\n::: {.cell-output-display}\n![](10-Correlation_and_regression_files/figure-html/unnamed-chunk-6-1.png){width=95%}\n:::\n:::\n\n\nThe data doesn't look very normal.\n\nWe can run the *Shapiro-Wilk Test* to check for the the normality of the data, any alpha value greater than `0.05` means we can assume that the data is normally distributed.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(sub_data$ICTEFFIC)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  sub_data$ICTEFFIC\nW = 0.85272, p-value = 0.0001823\n```\n\n\n:::\n:::\n\n\nIn this case the data *isn't* normally distributed as `p < 0.05` and we need to use a non-parametric correlation test. We need to run *Spearman* rather than *Pearson*:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(sub_data$HOMEPOS, sub_data$ICTEFFIC, method = \"spearman\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tSpearman's rank correlation rho\n\ndata:  sub_data$HOMEPOS and sub_data$ICTEFFIC\nS = 9301.1, p-value = 0.5459\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n       rho \n-0.1025489 \n```\n\n\n:::\n:::\n\n\nThe result shows no significant correlation (`p=0.5459`) between wealth and IT self-efficacy for girls who home at least one parent who is a software developer\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n## Checking the assumptions of the model\n\nFor you to conduct the correct correlation test you need to be sure that the data meet several criteria. First, as noted above, the data should be _normally distributed_ for a pearson test to be conducted. You can check the __normality__ of the data using the `shapiro.test` function and/or by graphing the data. For large data sets such as PISA (n > 5,000), the `shapiro.test` won't work and you might want to use the graph to check; alternatively you can also use the *central limit theorem*, which means that when you have a sufficiently large sample you can presume that the data is normally distributed [@field2012discovering]. As a rule of thumb *\"30 is the magic number\"*, and any samples you are studying with 30 or more data items can be treated as parametric, e.g. you could use _pearson_ when running correlation analysis on 30 or more items. This is a rough rule of thumb and you should always check the normality of your data before when checking and presenting any result any tests.\n\nYou also need to expect a _linear relationship_ between the two variables. For example, if you were to plot the data and it looked like a curve, you might want to use a different test. You can use the `ggplot` function to plot the data and see if it looks linear. The graph below shows data that doesn't appear to be linearly related.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-Correlation_and_regression_files/figure-html/unnamed-chunk-11-1.png){width=95%}\n:::\n:::\n\n\nThe data should be of paired observations. If you have missing data in one of the variables you should remove the missing data from the other variable using `na.omit()` e.g.:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPISA_2015 <- PISA_2015 %>% select(PV1MATH, PV1SCIE) %>% na.omit()\n```\n:::\n\n\nWhen dealing with non-parametric and small data sets you can also use **Kendall's Tau** i.e. `cor.test(... method = \"kendall\")`\n\n## Reporting correlations\n\nTo interpret the correlation co-efficient of a model we can use the following table:\n\n| Correlation co-efficient | Relationship         |\n|--------------------------|----------------------|\n| .70 or higher            | very strong positive |\n| .40 to .69               | strong positive      |\n| .30 to .39               | moderate positive    |\n| .20 to .29               | weak positive        |\n| .01 to .19               | negligible or none   |\n| 0                        | no relationship      |\n| -.01 to -.19             | negligible or none   |\n| -.20 to -.29             | weak negative        |\n| -.30 to -.39             | moderate negative    |\n| -.40 to -.69             | strong negative      |\n| -.70 or higher           | very strong negative |\n\nWhen writing a report we might present our findings like this:\n\n> There was no significant relationship between the perceived quality of sleep and its impact on Mood, *r* = -.12, *p* = .17\n\nor\n\n> There is a significant very strong correlation between overall well-being and life satisfaction, *r* = .86, *p* = .00\n\n## Questions: Correlation\n\n::: question\nUse `cor.test` to explore the following relationships:\n\n1.  `PV1MATH` to `PV1SCIE`, is this a stronger relationship than that between Maths and Reading? Why might they be different?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\ncor.test(PISA_2022$PV1MATH, PISA_2022$PV1SCIE, method = \"pearson\")\n#> cor 0.8888601\n\ncor.test(PISA_2022$PV1MATH, PISA_2022$PV1READ, method = \"pearson\")\n#> cor 0.8312513\n\n#> very slightly, yes!\n```\n:::\n\n\n2.  How does the correlation of wealth `HOMEPOS` of females `ST004D01T` and their Reading `PV1READ` scores compare to males? Why might they be different?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\ndata <- PISA_2022 %>% filter(ST004D01T == \"Female\")\ncor.test(data$HOMEPOS, data$PV1READ, method = \"pearson\")\n#> 0.4972371 \n\ndata <- PISA_2022 %>% filter(ST004D01T == \"Male\")\ncor.test(data$HOMEPOS, data$PV1READ, method = \"pearson\")\n#> cor 0.4216684 \n```\n:::\n\n\n3.  How does life satisfaction `ST016Q01NA` correlate with the science score of students?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\ncor.test(PISA_2022$ST016Q01NA, PISA_2022$PV1SCIE, method = \"pearson\")\n#> -0.06439345\n#> there is negligible or no correlation between these variables\n```\n:::\n\n\n4. How does parental involvement in education `PARINVOL` correlate with reading outcomes for students in Germany (__HINT:__ you might want to check the normality of this data!):\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\nmdl_data <- PISA_2022 %>%\n  mutate(gender = ST004D01T) %>%\n  filter(!is.na(PARINVOL),\n         CNT == \"Germany\") %>%\n  select(CNT, gender, PARINVOL, PV1READ)\n\nshapiro.test(mdl_data$PARINVOL)\n#> not normally distributed!\n#> W = 0.96017, p-value < 2.2e-16\nggplot(mdl_data) + \n  geom_density(aes(x=PARINVOL))\n\nshapiro.test(mdl_data$PV1READ)\n#> not normally distributed!\n#W = 0.99362, p-value = 4.224e-08\nggplot(mdl_data) + \n  geom_density(aes(x=PV1READ))\n\n#> as the data isn't normally distributed we need to use a non-parametric test, i.e. spearman's rho\ncor.test(mdl_data$PARINVOL, mdl_data$PV1READ, method = \"spearman\")\n#> p-value < 2.2e-16\n#> rho -0.2962208\n\n# or as a graph\nggplot(mdl_data, aes(x=PARINVOL, y=PV1READ)) + \n  geom_point() +\n  geom_smooth(method=\"lm\")\n```\n:::\n\n\n5. Using the _full_ [PISA data set](https://emckclac-my.sharepoint.com/:u:/g/personal/k1926273_kcl_ac_uk/EQwPwPa-bzBFp1ne6LlrT0MBSh_q-YSKzFb2Jp8ybcwztQ?e=cNcFNw), for the `United Kingdom` How does the sense of belonging to school `BELONG` correlate with the item that measures bullying `BULLIED`? How does the UK compare against other countries?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\ndata <- PISA_2022 %>% filter(CNT == \"United Kingdom\")\ncor.test(data$BELONG, data$BULLIED, method = \"pearson\")\n#> -0.3797393\n#> there is a moderate negative correlation between these variables,\n#> students who are bullied less have a greater sense of belonging\t\t\t\t\t\t\t\t\t\t\t\t  \n```\n:::\n\n\n:::\n\n::: callout-tip\nIf you want to find all the `numeric` fields, i.e. the fields that you can easily run correlation calculations on, use the following code to list them:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPISA_2022 %>% select(where(is.numeric)) %>% names()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"CNTSCHID\"   \"CNTSTUID\"   \"ST016Q01NA\" \"WB151Q01HA\" \"WB152Q01HA\"\n [6] \"WB156Q01HA\" \"BELONG\"     \"BULLIED\"    \"DISCLIM\"    \"HOMEPOS\"   \n[11] \"ESCS\"       \"ATTCONFM\"   \"ICTEFFIC\"   \"STUBMI\"     \"PQMIMP\"    \n[16] \"PARINVOL\"   \"W_FSTUWT\"   \"PV1MATH\"    \"PV1READ\"    \"PV1SCIE\"   \n```\n\n\n:::\n:::\n\n:::\n\n\n# Regression\n\nCorrelation allows us to see the strength of the relationship but it doesn't allow us to *predict* what would happen if a variable changed. \"When the wind blows, the trees move. When the trees move, the wind blows.\" Which is it? Correlation suggests there is a link but tells us nothing about causation. To do this we need *regression*.\n\n| Correlation                                                                             | Regression                                                                            |\n|-----------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------|\n| an example of inferential statistics                                                    | an example of inferential statistics                                                  |\n| give direction and strength of the relationship between two (or more) numeric variables | give direction and strength of the relationship between two (or more) variables       |\n| Relationship between variables                                                          | The extent to which one variable [predicts]{.underline} another                       |\n| Effect only (no cause)                                                                  | Cause and effect                                                                      |\n| p(x,y) == p(y,x)                                                                        | One way (e.g. education affects income differently from how income affects education) |\n| Single point/value                                                                      | An equation that creates a best fitting line                                          |\n\n: differences and similarities between correlation and regression\n\nRegression is a way of *predicting* the value of one *dependent* variable from one or more *independent* variables by creating a hypothetical model of the relationship between them.\n\n-   **independent variable(s)** - the cause of the change that is independent of other variables\n-   **dependent variable** - the effect of the cause\n\nFor example we could have a model that predicts the value of a house - the _dependent_ variable - based on the number of bedrooms, the size of the garden, and the distance from the city centre - the _independent_ variables.\n\nFor regression to work we need to have a large enough sample size, the means to explain any relationships, and relationships that are not spurious, i.e. that it is not due to third variables. For example....\n\n## Linear models and regression\n\nThe model used is a **linear** one, therefore, we describe the relationship using the equation of a straight line. In linear regression, with one dependent and one independent variable, we use the *Method of Least Squares* to find the line of best fit. The means finding a straight line that passes as close as possible to all the points. The distance between a point and this line is called a _residual_. The line of best fit is the line where the sum of the residuals squared is the smallest number possible.\n\n![Method of Least Squares](../images/method_of_least_squares.png)\n\nThe line that is created can be described by the equation:\n\n`Output = Intercept + Coefficient * Input` <!--F-statistic = a measure of the ratio of the variation explained by the model and the variation attributable to unsystematic factors (the error of the model).-->\n\nLet's use linear regression to explore the relationship between the score in maths(`PV1MATH`) and the score in reading (`PV1READ`). To build this model we use the `lm` command:\n\n`lm(<dependent_var> ~ <independent_var> , data=<dataframe>)`\n\nThe first part defines the model we are going to explore, listing the dependent variable and separating it from the independent variable\\[s\\] with a tilde `~`. You can specify multiple independent variables by adding more plusses, but for the example here we are only going to use one. Once the model has been built we can feed it into the `summary(<mdl>)` command to output the results:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmdl_math_read <- lm(PV1MATH ~ PV1READ, data=PISA_2022)\nsummary(mdl_math_read)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = PV1MATH ~ PV1READ, data = PISA_2022)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-273.61  -38.33   -2.48   36.01  323.51 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 1.021e+02  2.981e-01   342.5   <2e-16 ***\nPV1READ     7.731e-01  6.599e-04  1171.5   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 56.61 on 613742 degrees of freedom\nMultiple R-squared:  0.691,\tAdjusted R-squared:  0.691 \nF-statistic: 1.372e+06 on 1 and 613742 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nIf you look at the `Coefficents:` table we can see that `PV1READ` is significant in explaining the outcome of the model as the p-value `Pr(>|t|)` is less than 0.001 `<2e-16 ***`. The null hypothesis is that one variable does not predict another, we can dismiss this. By looking at the `Estimate` we can also see by how much a `PV1MATH` grade would increase if the `PV1READ` increased by one: `0.7731`. Additionally, we have *R^2^* value of `0.691`, this suggests that the model is very good at explaining the value of the dependent variable, 69.1% of the variance in the `PV1MATH` grade is explained by the `PV1READ` grade.\n\n## R squared\n\nWith large data sets you will often find a statistically significant difference, but *p-values* should be read with caution as the larger the data set you use the more likely you are to get a low *p-value*. The actual magnitude of a significant difference might be very small. **r-squared** and **adjusted r-squared** are ways for you to report on the magnitude of a significant difference and when you report the findings from a linear model you should be looking at the `p` and the `R^2^` values. You have already met *R*, this is the correlation coefficient from earlier, *R^2^* is this value squared:\n\n-   **R** - The correlation between the observed values of the outcome, and the values predicted by the model.\n-   **R^2^** - The proportion of variance in the dependent variable accounted for by the model.\n-   **Adj. R^2^** - An estimate of R^2^ in the population (shrinkage), often very similar to plain R^2^.\n\n<!--Effect size measurements include Cohen's d, Glass' g and Pearson's r-->\n\nImagine we take two experiments a) and b)\n\n![(a) larger effect-size; (b) smaller effect-size from @coe2002s](images/effectsize.png)\n\nBoth have statistically significant results, but it's clear that the impact of the intervention in graph a) is larger as there is less overlap between the curves, i.e. there is more difference between the the outcomes.\n\n> if the difference were as in graph (a) it would be very significant; in graph (b), on the other hand, the difference might hardly be noticeable [@coe2002s p2]\n\nDifferent effect sizes have different meanings and there is some debate on how to interpret them, with different interpretations for different fields of research [@schafer2019meaningfulness]\n\n| Effect size value | Effect size |\n|-------------------|-------------|\n| 0.0 to 0.19       | negligible  |\n| 0.2 to 0.49       | small       |\n| 0.5 to 0.79       | medium      |\n| 0.8+              | large       |\n\n: How to interpret effect sizes [@cohen1962statistical]\n\nHowever, acceptable effect sizes in social sciences - including education - are often very low. You might be familiar with the Education Endowment Foundation's *Teaching and Learning Toolkit* which outlines the *Impact* of different interventions on student learning. For example, repeating a year is seen to decrease student progress by 3 months and providing students with feedback is seen to increase student progress by 6 months. Behind the scenes they are using effect-sizes to predict the impact of educational interventions. In their model an effect-size of 0.1 is considered to have \"Low impact\", but also an effect size of this magnitude is translated to 2 months progress in the Toolkit [@higgins2016sutton p.5].\n\n## Questions: Regression\n\n::: question\n1. Run a regression model to look at how wealth `HOMEPOS` influences Maths grades in Kazakhstan What is the impact of increasing the wealth of students by one unit? How does this model compare against the same model for science and reading scores?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\nmdl <- lm(PV1MATH ~ HOMEPOS, \n          data=PISA_2022 %>% filter(CNT==\"Kazakhstan\"))\nsummary(mdl)\n#> HOMEPOS    33.432 \n#> R-squared:  0.1018\n\nmdl <- lm(PV1READ ~ HOMEPOS, \n          data=PISA_2022 %>% filter(CNT==\"Kazakhstan\"))\nsummary(mdl)\n#> HOMEPOS    37.1606 \n#> R-squared:  0.1258\n\nmdl <- lm(PV1SCIE ~ HOMEPOS, \n          data=PISA_2022 %>% filter(CNT==\"Kazakhstan\"))\nsummary(mdl)\n#> HOMEPOS    33.5009\n#> R-squared:  0.1089\n```\n:::\n\n\n2.  Run a regression model to look at how science grades predict Maths outcomes in UK students. How does this compare to students in France?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\nmdl <- lm(PV1MATH ~ PV1SCIE, \n          data=PISA_2022 %>% filter(CNT==\"United Kingdom\"))\nsummary(mdl)\n#> Estimate = 0.80789\n#> p<0.001\n#> R2 = 0.7533\n\nmdl <- lm(PV1MATH ~ PV1SCIE, \n          data=PISA_2022 %>% filter(CNT==\"France\"))\nsummary(mdl)\n#> Estimate = 0.793547\n#> p<0.001\n#> R2 = 0.8012\n\n#> both models are significant, but the model in France has a higher R squared \n#> value, i.e. Science is a better at explaining the variance in maths outcomes \n#> in France than it is in the UK.\n```\n:::\n\n\n3.  Create a linear model to look at parental involvement `PARINVOL` influences Maths grades for female students in Germany and Hong Kong (China). If we use the Education Endowment Foundation's interpretation of effect sizes [@higgins2016sutton p.4] what is the impact of increasing parental involvement on student grades in each country?\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\nmdl <- lm(PV1MATH ~ PARINVOL, \n          data=PISA_2022 %>% filter(ST004D01T==\"Female\",\n                                    CNT==\"Germany\"))\nsummary(mdl)\n#> Estimate = -41.864\n#> p<0.001\n#> R2 = 0.1289\n#> this is just above 0.1, meaning the model has a \"Low impact\" effect size \n#> if we use the Education Endowment Foundation's interpretation of effect sizes\n#> However, increased parental involvement decreases Maths scores!?\n\nmdl <- lm(PV1MATH ~ PARINVOL, \n          data=PISA_2022 %>% filter(ST004D01T==\"Female\",\n                                    CNT==\"Hong Kong (China)\"))\nsummary(mdl)\n\n#> Estimate = -4.614\n#> p<0.001\n#> R2 = 0.001756\n#> Parental involvement has a negligible effect on Maths scores in Hong Kong\n```\n:::\n\n\n4. Is it reasonable to presume that using 5 interventions from the education endowment foundation toolkit, each with effect-sizes of 0.1, i.e. 2 months improvement, will increase the progress for the average student in your class by 10 months (5 \\* 2)?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\n#> Probably not! The effect of the interventions might not be additive, and the \n#> effect of the interventions might not be the same for all students.\n```\n:::\n\n:::\n\n# Multivariable linear regression\n\nSo far we have looked at the impact of a single independent variable on a single dependent variable. We are now going to look at building models that contain multiple independent variables, of both continuous and discrete values. For example, we might want to see how Gender (`ST004D01T`) and Reading score (`PV1READ`) help predict a maths score. To add extra independent variables, use the plus symbol `+`:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmdl <- lm(PV1MATH ~ PV1READ + gender, \n          data = PISA_2022 %>% rename(gender = ST004D01T))\nsummary(mdl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = PV1MATH ~ PV1READ + gender, data = PISA_2022 %>% \n    rename(gender = ST004D01T))\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-289.474  -37.253   -2.099   35.295  309.126 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 8.363e+01  3.086e-01   271.0   <2e-16 ***\nPV1READ     7.863e-01  6.478e-04  1213.8   <2e-16 ***\ngenderMale  2.528e+01  1.419e-01   178.2   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 55.2 on 613662 degrees of freedom\n  (79 observations deleted due to missingness)\nMultiple R-squared:  0.7062,\tAdjusted R-squared:  0.7062 \nF-statistic: 7.375e+05 on 2 and 613662 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nBoth independent variables are significant (`p<0.001`), and the *R^2^* of the model is high at `0.7062`, this model explains 71% of the variance in Maths grade. Looking at the Estimates, we see both independent variables presented, this means we can read them as if the other factor has been *controlled* for; e.g. what is the impact of reading score if the impact of gender has been taken into consideration. `PV1READ` is `0.786`, meaning for an increase of 1 in this score, the `PV1MATH` grade would increase by `0.786`. Gender is different, this is a *nominal* field, being either Male or Female, and `genderMale` is shown in the coefficients table. This means that the model has taken `gender == Female` as the base state, and modeled what happens if the gender were to change to Male. Interestingly, it suggests that when controlling for the reading grade, e.g. comparing females and males of the same reading score, males would do `25.28` points better in their `PV1MATH` grade than females(!). We'll be exploring these gender differences a little further in section @sec-Stoet-Geary.\n\n::: callout-tip\n\nPicking variables for your regression model can be difficult. You might have a large number of potential predictors and you might not know which ones to include. Some predictors might also be correlated with each other, and this can cause problems in your model. For example, if you were to include the number of cars in a student's household and the income of the family, these two variables might be highly correlated, as it seems likely richer families will have more cars. This is known as *multicollinearity* and can cause problems in your model, such as lower p values and larger standard errors.\n\nThere are a few methods to help you decide which variables to include in your model:\n\nA rule of thumb is you need try to use predictors that you think make sense in explaining your model, variables that have some theoretical rationale behind their inclusion. You don't want to have a wonderful model that when you come to write-up, you can't explain; plus variables that make sense stand a good chance of being good predictors. For example, if you are trying to predict a student's Mathematics score, you might want to include the student's reading grade, along with their gender and their socio-economic status. You can find literature on all of these variables and could happily explain why you think they might be good predictors.\n\nNext you can use _stepwise_ selection to help you decide which variables to include in your model, by either starting with no variables and keep adding them to get the highest explanatory power of the model, or start with all the variables and remove them one by one until you get a model with the highest explanatory power (roughly the highest adj.R^2^). The `{{MASS}}` package comes with code to run the `AIC` (Akaike Information Criterion) stepwise process to help you do this. AIC is a measure of how well your model fits the data, but it also includes a penalty for the number of variables you use. This means that AIC will help you find the best model that uses the fewest variables. To use the AIC process, create a data frame with all the variables that you want to use and use `na.omit` to make sure that you have complete rows of data (warning, the more variables you use the slower this process will be):\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPISA_2022 %>% select(where(is.numeric)) %>% names()\nmdl_data <- PISA_2022 %>% \n  select(PV1MATH, PV1READ, PV1SCIE, ST004D01T,\n         ESCS, HOMEPOS, OECD, ST253Q01JA,\n         ICTEFFIC, STUBMI, PQMIMP, PARINVOL) %>% \n  na.omit()\n```\n:::\n\n\nThen use the `AIC` (Akaike Information Criterion) function to find the best model, to do this. Create a linear model using `lm`, with the model description `PV1MATH ~ .`, where `.` stands for _everything_, i.e. every other column in the `mdl_data` data frame. We then pass the `lm()` result to `stepAIC` to find the best model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS)\nmdl <- lm(PV1MATH ~ ., data = mdl_data)\nstepAIC(mdl, trace = TRUE, direction= \"both\")\n```\n:::\n\n\n> Call:\n> lm(formula = PV1MATH ~ PV1READ + PV1SCIE + ST004D01T + ESCS + \n>    HOMEPOS + OECD + ST253Q01JA + ICTEFFIC + STUBMI, data = mdl_data)\nIn this case _Parent Attitudes Toward Mathematics (WLE)_ `PQMIMP` and _Parental Involvement (WLE)_ `PARINVOL` were not seen to be contributing enough to the model to be included(?!).\n\n:::\n\n## Checking the assumptions of the model\n\nLike the other statistical models you have met so far, linear regression has a number of assumptions that need to be met for the model to be valid. These are:\n\n- **Independence**: The residuals should be independent of each other, i.e. the residuals from one observation should not predict the residuals from another observation, there shouldn't be patterns in the residuals. We can test the independence of the residuals using the _Durbin Watson_ test from the `{{car}}` package. Where p-values of < 0.05 indicate that the residuals are _not_ independent.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\nmdl <- lm(PV1READ ~ PV1MATH + ST004D01T + ESCS, \n          data = PISA_2022 %>% filter(CNT == \"United Kingdom\"))\ndurbinWatsonTest(mdl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n lag Autocorrelation D-W Statistic p-value\n   1     0.002082558      1.995719   0.828\n Alternative hypothesis: rho != 0\n```\n\n\n:::\n:::\n\n\nIn this test, we can see that the p-value is > 0.05 meaning we can assume that the residuals _are_ independent.\n\n- **No multicollinearity**: The independent variables should not be correlated with each other, e.g. having `PV1MATH` and `PV1SCIE` in a model, which are highly correlated, might make it difficult to work out which of the scores is having the impact. You might be able to alleviate this issue by creating a composite variable: `composite_score = (PV1MATH + PV1SCIE) / 2` and using this in your model instead. @field2012discovering suggest that if the correlation between two variables is \"above 0.80 or 0.90\" (p.276), then you might have a problem with multicollinearity, the actual correlation between these two fields is 0.89. More advanced checks can use the `vif()` function from the `{{car}}` package to check for multicollinearity. This function will calculate the _Variance Inflation Factor_ (VIF) for each variable in the model. A VIF of 1 means that the variable is not correlated with any other variables, and a VIF of 5 or more means that the variable is highly correlated with other variables.(ibid. p293)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(car)\nmdl <- lm(PV1READ ~ PV1MATH + PV1SCIE + ST004D01T, \n          data = PISA_2022 %>% filter(CNT == \"United Kingdom\"))\n# They are close to 5, consider removing one of the PV1 variables or combining them\nvif(mdl) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  PV1MATH   PV1SCIE ST004D01T \n 4.082640  4.066330  1.008424 \n```\n\n\n:::\n:::\n\n\n- **Normality**: The residuals should be normally distributed. To check this we can use _Q-Q plots_. The _Shapiro-Wilk_ test is also used for smaller data sets where there are n < 5000 observations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmdl <- lm(PV1READ ~ PV1MATH + PV1SCIE + ST004D01T, \n          data = PISA_2022 %>% \n            filter(CNT == \"United Kingdom\"))\npar(mfrow = c(2, 2))\nplot(mdl)\n```\n\n::: {.cell-output-display}\n![](10-Correlation_and_regression_files/figure-html/unnamed-chunk-30-1.png){width=95%}\n:::\n:::\n\n\nThere is some deviation from the red line in the Q-Q Residuals plot, but the residuals are close to the line within the x-axis `[-2,2]` range and we can assume the data is normally distributed with some confidence.\n\n- **Homoscedasticity**: The residuals (the difference between the observed and predicted values) should be equal across all values of the independent variables. This means that the variance of the residuals should be constant. You can use `ols_plot_resid_fit` from the `{{olsrr}}` package to check for the normality and homoscedasticity of the model. The data points should be spread randomly, with no funneling from one end to another:\n\n<!-- from: https://bookdown.org/jimr1603/Intermediate_R_-_R_for_Survey_Analysis/testing-regression-assumptions.html \n\nhttps://stats.stackexchange.com/questions/642992/trust-the-graphs-or-go-with-breusch-pagan-and-whites-tests-for-homoscedasticity?noredirect=1#comment1201800_642992\n\n# studentized residuals\n#ols_plot_resid_stud(mdl)\n#ols_plot_resid_stand(mdl)\nstud_resids <- studres(mdl)\nggplot(data=data.frame(x=PISA_2022 %>% \n                         filter(!is.na(ST004D01T)) %>% \n                         pull(PV1READ),\n                       y=studres(mdl)),\n       aes(x=x, y=y)) +\n  geom_point() +\n  geom_smooth(method = \"lm\") +\n  ylab('Studentized Residuals') +\n  xlab('Displacement')\n  \n\nplot(PISA_2022 %>% filter(!is.na(ST004D01T)) %>% pull(PV1READ),\n     stud_resids,  ylab='Studentized Residuals', xlab='Displacement') \nabline(0, 0)\nsum(abs(stud_resids)>2)/\nlength(stud_resids)\n\n-->\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(olsrr)\nmdl <- lm(PV1READ ~ PV1MATH + PV1SCIE + ST004D01T, \n          data = PISA_2022 %>% filter(CNT == \"United Kingdom\"))\n\nols_plot_resid_fit(mdl)\n```\n\n::: {.cell-output-display}\n![](10-Correlation_and_regression_files/figure-html/unnamed-chunk-31-1.png){width=95%}\n:::\n:::\n\n\nThese plots looks good for a random distribution of residuals, but we can add to our analysis by using the _Breusch-Pagan_ test - `ols_test_breusch_pagan()` in the `{{olsrr}}` package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(olsrr)\nmdl <- lm(PV1READ ~ PV1MATH + PV1SCIE + ST004D01T, \n          data = PISA_2022 %>% filter(CNT == \"United Kingdom\"))\n\nols_test_breusch_pagan(mdl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Breusch Pagan Test for Heteroskedasticity\n -----------------------------------------\n Ho: the variance is constant            \n Ha: the variance is not constant        \n\n               Data                 \n -----------------------------------\n Response : PV1READ \n Variables: fitted values of PV1READ \n\n         Test Summary           \n -------------------------------\n DF            =    1 \n Chi2          =    47.53604 \n Prob > Chi2   =    5.400197e-12 \n```\n\n\n:::\n:::\n\n\nThe result here of p<0.05 suggests that there is a degree of _heteroscedasticity_ in the model, for example, we might find that students with high reading scores do relatively badly at maths, when compared to those with lower reading scores, this looks marginally true:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](10-Correlation_and_regression_files/figure-html/unnamed-chunk-33-1.png){width=95%}\n:::\n:::\n\n\nHowever, the _Breusch-Pagan_ test does appear to be at odds with the graphs above and it is the case that with large data sets (PISA is _huge_) many of these model significance tests can overstate the issue, i.e. they report significance when the actual actual effect on the model is very small. A good way of thinking about this is the story of _The Princess and the Pea_, however many mattresses were placed underneath the princess, she could still feel the pea at the bottom of the pile of mattresses. For everyone else the pea wasn't important at all, when they saw how many mattresses there were [@dave2023cv]. The mattresses are our data samples, and the princess is our _Breusch-Pagan_ test complaining about something that actually isn't that important given the large data set we are using. The graphs look fine and we can assume that homoscedasticity is not a problem in our model. Good graphs can often overrule the output of model tests if the data set is large enough [@schmidt2018linear].\n\n\n::: {.cell}\n\n:::\n\n\nNot meeting all of the assumptions needed for linear models doesn't mean we can't report the linear model results, but we should make note of the assumptions that we have checked and the results of these checks to help readers better understand the limitations of the analysis and the robustness of the results. Additionally, we might want to:\n\n- _log-transform_ the outcome variable if you think the relationship might be logarithmic, or apply _square root_ or _cube root_ transforms\n- combine the two PV score predictors into one to avoid the potential multi-collinearity,\n- focus on particular countries rather than the whole data set, or \n- split our data so we only look at high, medium or low performing students only. \n<!--- use weighted regression-->\n\nOther types of regression, such as _multilevel_ models might be able to help you get past these issues as it will allow you to run multiple models on different subsets of the data. \n\n::: callout-tip\nTo find out more about the assumptions when using linear models, please see @field2012discovering and a great [book](https://sscc.wisc.edu/sscc/pubs/RegDiag-R/index.html) by the University of Wisconsin\n\nYou might also want to utilise the `{{easystats}}` package which will help you check the assumptions of your model using the `check_model()` command\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(easystats)\n\nmdl <- lm(PV1READ ~ PV1SCIE + ST004D01T, \n          data = PISA_2022 %>% filter(CNT == \"United Kingdom\"))\n\ncheck_model(mdl)\n```\n\n::: {.cell-output-display}\n![](10-Correlation_and_regression_files/figure-html/unnamed-chunk-35-1.png){width=95%}\n:::\n:::\n\n\n:::\n\n<!--\nR has a package to help you check the validity of your models: _{{gvlma}}_ Global Validation of Linear Models Assumptions. This package will check the assumptions of the model, such as the normality of the residuals, the linearity of the model, and the homoscedasticity of the residuals. To use this package, you need to install it first, then run the `gvlma()` function on your model:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = PV1READ ~ PV1SCIE, data = PISA_2022)\n\nCoefficients:\n(Intercept)      PV1SCIE  \n    45.8447       0.8711  \n\n\nASSESSMENT OF THE LINEAR MODEL ASSUMPTIONS\nUSING THE GLOBAL TEST ON 4 DEGREES-OF-FREEDOM:\nLevel of Significance =  0.05 \n\nCall:\n gvlma(x = mdl) \n\n                       Value p-value                   Decision\nGlobal Stat        3352.0529  0.0000 Assumptions NOT satisfied!\nSkewness              0.1649  0.6847    Assumptions acceptable.\nKurtosis           3217.4103  0.0000 Assumptions NOT satisfied!\nLink Function       133.7435  0.0000 Assumptions NOT satisfied!\nHeteroscedasticity    0.7341  0.3916    Assumptions acceptable.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](10-Correlation_and_regression_files/figure-html/unnamed-chunk-36-1.png){width=95%}\n:::\n:::\n\n\nIt is necessary to complete these tests when putting together models. With these tests, some of the results above might be called into question!\n-->\n\n## Reporting regression\n\nWhen reporting linear regression we should make note of the *estimate* (also known as beta *β-value*) of each factor along with their *p-values*. We need to know the *R^2^* and *p-value* for the model as well as the *F-statistic* and the *degrees of freedom*. We can then construct a few sentences to explain our findings [@statology2021]:\n\n> Simple linear regression was used to test if \\[predictor variable\\] significantly predicted \\[response variable\\]. The overall regression was statistically significant (R2 = \\[R2 value\\], F(df regression, df residual) = \\[F-value\\], p = \\[p-value\\]). It was found that \\[predictor variable\\] significantly predicted \\[response variable\\] (β = \\[β-value\\], p = \\[p-value\\]).\n\nFor the example above, this would be:\n\n> Simple linear regression was used to test if a student reading grade significantly predicted student maths grade. The overall regression was statistically significant (R^2^ = 0.7062, F(1,613662) = 737500, p = \\<0.001). It was found that reading grade significantly predicted maths grade (β = 0.7863, p = \\<0.001).\n\nAlternatively, you could make use of the `easystats` package which will do most of the heavy lifting for you:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(easystats)\nmdl <- lm(PV1MATH ~ PV1READ, data=PISA_2022)\nsummary(mdl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = PV1MATH ~ PV1READ, data = PISA_2022)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-273.61  -38.33   -2.48   36.01  323.51 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 1.021e+02  2.981e-01   342.5   <2e-16 ***\nPV1READ     7.731e-01  6.599e-04  1171.5   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 56.61 on 613742 degrees of freedom\nMultiple R-squared:  0.691,\tAdjusted R-squared:  0.691 \nF-statistic: 1.372e+06 on 1 and 613742 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nreport(mdl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWe fitted a linear model (estimated using OLS) to predict PV1MATH with PV1READ\n(formula: PV1MATH ~ PV1READ). The model explains a statistically significant\nand substantial proportion of variance (R2 = 0.69, F(1, 613742) = 1.37e+06, p <\n.001, adj. R2 = 0.69). The model's intercept, corresponding to PV1READ = 0, is\nat 102.10 (95% CI [101.52, 102.69], t(613742) = 342.54, p < .001). Within this\nmodel:\n\n  - The effect of PV1READ is statistically significant and positive (beta = 0.77,\n95% CI [0.77, 0.77], t(613742) = 1171.47, p < .001; Std. beta = 0.83, 95% CI\n[0.83, 0.83])\n\nStandardized parameters were obtained by fitting the model on a standardized\nversion of the dataset. 95% Confidence Intervals (CIs) and p-values were\ncomputed using a Wald t-distribution approximation.\n```\n\n\n:::\n:::\n\n\n<!--\n### Science self efficacy\n\nWe can also try and recreate fig. 4 from @stoet2018gender, looking at how self-efficacy in science `SCIEEFF` varies given the GGGI `Overall.Score`:\n-->\n\n::: {.cell}\n\n:::\n\n\nYou might also find that you want to convert the results of a linear model into a data frame for further analysis or plotting. To do this we can use the `{{broom}}` package and the `tidy()` function:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(broom)\nmdl <- lm(PV1MATH ~ PV1READ, data=PISA_2022)\ntidy(mdl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 5\n  term        estimate std.error statistic p.value\n  <chr>          <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)  102.     0.298         343.       0\n2 PV1READ        0.773  0.000660     1171.       0\n```\n\n\n:::\n:::\n\n\n::: callout-tip\n\nThe APA guidelines recommend reporting values to two decimal places, expect when extra precision is required (for example, when p-values are very small). To round the model above to two decimal places you can use the `gt` package, which produces well presented tables and the `fmt_number()` function to round the values to two decimal places, specifying which columns to round\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngt(tidy(mdl)) %>%\n  fmt_number(columns = c(estimate, std.error, statistic, p.value),\n             decimals = 2) \n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"fzfwdvofyc\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fzfwdvofyc table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fzfwdvofyc thead, #fzfwdvofyc tbody, #fzfwdvofyc tfoot, #fzfwdvofyc tr, #fzfwdvofyc td, #fzfwdvofyc th {\n  border-style: none;\n}\n\n#fzfwdvofyc p {\n  margin: 0;\n  padding: 0;\n}\n\n#fzfwdvofyc .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fzfwdvofyc .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fzfwdvofyc .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fzfwdvofyc .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fzfwdvofyc .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fzfwdvofyc .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fzfwdvofyc .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fzfwdvofyc .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fzfwdvofyc .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fzfwdvofyc .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fzfwdvofyc .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fzfwdvofyc .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fzfwdvofyc .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fzfwdvofyc .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fzfwdvofyc .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fzfwdvofyc .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fzfwdvofyc .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fzfwdvofyc .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fzfwdvofyc .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fzfwdvofyc .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fzfwdvofyc .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fzfwdvofyc .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fzfwdvofyc .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fzfwdvofyc .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fzfwdvofyc .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fzfwdvofyc .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fzfwdvofyc .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fzfwdvofyc .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fzfwdvofyc .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fzfwdvofyc .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fzfwdvofyc .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fzfwdvofyc .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fzfwdvofyc .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fzfwdvofyc .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fzfwdvofyc .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fzfwdvofyc .gt_left {\n  text-align: left;\n}\n\n#fzfwdvofyc .gt_center {\n  text-align: center;\n}\n\n#fzfwdvofyc .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fzfwdvofyc .gt_font_normal {\n  font-weight: normal;\n}\n\n#fzfwdvofyc .gt_font_bold {\n  font-weight: bold;\n}\n\n#fzfwdvofyc .gt_font_italic {\n  font-style: italic;\n}\n\n#fzfwdvofyc .gt_super {\n  font-size: 65%;\n}\n\n#fzfwdvofyc .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fzfwdvofyc .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fzfwdvofyc .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fzfwdvofyc .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fzfwdvofyc .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fzfwdvofyc .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fzfwdvofyc .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#fzfwdvofyc .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#fzfwdvofyc div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"term\">term</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"std.error\">std.error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">(Intercept)</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">102.10</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.30</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">342.54</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"term\" class=\"gt_row gt_left\">PV1READ</td>\n<td headers=\"estimate\" class=\"gt_row gt_right\">0.77</td>\n<td headers=\"std.error\" class=\"gt_row gt_right\">0.00</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">1,171.47</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.00</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n:::\n\n## Questions: Multivariable regression\n\n::: question\n1.  Can you explain the result of the following multivariable regression model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmdl <- lm(PV1MATH ~ ST016Q01NA + ST004D01T, data = PISA_2022)\nsummary(mdl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = PV1MATH ~ ST016Q01NA + ST004D01T, data = PISA_2022)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-446.40  -74.65   -8.02   68.69  476.42 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   446.31124    0.40789 1094.19   <2e-16 ***\nST016Q01NA     -1.81287    0.05404  -33.55   <2e-16 ***\nST004D01TMale   7.33878    0.28095   26.12   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 99.97 on 517070 degrees of freedom\n  (96671 observations deleted due to missingness)\nMultiple R-squared:  0.003065,\tAdjusted R-squared:  0.003061 \nF-statistic: 794.8 on 2 and 517070 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\n# The model is significant, p < 0.001, but the overall model has a very \n# small/insignificant effect size, R2 = 0.003, meaning the model explains \n# very little of the variance in maths scores. The estimate for ST016Q01NA \n# statistically significant with an estimate of -1.8, meaning for every \n# point increase in student satisfaction with life, their grades went down.\n# When controlling for life satisfaction, student gender was also \n# significant, with males typically getting 7.3 points more than females.\n```\n:::\n\n\n2.  Create a multivariable analysis to look at the impact of gender `ST004D01T` and parental involvement `PARINVOL` on reading scores. What is wrong with this model, how could you improve this model?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\nmdl <- lm(PV1READ ~ ST004D01T + PARINVOL, data = PISA_2022)\nsummary(mdl)\n\n# the R2 is very low, you could try adding more variables to the model, such as PV1SCIE\n# you could also try using the stepwise selection method to find the best model (see section above)\n# BUT always try and use variables in your models that you can make theoretical sense of\n# PARINVOL can be seen on table: 19.118\n# https://www.oecd.org/pisa/data/pisa2022technicalreport/PISA-2022-Technical-Report-Ch-19-PISA-Tables.xlsx\n```\n:::\n\n\n3.  For the following model, check that the assumptions needed for multivariable analysis have been met:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmdl <- lm(PV1SCIE ~ other_grades + ST004D01T + ESCS, \n          data = PISA_2022 %>% \n            filter(CNT == \"Brazil\") %>%\n            mutate(other_grades = (PV1MATH + PV1READ)/2))\nsummary(mdl)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\n# quickest way:\nlibrary(easystats)\ncheck_model(mdl)\n\n# For individual tests:\t   \nlibrary(car)\nlibrary(olsrr)\n\nmdl <- lm(PV1SCIE ~ other_grades + ST004D01T + ESCS, \n          data = PISA_2022 %>% \n            filter(CNT == \"Brazil\") %>%\n            mutate(other_grades = (PV1MATH + PV1READ)/2))\n\n# Independence\ndurbinWatsonTest(mdl)\n#> lag Autocorrelation D-W Statistic p-value\n#>   1      0.01650897      1.966672   0.094\n# p>0.05 therefore we can assume values are independent\n\n# No multicollinearity\nvif(mdl)\n#> other_grades    ST004D01T         ESCS \n#>     1.161354     1.004684     1.163242 \n# no value over 5, therefore we can assume no multicollinearity\n\n# Normality and Homoscedasticity\npar(mfrow = c(2, 2))\nplot(mdl)\n# QQ plot looks good and no funneling\n\n# Breusch-Pagan test p>0.05\n# therefore data is Homoscedastic\nols_test_breusch_pagan(mdl)\n\n#All tests check out, we can use the model\n```\n:::\n\n\n4.  Create your own multivariable analysis and present your findings to another person in your group. Are you able to explain the results to them? Does the model meet the assumptions necessary for a multivariable analysis?\n\n:::\n\n# Logistic regression\n\nSometimes the dependent variable will be *boolean*, that is a field that can only have two values, e.g. `True/False`, `Yes/No`, `High/Low`, etc. Unfortunately we can't use the linear model to do this as it assumes that the dependent variable is _continuous_, not _binary_ (or boolean). However, we can run _logistic_ regression models using the `glm()` command where the `family=` parameter is set to `binomial`. For example, let's imagine we want to predict whether a student scored in the top 5% of maths scores in the United Kingdom by looking at the gender and the wealth of a student (using the `ESCS` field).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# calculate whether a maths score is in the top 5% of scores for the UK\nPISA_2022_top_5 <- PISA_2022 %>% \n  filter(CNT == \"United Kingdom\") %>% \n  select(CNT, PV1MATH, PV1SCIE, PV1READ, ESCS, ST004D01T) %>%\n  rename(gender = ST004D01T) %>%\n  # add column with the percentage score for PV1MATH\n  mutate(top_5_per = \n           ifelse(PV1MATH > quantile(PV1MATH, probs = 0.95, na.rm = TRUE), \n                        1, 0),\n         z_ESCS = scale(ESCS)) # gives a standardised score for ESCS\n\nglm(top_5_per ~ gender + z_ESCS, \n    data = PISA_2022_top_5, family=\"binomial\") %>% summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = top_5_per ~ gender + z_ESCS, family = \"binomial\", \n    data = PISA_2022_top_5)\n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -3.43365    0.07642 -44.933  < 2e-16 ***\ngenderMale   0.41138    0.08682   4.738 2.15e-06 ***\nz_ESCS       0.95106    0.05411  17.576  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 4683.7  on 11083  degrees of freedom\nResidual deviance: 4279.8  on 11081  degrees of freedom\n  (1888 observations deleted due to missingness)\nAIC: 4285.8\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\nWe can see that Male students are significantly more likely to be in the top 5% for maths scores when you control for the wealth of the student, increasing the log odds by 0.41 units. The wealth of the student is also significant in predicting whether a student is in the top 5% of maths scores, with one standard deviation change^[for normally distributed data one SD will cover ~68% of responses] in wealth resulting a log odds increase of 0.95 units.\n\nYou can also use the _odds ratios_, which some people find easier to interpret, by setting the `exponentiate` parameter to `TRUE` in the `tbl_regression` command from the `{{gtsummary}}` package:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(gtsummary)\nglm(top_5_per ~ gender + z_ESCS , \n    data = PISA_2022_top_5, family=\"binomial\") %>% \n  tbl_regression(exponentiate = TRUE)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ujeyfachbn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ujeyfachbn table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ujeyfachbn thead, #ujeyfachbn tbody, #ujeyfachbn tfoot, #ujeyfachbn tr, #ujeyfachbn td, #ujeyfachbn th {\n  border-style: none;\n}\n\n#ujeyfachbn p {\n  margin: 0;\n  padding: 0;\n}\n\n#ujeyfachbn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ujeyfachbn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ujeyfachbn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ujeyfachbn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ujeyfachbn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ujeyfachbn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ujeyfachbn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ujeyfachbn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ujeyfachbn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ujeyfachbn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ujeyfachbn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ujeyfachbn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ujeyfachbn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ujeyfachbn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ujeyfachbn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ujeyfachbn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ujeyfachbn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ujeyfachbn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ujeyfachbn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ujeyfachbn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ujeyfachbn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ujeyfachbn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ujeyfachbn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ujeyfachbn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ujeyfachbn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ujeyfachbn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ujeyfachbn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ujeyfachbn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ujeyfachbn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ujeyfachbn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ujeyfachbn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ujeyfachbn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ujeyfachbn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ujeyfachbn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ujeyfachbn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ujeyfachbn .gt_left {\n  text-align: left;\n}\n\n#ujeyfachbn .gt_center {\n  text-align: center;\n}\n\n#ujeyfachbn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ujeyfachbn .gt_font_normal {\n  font-weight: normal;\n}\n\n#ujeyfachbn .gt_font_bold {\n  font-weight: bold;\n}\n\n#ujeyfachbn .gt_font_italic {\n  font-style: italic;\n}\n\n#ujeyfachbn .gt_super {\n  font-size: 65%;\n}\n\n#ujeyfachbn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ujeyfachbn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ujeyfachbn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ujeyfachbn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ujeyfachbn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ujeyfachbn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ujeyfachbn .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ujeyfachbn .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ujeyfachbn div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"label\"><span data-qmd-base64=\"KipDaGFyYWN0ZXJpc3RpYyoq\"><span class='gt_from_md'><strong>Characteristic</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\"><span data-qmd-base64=\"KipPUioq\"><span class='gt_from_md'><strong>OR</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\"><span data-qmd-base64=\"Kio5NSUgQ0kqKg==\"><span class='gt_from_md'><strong>95% CI</strong></span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\"><span data-qmd-base64=\"KipwLXZhbHVlKio=\"><span class='gt_from_md'><strong>p-value</strong></span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">gender</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">—</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">—</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">1.51</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">1.27, 1.79</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">z_ESCS</td>\n<td headers=\"estimate\" class=\"gt_row gt_center\">2.59</td>\n<td headers=\"conf.low\" class=\"gt_row gt_center\">2.33, 2.88</td>\n<td headers=\"p.value\" class=\"gt_row gt_center\"><0.001</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"4\"><span data-qmd-base64=\"QWJicmV2aWF0aW9uczogQ0kgPSBDb25maWRlbmNlIEludGVydmFsLCBPUiA9IE9kZHMgUmF0aW8=\"><span class='gt_from_md'>Abbreviations: CI = Confidence Interval, OR = Odds Ratio</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\nThere are many other types of regression for different outcome variables, e.g. _ordinal_ regression, _multilevel_ regression, and _Poisson_ regression for count data. We will not cover these here, but you can find out more about these in @field2012discovering.\n\n## Checking the assumptions of logistic regression\n\n@field2012discovering recommends that you check the assumptions of logistic regression by looking at :\n\n- __Linearity__ - there exists a linear relationship between the predictors and the _logit_ of the outcome variable (as the outcome can only assume two values, the logit is the natural log of the odds of the event happening)\n- __Independence of errors__ - data points should be independent of each other\n- __No-Multicollinearity__ - The independent variables should not be correlated with each other\n\nWe can test these using a number of methods, for example, we can use the `vif()` function from the `{{car}}` package to check for multicollinearity, the _Hosmer-Lemeshow_ `hltest()` from `{{glmtoolbox}}` package to test for Linearity (note that large datasets might result in low p-values and this test \"is to some extent obsolete\"^[https://stats.stackexchange.com/questions/18750/hosmer-lemeshow-vs-aic-for-logistic-regression]) and the `check_model` plots from the `{{easystats}}` package. For example\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(easystats)\nlibrary(glmtoolbox)\nlibrary(car)\n\n# make a logistic model \nmdl <- glm(top_5_per ~ gender + z_ESCS + z_PV1READ, \n    data = PISA_2022_top_5 %>% \n      mutate(z_ESCS = z_ESCS[,1],\n             z_PV1READ = scale(PV1READ)[,1]), \n    family=\"binomial\")\n\nvif(mdl)\nhltest(mdl)\ngrphs <- check_model(mdl)\ngrphs$PP_CHECK\n```\n:::\n\n\n# Seminar Tasks\n\n::: question\n\nGroup discussion:\n\n- What were the most important findings from Stoet and Geary's paper?\n- How trustworthy are the results?\n- What do these results mean for gender equality in STEM?\n\n1.  What are _Spearman's Rho_ and _Pearson's r_? When might you use one rather than the other?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\n#> When the data you use has outliers or is not \n#> normally distributed (non-parametric) you should use Spearman's Rho\n#> you can test this by checking that shapiro.test p >0.05\n```\n:::\n\n\n2.  Identify dependent and independent variables in the following scenarios and select the most appropriate statistical test (from all that you have learnt) for the analysis.\n\n-   The government is trying to understand which groups of people have been affected by a pandemic. They have data on healthcare professionals, education professionals and train drivers and the number of days taken off ill in the last 6 months.\n-   A cigarette company, working in a country that still allows cigarette advertising(!), wants to work out which groups in society are not currently smoking that many cigarettes. They want to find out if city dwellers are more likely to smoke than people living in the countryside.\n-   A netball team is trying to work out how likely their players are to get injured in a season. They have data on the number of injuries per player and the number of minutes each player has been playing netball.\n-   A country is trying to find out whether girls or boys are better behaved in schools. They have access to school databases that record the number of bad behaviour slips for each student.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\n# The government is trying to understand which groups of people have been affected by a pandemic. They have data on healthcare professionals, education professionals and train drivers and the number of days taken off ill in the last 6 months.\n#> Dependendent: days off ill\n#> Independent: job role\n#> Suggested model: ANOVA to check if there are differences between jobs\n\n# A cigarette company, working in a country that still allows cigarette advertising(!), wants to work out which groups in society are not currently smoking that many cigarettes. They want to find out if city dwellers are more likely to smoke than people living in the countryside.\n#> Dependent: Smoker / Non Smoker\n#> Independent: City / Countryside residence\n#> Suggested model: Chi-square\n\n# A netball team is trying to work out how likely their players are to get injured in a season. They have data on the number of injuries per player and the number of minutes each player has been playing netball.\n#> Dependent: injuries\n#> Independent: time on court\n#> Suggested model: Linear model/regression\n\n# A country is trying to find out whether girls or boys are better behaved in schools. They have access to school databases that record the number of bad behaviour slips for each student.\n#> Dependent: behaviour slips\n#> Independent: Gender (Girls/Boys)\n#> Suggested model: t-test\n```\n:::\n\n\n3.  Interpret this correlation coefficient between the Index of economic, social and cultural status `ESCS` and Home Possessions `HOMEPOS`\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  PISA_2022$ESCS and PISA_2022$HOMEPOS\nt = 999.75, df = 588185, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.7924824 0.7943760\nsample estimates:\n      cor \n0.7934311 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\n#> The Index of economic, social and cultural status `ESCS` is strongly\n#> correlated with home posessions `HOMEPOS`, with a correlation coefficient\n#> of 0.7934311. This model is significant with a p-value of < 0.001\n```\n:::\n\n\n4.  Interpret this linear model based on the FBI's 2006 crime statistics. It explores the relationship between size of population (1,000s) and the number of murders (units)[^FBI]:\n\n[^FBI]: https://www.statisticssolutions.com/the-linear-regression-analysis-in-spss/:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ywtdcjtats\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ywtdcjtats table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ywtdcjtats thead, #ywtdcjtats tbody, #ywtdcjtats tfoot, #ywtdcjtats tr, #ywtdcjtats td, #ywtdcjtats th {\n  border-style: none;\n}\n\n#ywtdcjtats p {\n  margin: 0;\n  padding: 0;\n}\n\n#ywtdcjtats .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ywtdcjtats .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ywtdcjtats .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ywtdcjtats .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ywtdcjtats .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ywtdcjtats .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ywtdcjtats .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ywtdcjtats .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ywtdcjtats .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ywtdcjtats .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ywtdcjtats .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ywtdcjtats .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ywtdcjtats .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ywtdcjtats .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ywtdcjtats .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ywtdcjtats .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ywtdcjtats .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ywtdcjtats .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ywtdcjtats .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ywtdcjtats .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ywtdcjtats .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ywtdcjtats .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ywtdcjtats .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ywtdcjtats .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ywtdcjtats .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ywtdcjtats .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ywtdcjtats .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ywtdcjtats .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ywtdcjtats .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ywtdcjtats .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ywtdcjtats .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ywtdcjtats .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ywtdcjtats .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ywtdcjtats .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ywtdcjtats .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ywtdcjtats .gt_left {\n  text-align: left;\n}\n\n#ywtdcjtats .gt_center {\n  text-align: center;\n}\n\n#ywtdcjtats .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ywtdcjtats .gt_font_normal {\n  font-weight: normal;\n}\n\n#ywtdcjtats .gt_font_bold {\n  font-weight: bold;\n}\n\n#ywtdcjtats .gt_font_italic {\n  font-style: italic;\n}\n\n#ywtdcjtats .gt_super {\n  font-size: 65%;\n}\n\n#ywtdcjtats .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ywtdcjtats .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ywtdcjtats .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ywtdcjtats .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ywtdcjtats .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ywtdcjtats .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ywtdcjtats .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ywtdcjtats .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ywtdcjtats div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"_\">_</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Estimate\">Estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Std.-Error\">Std. Error</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"t-value\">t value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Pr(&gt;|t|)\">Pr(&gt;|t|)</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"star\">star</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"_\" class=\"gt_row gt_left\">       (Intercept)</td>\n<td headers=\"Estimate\" class=\"gt_row gt_right\">-0.726</td>\n<td headers=\"Std. Error\" class=\"gt_row gt_right\">0.089</td>\n<td headers=\"t value\" class=\"gt_row gt_right\">-8.191</td>\n<td headers=\"Pr(>|t|)\" class=\"gt_row gt_left\">     &lt;2e-16</td>\n<td headers=\"star\" class=\"gt_row gt_right\"> ***</td></tr>\n    <tr><td headers=\"_\" class=\"gt_row gt_left\">       Pop_thou   </td>\n<td headers=\"Estimate\" class=\"gt_row gt_right\">0.103</td>\n<td headers=\"Std. Error\" class=\"gt_row gt_right\">0.001</td>\n<td headers=\"t value\" class=\"gt_row gt_right\">145.932</td>\n<td headers=\"Pr(>|t|)\" class=\"gt_row gt_left\">     &lt;2e-16</td>\n<td headers=\"star\" class=\"gt_row gt_right\"> ***</td></tr>\n  </tbody>\n  <tfoot>\n    <tr class=\"gt_sourcenotes\">\n      <td class=\"gt_sourcenote\" colspan=\"6\"><span data-qmd-base64=\"X0FkaiBSXjJeXyAwLjcyMQ==\"><span class='gt_from_md'><em>Adj R<sup>2</sup></em> 0.721</span></span></td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\n#> The model is pretty good at explaining the variance, The Adj. R2\n#> shows that population explains 72% of the variance in murders.\n#> The model is significant as p < 0.001. For every increase in \n#> population of 1000 people, the model predicts another 0.1 deaths.\n```\n:::\n\n\n5. Work out the correlation between a country's _mean_ female mathematics grade and _mean_ male mathematics grade. Should you use _Spearman's Rho_ or _Pearson's r_ in your model? Why? EXTENSION: try plotting this data to see if the `cor.test` result is correct\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\ndf <- PISA_2022 %>% group_by(CNT, ST004D01T) %>% summarise(maths = mean(PV1MATH))\n\nmaths_male   <- df %>% filter(ST004D01T == \"Male\")\nmaths_female <- df %>% filter(ST004D01T == \"Female\")\n\n#> As the shapiro wilkes test has a p-value > 0.05 for girls, \n#> we need to Spearman's Rho as the data is not normally distributed\n\nshapiro.test(maths_female$maths)\n#> p-value = 0.07514\n\nshapiro.test(maths_male$maths)\n#> p-value = 0.03921\n\ncor.test(maths_male$maths, maths_female$maths, method = \"spearman\")\n#> 0.9874121\n```\n:::\n\n\n6.  Create a linear model to explore the relationship between the Index of economic, social and cultural status (`ESCS`) and the grade in science (`PV1SCIE`)\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\nmdl <- lm(PV1SCIE ~ ESCS, data = PISA_2022)\nsummary(mdl)\n\n#> For every increase in ESCS score by 1 \n#> there is an increase in score of 40.0837 points, \n#> ESCS is a significant predictor p <2e-16 ***, \n#> but the overall model has a low R squared value of 0.1837\n```\n:::\n\n\nAdd the student maths score `PV1MATH` this model, how does this change the outcome? \n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\nmdl <- lm(PV1SCIE ~ ESCS + PV1MATH, data = PISA_2022)\nsummary(mdl)\n\n#> For every increase in ESCS grade, \n#> there is now a science score increase of only 3.225, \n#> i.e. when controlling for maths outcomes, ESCS \n#>  explains less of the overall science grade. \n#> Both factors remain significant and the overall model \n#> now has a very high R squared value of 0.7905\n```\n:::\n\n\n7.  Load the school level data set for 2022 (file [here](https://emckclac-my.sharepoint.com/:u:/g/personal/k1926273_kcl_ac_uk/EaEQPEKYzR9MmiqLBYXOhmYBNXYg15UoDKGip-78kS1DvA?e=q74fyK)) and explore the fields.\n\n  Using a linear model, how do \"Shortage of educational staff\" `STAFFSHORT` and \"Shortage of educational material\" `EDUSHORT` relate to \"Student behaviour hindering learning\" `STUBEHA`\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\nmdl <- lm(STUBEHA ~ STAFFSHORT + EDUSHORT, data=PISA_2022_school)\nsummary(mdl)\n\n#> STAFFSHORT has a slightly larger estimate, 0.339116, than EDUSHORT, 0.190948\n#> This means as staff and educational resource shortages increase, so does\n#> student behaviour hindering learning.\n#> Both factors are significant p <2e-16 ***\n#> The effect size of the overall model is relatively low, at 0.1983\n```\n:::\n\n\n  Adjust the model to incorporate the percentage of boys in a school (see `SC002Q01TA` and `SCHSIZE`), what difference does this make?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\ntbl_beh_predict <- PISA_2022_school %>% \n  mutate(boy_per = 100 * SC002Q01TA / SCHSIZE)\n\nmdl <- lm(STUBEHA ~ STAFFSHORT + EDUSHORT + boy_per, data=tbl_beh_predict)\nsummary(mdl)\n\n#> adding percentage of boys to the model increases the effect size to 0.2058,\n#> when controlling for boy_per the estimate of staff shortages\n#> decreases slightly, and the estimate of educational shortages\n#> increases. The estimate of boy_per is significant, for every \n#> one percent increase in boys in a school, student behaviour\n#> hindering learning increases by 0.002, this model shows an all \n#> girls school would likely have a student behaviour hindering\n#> learning value 0.2 lower than an all boys school!\n#> it'd be worth double checking to see if boy_per is parametric\n```\n:::\n\n\n  How does the explanatory value of this model change if you only look at schools in the UK?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\nmdl <- lm(STUBEHA ~ STAFFSHORT + EDUSHORT + boy_per, \n          data=tbl_beh_predict %>% filter(CNT == \"United Kingdom\"))\nsummary(mdl)\n\n#> for the UK the effect size is larger at 0.2291, more of the variance of\n#> STUBEHA is explained by this model than for other countries\n#> Educational resource shortages have a smaller impact on STUBEHA, \n#> than in other countries, with an estimate of 0.142237\n#> staff shortages have a bigger impact that other countries, with an\n#> estimate of 0.369571\n```\n:::\n\n\n8.  Using `left_join` (see @sec-leftjoin),  link each student record in `PISA_2022` to their school details (file [here](https://emckclac-my.sharepoint.com/:u:/g/personal/k1926273_kcl_ac_uk/EaEQPEKYzR9MmiqLBYXOhmYBNXYg15UoDKGip-78kS1DvA?e=q74fyK)). You will need need to `select` a subset of the school table to cover: \n`CNT, CNTSCHID, SC016Q02TA, SC156Q03HA, SC156Q04HA, SC154Q01HA,`\n`SC154Q02WA, SC154Q05WA, SC154Q08WA, SC154Q09HA, STRATIO, CLSIZE,`\n`EDUSHORT, STAFFSHORT, STUBEHA` \n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"left_join code\"}\n#> SC016Q02TA\tPercentage of total funding for school year from: Student fees or school charges paid by parents\n#> SC035Q01NA\tHow student tests are used: [Standardised tests]: To guide students' learning\n#> SC035Q10TA\tHow student tests are used: [Standardised tests]: To compare the school with other schools\n#> SC035Q08TB\tHow student tests are used: Teacher-developed tests: To identify aspects of instruction or the curriculum that could be improved\n#> SC035Q09NA\tHow student tests are used: [Standardised tests]: To adapt teaching to the students' needs\n#> SC035Q09NB\tHow student tests are used: Teacher-developed tests: To adapt teaching to the students' needs\n\n#> STRATIO\tStudent-Teacher ratio\n#> CLSIZE\tClass Size (cheating here slightly as this is a nominal field which roughly maps to the continuous) - in test English\n#> EDUSHORT\tShortage of educational material (WLE)\n#> STAFFSHORT\tShortage of educational staff (WLE)\n#> STUBEHA\tStudent behaviour hindering learning (WLE)\n\nPISA_2022_stusch <- \n  left_join(PISA_2022 %>% select(CNT, CNTSCHID, ST004D01T, HOMEPOS, \n                                 ESCS, PV1SCIE, PV1MATH, PV1READ), \n             PISA_2022_school %>% \n              select(CNT, CNTSCHID, SC016Q02TA, SC035Q01NA,\n                     SC035Q10TA, SC035Q08TB, SC035Q09NA, SC035Q09NB,\n                     STRATIO, CLSIZE, EDUSHORT, STAFFSHORT, STUBEHA))\n```\n:::\n\n\n  Using a linear model, find out how well the student teacher ratio `STRATIO` in a school predicts the `mean` maths achievement `PV1MATH` in that school. __HINT__: you need one row for each school, so use summarise with unique on `STRATIO` and mean on `PV1MATH`:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\nstu_tch_mat <- PISA_2022_stusch %>% \n  group_by(CNTSCHID) %>%\n  summarise(stu_tch_rat = unique(STRATIO),\n            maths = mean(PV1MATH))\n\nmdl_stu_tch_mat <- lm(maths ~ stu_tch_rat, data=stu_tch_mat)\nsummary(mdl_stu_tch_mat)\n\n#> it's significant p <2e-16 ***, but with a very low \n#> estimates/betas, i.e. one extra student per teacher \n#> decreases the maths score by just 1.3 points, \n#> additionally the R squared value is low 0.04486 \n#> this is \"low impact\" in the EEF toolkit\n```\n:::\n\n\n  Adjust the linear model used above to incorporate `STUBEHA`\t\"Student behaviour hindering learning\" in addition to the student teacher ratio:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\nstu_tch_mat_bev <- PISA_2022_stusch %>% \n  group_by(CNTSCHID) %>%\n  summarise(stu_tch_rat = unique(STRATIO),\n            behaviour = unique(STUBEHA),\n            maths = mean(PV1MATH))\n\n#> max(stu_tch_mat_bev$behaviour, na.rm = TRUE)\n#> min(stu_tch_mat_bev$behaviour, na.rm = TRUE)\n\nmdl_stu_tch_mat_bev <- lm(maths ~ stu_tch_rat + behaviour, data=stu_tch_mat_bev)\nsummary(mdl_stu_tch_mat_bev)\n\n#> both factors are significant p<2e-16 ***, but with low estimates/betas, \n#> i.e. one extra student per teacher decreases \n#> the maths score by 1.6 points and the aggregated student behaviour hinder \n#> learning decreases maths by 11.8 points \n#> (max behaviour = 4.1448, min = -4.432), additionally the R squared value \n#> is better, but still low 0.07449\n```\n:::\n\n\n8. Test the model for independence, multi-collinearity, normality and homoscedasticity.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\n# Independence\ndurbinWatsonTest(mdl_stu_tch_mat_bev)\n#> lag Autocorrelation D-W Statistic p-value\n#>   1      0.01650897      1.966672   0.094\n# p>0.05 therefore we can assume values are independent\n\n# No multicollinearity\nvif(mdl_stu_tch_mat_bev)\n#> stu_tch_rat   behaviour \n#>     1.00856     1.00856 \n# no value over 5, therefore we can assume no multicollinearity\n\n# Normality and Homoscedasticity\npar(mfrow = c(2, 2))\nplot(mdl_stu_tch_mat_bev)\n# QQ plot looks good but lots of outliers\n\n# Breusch-Pagan test p<0.05\n# therefore data is NOT Homoscedastic (which we can see from the graphs)\nols_test_breusch_pagan(mdl_stu_tch_mat_bev)\n\n# Unfortunately this model doesn't pass the assumptions of:\n# - Homoscedasticity, and\n# - Independence\n# and linear modelling doesn't appear appropriate here.\n# Maybe a subset of the countries might give a better result?\n```\n:::\n\n\n9. Explore the school data set to look at other interesting models. The school data set has a lot more numeric/continuous fields than the student table! To find these fields use this code:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"find numeric fields\"}\n# to get the names of numeric fields along with their labels\nnms <- PISA_2022_school %>% select(where(is.numeric)) %>% names()\nlbls <- map_dfr(nms,~{\n  #.x <- \"test\"\n  message(.x)\n  lbl <- attr(PISA_2022_school[[.x]], \"label\")\n  nme <- .x\n  row <- c(nme, lbl)\n  names(row) <- c(\"name\", \"label\")\n  return(row)\n})\n```\n:::\n\n\n10.  In pairs discuss how you could use correlation and regression in your own research. Start building some models to explore the data sets.\n\n11.  Recreate the Stoet & Geary analysis (see @sec-standard-stoet-geary) to see if there is a \"gender gap in intraindividual __mathematics__ scores\" that is \"larger in more gender-equal countries\". You might expect this to be the case as it exists for science. Is this a STEM wide finding? How does the science model look for 2022 data? Was it a one off finding?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"answer\"}\n# standardise the results for each student in line with pg7\n# https://eprints.leedsbeckett.ac.uk/id/eprint/4753/6/symplectic-version.pdf\n\nlibrary(tidyverse)\nlibrary(arrow)\nlibrary(ggrepel)\n\nPISA_2015_GGGI <- left_join(\n  PISA_2015 %>% select(CNT, ST004D01T, PV1MATH, PV1SCIE, PV1READ, SCIEEFF),\n  GGGI %>% select(Country, Overall.Score),\n  by=c(\"CNT\"=\"Country\"))\n\n# step 1\nPISA_2015z <- PISA_2015_GGGI %>% \n  rename(gender = ST004D01T) %>%\n  group_by(CNT) %>%\n  mutate(zMaths   = scale(PV1MATH),\n         zScience = scale(PV1SCIE), \n         zReading = scale(PV1READ))\n\n# step 2\nPISA_2015z <- PISA_2015z %>% \n  mutate(zGeneral = (zMaths + zScience + zReading) / 3)\n\n# step 3\nPISA_2015z <- PISA_2015z %>% \n  mutate(rel_MATH = zMaths   - zGeneral,\n         rel_SCIE = zScience - zGeneral,\n         rel_READ = zReading - zGeneral)\n\n# step 4 part 1\nPISA_2015z <- PISA_2015z %>% \n  group_by(CNT, gender) %>%\n  summarise(zMaths = mean(zMaths, na.rm=TRUE),\n            zScience = mean(zScience, na.rm=TRUE),\n            zReading = mean(zReading, na.rm=TRUE),\n            zGeneral = mean(zGeneral, na.rm=TRUE),\n            rel_MATH = zMaths - zGeneral,\n            rel_SCIE = zScience - zGeneral,\n            rel_READ = zReading - zGeneral,\n            gggi = unique(Overall.Score))\n\n# step 4 part 2\npisa_gggi_diff <- PISA_2015z %>%\n  select(CNT, gender, gggi, rel_MATH) %>%\n  pivot_wider(names_from = gender,\n              values_from = rel_MATH) %>%\n  mutate(difference =  Male - Female)\n\nggplot(pisa_gggi_diff,\n       aes(x=difference, y=gggi)) + \n  geom_point(colour=\"red\") +\n  geom_smooth(method=\"lm\") +\n  geom_text_repel(aes(label=CNT),\n            box.padding = 0.2,\n            max.overlaps = Inf,\n            colour=\"black\") +\n  xlab(paste0(\"relative difference in PV1MATH scores (male-female)\"))\n\n# perform correlation analysis\nresult <- cor.test(pisa_gggi_diff$gggi, \n                    pisa_gggi_diff$difference, \n                    method=\"spearman\")\nresult\n#> this result isn't significant as p-value > 0.05\n#> additionally the correlation coefficient is negative\n#> this suggests that the STEM gender paradox doesn't apply to maths.\n```\n:::\n\n\n:::\n\n# Extension topics\n\n## Standardising results with z-values {#sec-z-values}\n\nWhen we are trying to compare data between countries, our results can be heavily skewed by the overall performance of a country. For example, imagine we have country *A* and country *U*. Students in country *A* generally get high grades with a very high standard deviation, whilst students in country *U* generally get very low grades with a very low standard deviation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- data.frame(sex=c(\"M\",\"M\",\"M\",\"F\",\"F\",\"F\",\"M\",\"M\",\"M\",\"F\",\"F\",\"F\"),\n           country=c(\"A\",\"A\",\"A\",\"A\",\"A\",\"A\",\"U\",\"U\",\"U\",\"U\",\"U\",\"U\"),\n           grade=c(100,87,98,95,82,90,10,8,9,12,10,11))\n\ndf %>% group_by(country, sex) %>% \n  mutate(mgrade = mean(grade)) %>%\n  group_by(country) %>%\n  mutate(meancountry = mean(grade),\n         sdgrade = sd(grade)) %>%\n  pivot_wider(names_from = sex, values_from = mgrade) %>%\n  summarise(M_max = max(M, na.rm=TRUE),\n            `F_max` = max(`F`, na.rm=TRUE),\n            difference = M_max-`F_max`,\n            sd = max(sdgrade),\n            mean = max(meancountry))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 6\n  country M_max F_max difference    sd  mean\n  <chr>   <dbl> <dbl>      <dbl> <dbl> <dbl>\n1 A          95    89          6  6.90    92\n2 U           9    11         -2  1.41    10\n```\n\n\n:::\n:::\n\n\nIf we look for the difference in grades between females and males in country *A* we might see a massive difference, whilst female and male students in country *U* have a much smaller difference. We might then conclude that country *U* is more equitable. But in reality, because the standard deviation in country *U* is so small, the relative difference between females and males is actually larger than that seen in country *A*! To get around this problem, when dealing with situations like this, we can use *standardised*, or *z*, values. These z-values would be a student's grade in relation to the standard deviation of all of that country's grades.\n\nTo calculate the standardised *z-value* for each entry, we use:\n\n`(entry - mean of grouping) / sd of grouping`\n\nFor example, for the first Male student in country A who scored 100 points, we would calculate\n\n`(100 - 92) / 6.899 = 1.16`\n\nThis shows that this student got 1.16 standard deviations more than the mean of the population. For the first female in country U, we would calculate:\n\n`(12 - 10) / 1.141 = 1.75`\n\nThese two values are then directly comparable, the first males in country A is relatively closer to the mean grade of country A, than the first female in country U. How does this work out for the whole country? Going back to whether sex had a greater impact on results in country A or country U we can calculate the z-values for each student by using the `scale()` command:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndfz <- df %>% group_by(country) %>% \n  mutate(zgrade = scale(grade))\ndfz\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 12 × 4\n# Groups:   country [2]\n   sex   country grade zgrade[,1]\n   <chr> <chr>   <dbl>      <dbl>\n 1 M     A         100      1.16 \n 2 M     A          87     -0.725\n 3 M     A          98      0.870\n 4 F     A          95      0.435\n 5 F     A          82     -1.45 \n 6 F     A          90     -0.290\n 7 M     U          10      0    \n 8 M     U           8     -1.41 \n 9 M     U           9     -0.707\n10 F     U          12      1.41 \n11 F     U          10      0    \n12 F     U          11      0.707\n```\n\n\n:::\n:::\n\n\nWe can then group by country and by sex and see how the `mean` z-value varies\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndfz %>%\n  group_by(country, sex) %>%\n  summarise(mean_zgrade = mean(zgrade))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 3\n# Groups:   country [2]\n  country sex   mean_zgrade\n  <chr>   <chr>       <dbl>\n1 A       F          -0.435\n2 A       M           0.435\n3 U       F           0.707\n4 U       M          -0.707\n```\n\n\n:::\n:::\n\n\nWe can clearly see that the grades in country *A* are relatively closer to the mean of country *A*, than the grades in country *U*, meaning that there is less variation in country *A*.\n\n\n## Recreating Stoet and Geary's paper {#sec-Stoet-Geary}\n\nStoet and Geary's 2018 paper: *\"The Gender-Equality Paradox in Science, Technology, Engineering, and Mathematics Education\"* presented controversial findings, including how the increased female uptake of STEM degrees in country could be partially explained (using regression) by the decreased gender equality in that country. We are going to explore part of this paper by looking at another finding (figure 3a) that looked at girls' achievement in the `PISA_2015` science test compared to their maths and reading grades. Comparing this relative grade to boys in the same country, it showed that as gender equality of their country increased, the gap got bigger, i.e. the more gender equal a country, the worse the female relative performance in science.\n\n> The gender gap in intraindividual science scores (a) was larger in more gender-equal countries (*r~s~* = .42)\n\n<!-- fields used by stoet geary and 2012 equivalents\n\nMATHEFF 2012 MATINTFC 2012 SCIEEFF 2015-->\n\n## Loading data sets\n\nTo perform more complex analysis you will often want to join different data sets together. @stoet2018gender explore gender differences in outcomes with gender equality in countries (see their figures 3 and 4), by using the `PISA_2015` data set with the science efficacy `SCIEEFF`, and science performance (maybe `PV1SCIE`, or a aggregation of `PV1`, `PV2` etc ) fields; mapping this data set to the 2015 Global Gender Gap Index (GGGI). Let's try and recreate what they did.\n\nFirst we are going to download the GGGI, unfortunately, it's difficult to find the 2015 data set, so we'll use 2013 instead, which can be found [here](https://data.humdata.org/dataset/29f2f52f-a9c2-4ff9-a99e-42b894dc18e9/resource/a8fe8c72-1359-4ce3-b8cc-03d9e5e85875/download/table-3b-detailed-rankings-2013.csv)\n\nThe data is in a `.csv` format so we need to use `read.csv` to get it into R (make sure that you use `read.csv` rather than `read_csv` as the names will come out slightly differently)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load the GGGI\nGGGI <- read.csv(\"<folder>table-3b-detailed-rankings-2013.csv\")\n```\n:::\n\n\nIf we look at the names of the GGGI fields we find that there is a `Country` column and the `Overall.Score` column, these are the columns that we are interested in. We can also see that many of the top scoring countries, i.e. those with better gender equality are Nordic countries.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGGGI %>% head(5) %>% select(Country, Overall.Score)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      Country Overall.Score\n1     Iceland        0.8731\n2     Finland        0.8421\n3      Norway        0.8417\n4      Sweden        0.8129\n5 Philippines        0.7832\n```\n\n\n:::\n:::\n\n\nNow we will load the 2015 PISA data set, we have a `.parquet` copy for you [here](https://drive.google.com/file/d/18NpQO1DGY5dnjnlR2b3IF9Zv8xtpc1Fk/view?usp=share_link)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load PISA_2015 student data set\nPISA_2015 <- read_parquet(\"<folder>PISA_2015_student_subset.parquet\")\n```\n:::\n\n\n## Linking data using `left_join` {#sec-leftjoin}\n\nTo link the `GGGI` to the `PISA_2015` data set we will use the `left_join` function from the tidyverse. This takes a few parameters\n\n    left_join(<table_1>, <table_2>, by=<matching_field[s]>)\n\nWe will now join a subset of the `PISA_2015` data set to a subset of the `GGGI` scores:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPISA_2015_GGGI <- left_join(\n  PISA_2015 %>% select(CNT, ST004D01T, PV1MATH, PV1SCIE, PV1READ, SCIEEFF),\n  GGGI %>% select(Country, Overall.Score),\n  by=c(\"CNT\"=\"Country\"))\n```\n:::\n\n\n-   line 1, assigns `<-` the result of the `left_join` to a new object, `PISA_2015_GGGI`,\n-   line 2, specifies `<table_1>` to be `PISA_2015` with the selected fields, note we have chosen to use `PV1` grades here, it's unclear what the original paper uses (See @sec-PV for a discussion on the use of `PV` grades)\n-   line 3, specifies `<table_2>` to be `GGGI` with just the country and `Overall.Score` fields\n-   line 4, specifies the `<matching_field>` to be `CNT`from `PISA_2015` and `Country` from `GGGI`, this means that the data in `<table_2>` will be added to `<table_1>` where `CNT` and `Country` are the same. For example for every entry of `Finland` in `PISA_2015`, the `Overall.Score` of `0.8421` will be added. Where it can't find a matching country, e.g. Albania doesn't have a GGGI entry, `NA` will be added.\n\nYou can see the new data set has attached the `Overall.Score` field from `GGGI` to the selected fields from `PISA_2015`:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 7\n  CNT     ST004D01T PV1MATH PV1SCIE PV1READ SCIEEFF Overall.Score\n  <chr>   <fct>       <dbl>   <dbl>   <dbl>   <dbl>         <dbl>\n1 Albania Female       463.    517.    430.      NA         0.641\n2 Albania Female       430.    480.    463.      NA         0.641\n3 Albania Female       303.    447.    503.      NA         0.641\n```\n\n\n:::\n:::\n\n\n::: callout-tip\nThere are multiple types of join in the tidyverse, you can find out more about them [here](https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf)\n\n![The available joins in the tidyverse, CC 4.0, by rstudio.com](/images/joins.png)\n:::\n\n## Standardising PISA results {#sec-standard-stoet-geary}\n\nNext, we will try to wrangle the data into shape to recreate figure 3 from @stoet2018gender. To do this we first need to standardise the grades for maths, science and reading so we can compare the results of students between countries without low performing or high performing countries skewing the results (see @sec-z-values for details on how to standardise data). Following the steps outlined on page 7:\n\n> 1.  We standardized the mathematics, science, and reading scores on a nation-by-nation basis. We call these new standardized scores *zMath*, *zRead*, and *zScience*.\n> 2.  We calculated for each student the standardized average score of the new z-scores and we call this *zGeneral*.\n> 3.  Then, we calculated for each student their intra-individual strengths by subtracting *zGeneral* as follows: *relativeSciencestrength = zScience - zGeneral*, *relativeMathstrength = zMath - zGeneral*, *relativeReadingstrength = zReading - zGeneral*.\n> 4.  Finally, using these new intra-individual (relative) scores, we calculated for each country the averages for boys and girls and subtracted those to calculate the gender gaps in relative academic strengths\n\nproduces the following code:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"code\"}\n# standardise the results for each student in line with pg7\n# https://eprints.leedsbeckett.ac.uk/id/eprint/4753/6/symplectic-version.pdf\n\nlibrary(tidyverse)\nlibrary(arrow)\nlibrary(ggrepel)\n\n# step 1\nPISA_2015z <- PISA_2015_GGGI %>% \n  rename(gender = ST004D01T) %>%\n  group_by(CNT) %>%\n  mutate(zMaths   = scale(PV1MATH),\n         zScience = scale(PV1SCIE), \n         zReading = scale(PV1READ))\n\n# step 2\nPISA_2015z <- PISA_2015z %>% \n  mutate(zGeneral = (zMaths + zScience + zReading) / 3)\n\n# step 3\nPISA_2015z <- PISA_2015z %>% \n  mutate(rel_MATH = zMaths   - zGeneral,\n         rel_SCIE = zScience - zGeneral,\n         rel_READ = zReading - zGeneral)\n\n# step 4 part 1\nPISA_2015z <- PISA_2015z %>% \n  group_by(CNT, gender) %>%\n  summarise(zMaths = mean(zMaths, na.rm=TRUE),\n            zScience = mean(zScience, na.rm=TRUE),\n            zReading = mean(zReading, na.rm=TRUE),\n            zGeneral = mean(zGeneral, na.rm=TRUE),\n            rel_MATH = zMaths - zGeneral,\n            rel_SCIE = zScience - zGeneral,\n            rel_READ = zReading - zGeneral,\n            gggi = unique(Overall.Score))\n\n# step 4 part 2\npisa_gggi_diff <- PISA_2015z %>%\n  select(CNT, gender, gggi, rel_SCIE) %>%\n  pivot_wider(names_from = gender,\n              values_from = rel_SCIE) %>%\n  mutate(difference =  Male - Female)\n```\n:::\n\n\nFinally we will plot the results:\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\" code-summary=\"graph code\"}\nlibrary(ggrepel)\n\nggplot(pisa_gggi_diff,\n       aes(x=difference, y=gggi)) + \n  geom_point(colour=\"red\") +\n  geom_smooth(method=\"lm\") +\n  geom_text_repel(aes(label=CNT),\n            box.padding = 0.2,\n            max.overlaps = Inf,\n            colour=\"black\") +\n  xlab(paste0(\"relative difference in PV1SCIE scores (male-female)\"))\n```\n\n::: {.cell-output-display}\n![](10-Correlation_and_regression_files/figure-html/unnamed-chunk-76-1.png){width=95%}\n:::\n:::\n\n\nThe graph is pretty good recreation of what the paper presented, with the general shape the same; differences in grades for each country might be explained by the original paper using 5 plausible values rather than just `PV1SCIE`, as we have used [@stoet2020gender]. Does the statistical model stand up to scrutiny? To find out we will use *correlation*. Stoet and Geary used _Spearman's rho_, signified by the ~*s*~ in *r~s~*:\n\n> The most important and novel finding here is that the sex difference in intraindividual strength in science was higher and more favorable to boys in more gender-equal countries, *r~s~* = .42, 95% CI = \\[.19,.61\\], *p* \\< .001, *n* = 62 (Fig. 3a)\n\nWe can run our version of this model using the following:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult <- cor.test(pisa_gggi_diff$gggi, \n                    pisa_gggi_diff$difference, \n                    method=\"spearman\")\nresult\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tSpearman's rank correlation rho\n\ndata:  pisa_gggi_diff$gggi and pisa_gggi_diff$difference\nS = 24384, p-value = 0.02763\nalternative hypothesis: true rho is not equal to 0\nsample estimates:\n      rho \n0.2874342 \n```\n\n\n:::\n:::\n\n\nOur model doesn't show such a strong correlation. In fact, our model shows a \"weak positive\" relationship of just <code>0.287</code>, albeit a significant one (`p<0.05`).\n\nFor our version of this model it seems unnecessary to use Spearman's rho, the number of countries we are comparing with valid data is 59 (`pisa_gggi_diff %>% na.omit() %>% nrow()`), which is greater than 30 and using the *central limit theorem* we should be able to use _Pearson's r_. Additionally,`shapiro.test`on both difference and`gggi` give non-significant results, suggesting Pearson is the better test to use here:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(pisa_gggi_diff$gggi) \n#> p-value = 0.1226\nshapiro.test(pisa_gggi_diff$difference)\n#> p-value = 0.4078\n```\n:::\n\n\nIf we run the model again using Pearson's r, we get:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresult <- cor.test(pisa_gggi_diff$gggi, \n                    pisa_gggi_diff$difference, \n                    method=\"pearson\")\nresult\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's product-moment correlation\n\ndata:  pisa_gggi_diff$gggi and pisa_gggi_diff$difference\nt = 3.9972, df = 57, p-value = 0.0001863\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.2406661 0.6465242\nsample estimates:\n      cor \n0.4679109 \n```\n\n\n:::\n:::\n\n\nA result much closer to the one published. The differences here might be the result of the different GGGI data set we used or a difference in the way we calculated `difference`, or something to do with the correlation model used. It would be good to know!\n\nWe can also explore this data using regression and a linear model looking at the relationship between `difference` in grades and the `gggi` value for each country:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmdl <- lm(difference ~ gggi, data = pisa_gggi_diff)\nsummary(mdl)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = difference ~ gggi, data = pisa_gggi_diff)\n\nResiduals:\n      Min        1Q    Median        3Q       Max \n-0.067343 -0.018964 -0.003605  0.023548  0.083991 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -0.12926    0.05317  -2.431 0.018228 *  \ngggi         0.29826    0.07462   3.997 0.000186 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.03247 on 57 degrees of freedom\n  (14 observations deleted due to missingness)\nMultiple R-squared:  0.2189,\tAdjusted R-squared:  0.2052 \nF-statistic: 15.98 on 1 and 57 DF,  p-value: 0.0001863\n```\n\n\n:::\n:::\n\n\nThis model also finds a significant difference (`p<0.001`) and an estimate for gggi of <code>0.298</code>, i.e. for each increase of 1 in gggi, males will do <code>0.298</code> of a standard deviation better than females. The R^2^ is pretty decent too at <code>0.219</code> suggesting the finding that Stoet and Geary reported is a sound one.\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n<!--# Stoet Geary Maths-->\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n",
    "supporting": [
      "10-Correlation_and_regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}